using MOS.LibraryHein.Bhyt.HeinLevel;
using MOS.LibraryHein.Bhyt.HeinRightRoute;
using MOS.LibraryHein.Bhyt.HeinTreatmentType;
using MOS.LibraryHein.Bhyt.HeinUpToStandard;
using System.Collections.Generic;

namespace MOS.LibraryHein.Bhyt.HeinRatio
{
    class HeinRatioStoreNew
    {
        /// <summary>
        /// Ti le huong cua stent thu hai trong truong hop thuoc goi ky thuat cao
        /// </summary>
        public static readonly List<HeinRatioData> SECOND_STENT_HEIN_RATIO_STORE = new List<HeinRatioData>()
        {
            new HeinRatioData(null, null, HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData(null, null, HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData(null, null, HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData(null, null, HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),

            new HeinRatioData(null, null, HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData(null, null, HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData(null, null, HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData(null, null, HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.FALSE,null, (decimal)0.4),
        };

        /// <summary>
        /// Luu cau hinh ti le BHYT
        /// </summary>
        public static readonly List<HeinRatioData> HEIN_RATIO_STORE = new List<HeinRatioData>()
        {
            //Tuyen xa
            new HeinRatioData("1",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,null,HeinUpToStandardCode.TRUE,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,null,HeinUpToStandardCode.TRUE,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,null,HeinUpToStandardCode.TRUE,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("5",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.NORMAL,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.HIGH,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.COMMUNE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),

            //Tuyen huyen
            new HeinRatioData("1",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)0.95),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,null,HeinUpToStandardCode.TRUE,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0.95),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.95),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)0.95),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0.95),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.95),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)0.8),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,null,HeinUpToStandardCode.TRUE,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0.8),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.8),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)0.8),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,null,HeinUpToStandardCode.TRUE,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0.8),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.8),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("5",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.NORMAL,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.HIGH,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.DISTRICT,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),

            //Tuyen tinh
            new HeinRatioData("1",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),            
            new HeinRatioData("1",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),            
            new HeinRatioData("1",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("1",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("2",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("2",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("2",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)0.95),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,null,HeinUpToStandardCode.TRUE,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.95),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)0.95),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.95),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)0.8),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,null,HeinUpToStandardCode.TRUE,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.8),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)0.8),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,null,HeinUpToStandardCode.TRUE,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.8),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("5",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("5",HeinRatioTypeCode.NORMAL,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("5",HeinRatioTypeCode.HIGH,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("5",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.PROVINCE,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)1),

            //Tuyen trung uong
            new HeinRatioData("1",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("1",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.4),
            new HeinRatioData("1",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("1",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.4),
            new HeinRatioData("1",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("1",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("1",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.4),
            new HeinRatioData("2",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("2",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.4),
            new HeinRatioData("2",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("2",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.4),
            new HeinRatioData("2",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("2",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("2",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.4),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)0.95),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,null,HeinUpToStandardCode.TRUE,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.38),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)0.4),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)0.4),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)0.95),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,true, (decimal)1),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.38),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)0.4),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)0.4),
            new HeinRatioData("3",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("3",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)0.8),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,null,HeinUpToStandardCode.TRUE,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,true, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.32),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)0.4),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)0.4),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)0.8),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,null,HeinUpToStandardCode.TRUE,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.32),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,true, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,true, (decimal)0.4),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,HeinUpToStandardCode.TRUE,HeinRightRouteCode.FALSE,null, (decimal)0.4),
            new HeinRatioData("4",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("4",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("5",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("5",HeinRatioTypeCode.NORMAL,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.4),
            new HeinRatioData("5",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("5",HeinRatioTypeCode.HIGH,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.4),
            new HeinRatioData("5",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,null,null,HeinRightRouteCode.TRUE,null, (decimal)1),
            new HeinRatioData("5",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.EXAM,null,HeinRightRouteCode.FALSE,null, (decimal)0),
            new HeinRatioData("5",HeinRatioTypeCode.TRANSPORT,HeinLevelCode.NATIONAL,HeinTreatmentTypeCode.TREAT,null,HeinRightRouteCode.FALSE,null, (decimal)0.4),
        };
    }
}
