//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDA.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SDA_PROVINCE
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string PROVINCE_CODE { get; set; }
        public string PROVINCE_NAME { get; set; }
        public long NATIONAL_ID { get; set; }
        public string SEARCH_CODE { get; set; }
        public string NATIONAL_CODE { get; set; }
        public string NATIONAL_NAME { get; set; }
        public string ID_PATH { get; set; }
        public string CODE_PATH { get; set; }
    }
}
