
namespace HIS.Desktop.Plugins.AssignServiceEdit.Base
{
    internal class AppConfigKeys
    {
        #region Public key
        internal const string CONFIG_KEY__DEFAULT_CONFIG_PATIENT_TYPE_CODE = "CONFIG_KEY__DEFAULT_CONFIG_PATIENT_TYPE_CODE";
        public const string HFS_KEY__PAY_FORM_CODE = "HFS_KEY__PAY_FORM_CODE";
        public const string CONFIG_KEY__MODULE_CHI_DINH_DICH_VU__AN_HIEN_TAB = "CONFIG_KEY__MODULE_CHI_DINH_DICH_VU__AN_HIEN_TAB";
        public const string CONFIG_KEY__MODULE_CHI_DINH_DICH_VU__AN_HIEN_CP_NGOAI_GOI = "CONFIG_KEY__MODULE_CHI_DINH_DICH_VU__AN_HIEN_CP_NGOAI_GOI";
        public const string CONFIG_KEY__MODULE_CHI_DINH_DICH_VU__AN_HIEN_HAO_PHI = "CONFIG_KEY__MODULE_CHI_DINH_DICH_VU__AN_HIEN_HAO_PHI";
        public const string CONFIG_KEY__MODULE_CHI_DINH_DICH_VU__AN_HIEN_GIA_GOI = "CONFIG_KEY__MODULE_CHI_DINH_DICH_VU__AN_HIEN_GIA_GOI";

        public const string CONFIG_KEY__IN_SAU_KHI_LUU_MAN_HINH_TIEP_DON = "CONFIG_KEY__IN_SAU_KHI_LUU_MAN_HINH_TIEP_DON";
        public const string CONFIG_KEY__TIEP_DON_HIEN_THI_THONG_TIN_THEM = "CONFIG_KEY__TIEP_DON_HIEN_THI_THONG_TIN_THEM";
        public const string CONFIG_KEY__HIEN_THI_NOI_LAM_VIEC_THEO_DINH_DANG_MAN_HINH_DANG_KY = "CONFIG_KEY__HIEN_THI_NOI_LAM_VIEC_THEO_DINH_DANG_MAN_HINH_DANG_KY";
        public const string CONFIG_KEY__CHE_DO_IN_PHIEU_DANG_KY_DICH_VU_KHAM_BENH = "CONFIG_KEY__CHE_DO_IN_PHIEU_DANG_KY_DICH_VU_KHAM_BENH";
        public const string CONFIG_KEY__CHE_DO_HIEN_THI_CAC_YEU_CAU_DICH_VU = "CONFIG_KEY__CHE_DO_HIEN_THI_CAC_YEU_CAU_DICH_VU";
        public const string CONFIG_KEY__FILL_DU_LIEU_TU_DONG_VAO_O_DIA_CHI_BENH_NHAN_CHIP_THE_MAN_HINH_DANG_KY = "CONFIG_KEY__FILL_DU_LIEU_TU_DONG_VAO_O_DIA_CHI_BENH_NHAN_CHIP_THE_MAN_HINH_DANG_KY"; 
        public const string CONFIG_KEY__ALERT_EXPRIED_TIME_HEIN_CARD_BHYT = "CONFIG_KEY__ALERT_EXPRIED_TIME_HEIN_CARD_BHYT";
        public const string CONFIG_KEY__CHI_DINH_NHANH_THUOC_VAT_TU = "CONFIG_KEY__CHI_DINH_NHANH_THUOC_VAT_TU";
        public const string CONFIG_KEY__DUONG_DAN_CHAY_FILE_VIDEO = "CONFIG_KEY__DUONG_DAN_CHAY_FILE_VIDEO";
        public const string CONFIG_KEY__SO_BENH_NHAN_TREN_DANH_SACH_CHO_KHAM_VA_CLS = "CONFIG_KEY__SO_BENH_NHAN_TREN_DANH_SACH_CHO_KHAM_VA_CLS";
        public const string CONFIG_KEY__DIRECTORY_ADVERTISEMENT = "CONFIG_KEY__DIRECTORY_ADVERTISEMENT";
        public const string CONFIG_KEY__CHE_DO_KE_DON_THUOC__MOT_HOAC_NHIEU_KHO = "CONFIG_KEY__CHE_DO_KE_DON_THUOC__MOT_HOAC_NHIEU_KHO";
        public const string CONFIG_KEY__CHE_DO_PHIEU_LINH_THUOC_GAY_NGHIEN_HUONG_TAM_THAN = "CONFIG_KEY__CHE_DO_PHIEU_LINH_THUOC_GAY_NGHIEN_HUONG_TAM_THAN";
        public const string CONFIG_KEY__DANG_KY_TIEP_DON__THU_TIEN_SAU = "CONFIG_KEY__DEFAULT_CONFIG_IS_NOT_REQUIRE_FEE";
        public const string CONFIG_KEY__DANG_KY_TIEP_DON__THOI_GIAN_LOAD_DANH_SACH_PHONG_KHAM = "CONFIG_KEY__DANG_KY_TIEP_DON__THOI_GIAN_LOAD_DANH_SACH_PHONG_KHAM";
        public const string CONFIG_KEY__DANG_KY_TIEP_DON__GOI_BENH_NHAN_BANG_PHAN_MEM_CPA = "CONFIG_KEY__DANG_KY_TIEP_DON__GOI_BENH_NHAN_BANG_CPA";
        public const string CONFIG_KEY__DANG_KY_TIEP_DON__HIEN_THI_THONG_BAO_TIM_THAY_BN_THEO_THONG_TIN_NHAP = "CONFIG_KEY__DANG_KY_TIEP_DON__HIEN_THI_THONG_BAO_TIM_THAY_BN_THEO_THONG_TIN_NHAP";
        public const string CONFIG_KEY__HIS_DESKTOP__AUTO_TOKEN_LOGOUT_WHILE_CLOSE_APPLICATION = "CONFIG_KEY__HIS_DESKTOP__AUTO_TOKEN_LOGOUT_WHILE_CLOSE_APPLICATION";
        public const string CONFIG_KEY__EXAM_SERVICE_REQ_EXCUTE_HIDE_TABS_INFOMATION__APPLICATION = "CONFIG_KEY__EXAM_SERVICE_REQ_EXCUTE_HIDE_TABS_INFOMATION__APPLICATION";
        public const string CONFIG_KEY__HIS_DESKTOP__ASSIGN_PRESCRIPTION__ISVISIBLE_REMEDY_COUNT = "CONFIG_KEY__HIS_DESKTOP__ASSIGN_PRESCRIPTION__ISVISIBLE_REMEDY_COUNT";
        public const string CONFIG_KEY__HIS_DESKTOP__ASSIGN_PRESCRIPTION__IS_PRINT_NOW = "CONFIG_KEY__HIS_DESKTOP__ASSIGN_PRESCRIPTION__IS_PRINT_NOW";
        
        #endregion
    }
}
