//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTC.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTC_REPARTITION_TYPE
    {
        public HTC_REPARTITION_TYPE()
        {
            this.HTC_REPARTITION_RATIO = new HashSet<HTC_REPARTITION_RATIO>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string REPARTITION_TYPE_CODE { get; set; }
        public string REPARTITION_TYPE_NAME { get; set; }
        public Nullable<short> IS_HAS_NOT_RATIO { get; set; }
    
        public virtual ICollection<HTC_REPARTITION_RATIO> HTC_REPARTITION_RATIO { get; set; }
    }
}
