//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDA.LibraryBug {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDA.LibraryBug.CodeResource", typeof(CodeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA007.
        /// </summary>
        internal static string Common__CapNhatThatBai {
            get {
                return ResourceManager.GetString("Common__CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA006.
        /// </summary>
        internal static string Common__DuLieuDangBiKhoa {
            get {
                return ResourceManager.GetString("Common__DuLieuDangBiKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA004.
        /// </summary>
        internal static string Common__FactoryKhoiTaoDoiTuongThatBai {
            get {
                return ResourceManager.GetString("Common__FactoryKhoiTaoDoiTuongThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA001.
        /// </summary>
        internal static string Common__KXDDDuLieuCanXuLy {
            get {
                return ResourceManager.GetString("Common__KXDDDuLieuCanXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA003.
        /// </summary>
        internal static string Common__LoiCauHinhHeThong {
            get {
                return ResourceManager.GetString("Common__LoiCauHinhHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA005.
        /// </summary>
        internal static string Common__MaDaTonTai {
            get {
                return ResourceManager.GetString("Common__MaDaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA008.
        /// </summary>
        internal static string Common__ThemMoiThatBai {
            get {
                return ResourceManager.GetString("Common__ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA002.
        /// </summary>
        internal static string Common__ThieuThongTinBatBuoc {
            get {
                return ResourceManager.GetString("Common__ThieuThongTinBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA015.
        /// </summary>
        internal static string SdaCustomizeButton_CapNhatThatBai {
            get {
                return ResourceManager.GetString("SdaCustomizeButton_CapNhatThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA016.
        /// </summary>
        internal static string SdaCustomizeButton_ThemMoiThatBai {
            get {
                return ResourceManager.GetString("SdaCustomizeButton_ThemMoiThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA009.
        /// </summary>
        internal static string SdaEventLog_EventLogTypeIdKhongDung {
            get {
                return ResourceManager.GetString("SdaEventLog_EventLogTypeIdKhongDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA013.
        /// </summary>
        internal static string SdaGroup_CoLoiTrongQuaTrinhCapNhatPathCuaTatCaDonVi {
            get {
                return ResourceManager.GetString("SdaGroup_CoLoiTrongQuaTrinhCapNhatPathCuaTatCaDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA010.
        /// </summary>
        internal static string SdaGroup_DAOTruncateGroupThatBai {
            get {
                return ResourceManager.GetString("SdaGroup_DAOTruncateGroupThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA014.
        /// </summary>
        internal static string SdaGroup_DonViKhongCoPath {
            get {
                return ResourceManager.GetString("SdaGroup_DonViKhongCoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA011.
        /// </summary>
        internal static string SdaGroup_KhongUpdateDuocGroupPath {
            get {
                return ResourceManager.GetString("SdaGroup_KhongUpdateDuocGroupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDA012.
        /// </summary>
        internal static string SdaGroup_KhongXoaDuocCacDonViCon {
            get {
                return ResourceManager.GetString("SdaGroup_KhongXoaDuocCacDonViCon", resourceCulture);
            }
        }
    }
}
