using Inventec.Common.Repository;

namespace MRS.Processor.Mrs00105
{
    static class DAOWorker
    {
        internal static MOS.DAO.HisCard.HisCardDAO HisCardDAO { get { return (MOS.DAO.HisCard.HisCardDAO)Worker.Get<MOS.DAO.HisCard.HisCardDAO>(); } }
        internal static MOS.DAO.HisIcd.HisIcdDAO HisIcdDAO { get { return (MOS.DAO.HisIcd.HisIcdDAO)Worker.Get<MOS.DAO.HisIcd.HisIcdDAO>(); } }
        internal static MOS.DAO.HisPatient.HisPatientDAO HisPatientDAO { get { return (MOS.DAO.HisPatient.HisPatientDAO)Worker.Get<MOS.DAO.HisPatient.HisPatientDAO>(); } }
        internal static MOS.DAO.HisPatientType.HisPatientTypeDAO HisPatientTypeDAO { get { return (MOS.DAO.HisPatientType.HisPatientTypeDAO)Worker.Get<MOS.DAO.HisPatientType.HisPatientTypeDAO>(); } }
        internal static MOS.DAO.HisService.HisServiceDAO HisServiceDAO { get { return (MOS.DAO.HisService.HisServiceDAO)Worker.Get<MOS.DAO.HisService.HisServiceDAO>(); } }
        internal static MOS.DAO.HisServiceGroup.HisServiceGroupDAO HisServiceGroupDAO { get { return (MOS.DAO.HisServiceGroup.HisServiceGroupDAO)Worker.Get<MOS.DAO.HisServiceGroup.HisServiceGroupDAO>(); } }
        internal static MOS.DAO.HisServiceReq.HisServiceReqDAO HisServiceReqDAO { get { return (MOS.DAO.HisServiceReq.HisServiceReqDAO)Worker.Get<MOS.DAO.HisServiceReq.HisServiceReqDAO>(); } }
        internal static MOS.DAO.HisServiceType.HisServiceTypeDAO HisServiceTypeDAO { get { return (MOS.DAO.HisServiceType.HisServiceTypeDAO)Worker.Get<MOS.DAO.HisServiceType.HisServiceTypeDAO>(); } }
        internal static MOS.DAO.HisTranPatiForm.HisTranPatiFormDAO HisTranPatiFormDAO { get { return (MOS.DAO.HisTranPatiForm.HisTranPatiFormDAO)Worker.Get<MOS.DAO.HisTranPatiForm.HisTranPatiFormDAO>(); } }
        internal static MOS.DAO.HisTranPatiReason.HisTranPatiReasonDAO HisTranPatiReasonDAO { get { return (MOS.DAO.HisTranPatiReason.HisTranPatiReasonDAO)Worker.Get<MOS.DAO.HisTranPatiReason.HisTranPatiReasonDAO>(); } }
        internal static MOS.DAO.HisServicePaty.HisServicePatyDAO HisServicePatyDAO { get { return (MOS.DAO.HisServicePaty.HisServicePatyDAO)Worker.Get<MOS.DAO.HisServicePaty.HisServicePatyDAO>(); } }
        internal static MOS.DAO.HisDepartment.HisDepartmentDAO HisDepartmentDAO { get { return (MOS.DAO.HisDepartment.HisDepartmentDAO)Worker.Get<MOS.DAO.HisDepartment.HisDepartmentDAO>(); } }
        internal static MOS.DAO.HisServiceReqStt.HisServiceReqSttDAO HisServiceReqSttDAO { get { return (MOS.DAO.HisServiceReqStt.HisServiceReqSttDAO)Worker.Get<MOS.DAO.HisServiceReqStt.HisServiceReqSttDAO>(); } }
        internal static MOS.DAO.HisAccountBook.HisAccountBookDAO HisAccountBookDAO { get { return (MOS.DAO.HisAccountBook.HisAccountBookDAO)Worker.Get<MOS.DAO.HisAccountBook.HisAccountBookDAO>(); } }
        internal static MOS.DAO.HisPayForm.HisPayFormDAO HisPayFormDAO { get { return (MOS.DAO.HisPayForm.HisPayFormDAO)Worker.Get<MOS.DAO.HisPayForm.HisPayFormDAO>(); } }
        internal static MOS.DAO.HisSereServ.HisSereServDAO HisSereServDAO { get { return (MOS.DAO.HisSereServ.HisSereServDAO)Worker.Get<MOS.DAO.HisSereServ.HisSereServDAO>(); } }
        internal static MOS.DAO.HisTransaction.HisTransactionDAO HisTransactionDAO { get { return (MOS.DAO.HisTransaction.HisTransactionDAO)Worker.Get<MOS.DAO.HisTransaction.HisTransactionDAO>(); } }
        internal static MOS.DAO.HisDhst.HisDhstDAO HisDhstDAO { get { return (MOS.DAO.HisDhst.HisDhstDAO)Worker.Get<MOS.DAO.HisDhst.HisDhstDAO>(); } }
        internal static MOS.DAO.HisTransactionType.HisTransactionTypeDAO HisTransactionTypeDAO { get { return (MOS.DAO.HisTransactionType.HisTransactionTypeDAO)Worker.Get<MOS.DAO.HisTransactionType.HisTransactionTypeDAO>(); } }
        internal static MOS.DAO.HisServiceRoom.HisServiceRoomDAO HisServiceRoomDAO { get { return (MOS.DAO.HisServiceRoom.HisServiceRoomDAO)Worker.Get<MOS.DAO.HisServiceRoom.HisServiceRoomDAO>(); } }
        internal static MOS.DAO.HisRoom.HisRoomDAO HisRoomDAO { get { return (MOS.DAO.HisRoom.HisRoomDAO)Worker.Get<MOS.DAO.HisRoom.HisRoomDAO>(); } }
        internal static MOS.DAO.HisUserRoom.HisUserRoomDAO HisUserRoomDAO { get { return (MOS.DAO.HisUserRoom.HisUserRoomDAO)Worker.Get<MOS.DAO.HisUserRoom.HisUserRoomDAO>(); } }
        internal static MOS.DAO.HisServicePackage.HisServicePackageDAO HisServicePackageDAO { get { return (MOS.DAO.HisServicePackage.HisServicePackageDAO)Worker.Get<MOS.DAO.HisServicePackage.HisServicePackageDAO>(); } }
        internal static MOS.DAO.HisTestIndexRange.HisTestIndexRangeDAO HisTestIndexRangeDAO { get { return (MOS.DAO.HisTestIndexRange.HisTestIndexRangeDAO)Worker.Get<MOS.DAO.HisTestIndexRange.HisTestIndexRangeDAO>(); } }
        internal static MOS.DAO.HisTestIndex.HisTestIndexDAO HisTestIndexDAO { get { return (MOS.DAO.HisTestIndex.HisTestIndexDAO)Worker.Get<MOS.DAO.HisTestIndex.HisTestIndexDAO>(); } }
        internal static MOS.DAO.HisSereServTein.HisSereServTeinDAO HisSereServTeinDAO { get { return (MOS.DAO.HisSereServTein.HisSereServTeinDAO)Worker.Get<MOS.DAO.HisSereServTein.HisSereServTeinDAO>(); } }
        internal static MOS.DAO.HisBedRoom.HisBedRoomDAO HisBedRoomDAO { get { return (MOS.DAO.HisBedRoom.HisBedRoomDAO)Worker.Get<MOS.DAO.HisBedRoom.HisBedRoomDAO>(); } }
        internal static MOS.DAO.HisGender.HisGenderDAO HisGenderDAO { get { return (MOS.DAO.HisGender.HisGenderDAO)Worker.Get<MOS.DAO.HisGender.HisGenderDAO>(); } }
        internal static MOS.DAO.HisMediStock.HisMediStockDAO HisMediStockDAO { get { return (MOS.DAO.HisMediStock.HisMediStockDAO)Worker.Get<MOS.DAO.HisMediStock.HisMediStockDAO>(); } }
        internal static MOS.DAO.HisMedicineUseForm.HisMedicineUseFormDAO HisMedicineUseFormDAO { get { return (MOS.DAO.HisMedicineUseForm.HisMedicineUseFormDAO)Worker.Get<MOS.DAO.HisMedicineUseForm.HisMedicineUseFormDAO>(); } }
        internal static MOS.DAO.HisMaterialType.HisMaterialTypeDAO HisMaterialTypeDAO { get { return (MOS.DAO.HisMaterialType.HisMaterialTypeDAO)Worker.Get<MOS.DAO.HisMaterialType.HisMaterialTypeDAO>(); } }
        internal static MOS.DAO.HisMaterial.HisMaterialDAO HisMaterialDAO { get { return (MOS.DAO.HisMaterial.HisMaterialDAO)Worker.Get<MOS.DAO.HisMaterial.HisMaterialDAO>(); } }
        internal static MOS.DAO.HisActiveIngredient.HisActiveIngredientDAO HisActiveIngredientDAO { get { return (MOS.DAO.HisActiveIngredient.HisActiveIngredientDAO)Worker.Get<MOS.DAO.HisActiveIngredient.HisActiveIngredientDAO>(); } }
        internal static MOS.DAO.HisMedicineBean.HisMedicineBeanDAO HisMedicineBeanDAO { get { return (MOS.DAO.HisMedicineBean.HisMedicineBeanDAO)Worker.Get<MOS.DAO.HisMedicineBean.HisMedicineBeanDAO>(); } }
        internal static MOS.DAO.HisImpMest.HisImpMestDAO HisImpMestDAO { get { return (MOS.DAO.HisImpMest.HisImpMestDAO)Worker.Get<MOS.DAO.HisImpMest.HisImpMestDAO>(); } }
        internal static MOS.DAO.HisExpMest.HisExpMestDAO HisExpMestDAO { get { return (MOS.DAO.HisExpMest.HisExpMestDAO)Worker.Get<MOS.DAO.HisExpMest.HisExpMestDAO>(); } }
        internal static MOS.DAO.HisImpMestType.HisImpMestTypeDAO HisImpMestTypeDAO { get { return (MOS.DAO.HisImpMestType.HisImpMestTypeDAO)Worker.Get<MOS.DAO.HisImpMestType.HisImpMestTypeDAO>(); } }
        internal static MOS.DAO.HisImpMestStt.HisImpMestSttDAO HisImpMestSttDAO { get { return (MOS.DAO.HisImpMestStt.HisImpMestSttDAO)Worker.Get<MOS.DAO.HisImpMestStt.HisImpMestSttDAO>(); } }
        internal static MOS.DAO.HisExpMestType.HisExpMestTypeDAO HisExpMestTypeDAO { get { return (MOS.DAO.HisExpMestType.HisExpMestTypeDAO)Worker.Get<MOS.DAO.HisExpMestType.HisExpMestTypeDAO>(); } }
        internal static MOS.DAO.HisExpMestStt.HisExpMestSttDAO HisExpMestSttDAO { get { return (MOS.DAO.HisExpMestStt.HisExpMestSttDAO)Worker.Get<MOS.DAO.HisExpMestStt.HisExpMestSttDAO>(); } }
        internal static MOS.DAO.HisMedicineType.HisMedicineTypeDAO HisMedicineTypeDAO { get { return (MOS.DAO.HisMedicineType.HisMedicineTypeDAO)Worker.Get<MOS.DAO.HisMedicineType.HisMedicineTypeDAO>(); } }
        internal static MOS.DAO.HisMedicine.HisMedicineDAO HisMedicineDAO { get { return (MOS.DAO.HisMedicine.HisMedicineDAO)Worker.Get<MOS.DAO.HisMedicine.HisMedicineDAO>(); } }
        internal static MOS.DAO.HisMedicinePaty.HisMedicinePatyDAO HisMedicinePatyDAO { get { return (MOS.DAO.HisMedicinePaty.HisMedicinePatyDAO)Worker.Get<MOS.DAO.HisMedicinePaty.HisMedicinePatyDAO>(); } }
        internal static MOS.DAO.HisImpMestMedicine.HisImpMestMedicineDAO HisImpMestMedicineDAO { get { return (MOS.DAO.HisImpMestMedicine.HisImpMestMedicineDAO)Worker.Get<MOS.DAO.HisImpMestMedicine.HisImpMestMedicineDAO>(); } }
        internal static MOS.DAO.HisExpMestMedicine.HisExpMestMedicineDAO HisExpMestMedicineDAO { get { return (MOS.DAO.HisExpMestMedicine.HisExpMestMedicineDAO)Worker.Get<MOS.DAO.HisExpMestMedicine.HisExpMestMedicineDAO>(); } }
        internal static MOS.DAO.HisMediStockMety.HisMediStockMetyDAO HisMediStockMetyDAO { get { return (MOS.DAO.HisMediStockMety.HisMediStockMetyDAO)Worker.Get<MOS.DAO.HisMediStockMety.HisMediStockMetyDAO>(); } }
        internal static MOS.DAO.HisMediStockMaty.HisMediStockMatyDAO HisMediStockMatyDAO { get { return (MOS.DAO.HisMediStockMaty.HisMediStockMatyDAO)Worker.Get<MOS.DAO.HisMediStockMaty.HisMediStockMatyDAO>(); } }
        internal static MOS.DAO.HisSupplier.HisSupplierDAO HisSupplierDAO { get { return (MOS.DAO.HisSupplier.HisSupplierDAO)Worker.Get<MOS.DAO.HisSupplier.HisSupplierDAO>(); } }
        internal static MOS.DAO.HisMestRoom.HisMestRoomDAO HisMestRoomDAO { get { return (MOS.DAO.HisMestRoom.HisMestRoomDAO)Worker.Get<MOS.DAO.HisMestRoom.HisMestRoomDAO>(); } }
        internal static MOS.DAO.HisMediStockPeriod.HisMediStockPeriodDAO HisMediStockPeriodDAO { get { return (MOS.DAO.HisMediStockPeriod.HisMediStockPeriodDAO)Worker.Get<MOS.DAO.HisMediStockPeriod.HisMediStockPeriodDAO>(); } }
        internal static MOS.DAO.HisMestPeriodMety.HisMestPeriodMetyDAO HisMestPeriodMetyDAO { get { return (MOS.DAO.HisMestPeriodMety.HisMestPeriodMetyDAO)Worker.Get<MOS.DAO.HisMestPeriodMety.HisMestPeriodMetyDAO>(); } }
        internal static MOS.DAO.HisCareer.HisCareerDAO HisCareerDAO { get { return (MOS.DAO.HisCareer.HisCareerDAO)Worker.Get<MOS.DAO.HisCareer.HisCareerDAO>(); } }
        internal static MOS.DAO.HisExpMestTemplate.HisExpMestTemplateDAO HisExpMestTemplateDAO { get { return (MOS.DAO.HisExpMestTemplate.HisExpMestTemplateDAO)Worker.Get<MOS.DAO.HisExpMestTemplate.HisExpMestTemplateDAO>(); } }
        internal static MOS.DAO.HisEmteMedicineType.HisEmteMedicineTypeDAO HisEmteMedicineTypeDAO { get { return (MOS.DAO.HisEmteMedicineType.HisEmteMedicineTypeDAO)Worker.Get<MOS.DAO.HisEmteMedicineType.HisEmteMedicineTypeDAO>(); } }
        internal static MOS.DAO.HisImpMestMaterial.HisImpMestMaterialDAO HisImpMestMaterialDAO { get { return (MOS.DAO.HisImpMestMaterial.HisImpMestMaterialDAO)Worker.Get<MOS.DAO.HisImpMestMaterial.HisImpMestMaterialDAO>(); } }
        internal static MOS.DAO.HisExecuteRoom.HisExecuteRoomDAO HisExecuteRoomDAO { get { return (MOS.DAO.HisExecuteRoom.HisExecuteRoomDAO)Worker.Get<MOS.DAO.HisExecuteRoom.HisExecuteRoomDAO>(); } }
        internal static MOS.DAO.HisDiseaseRelation.HisDiseaseRelationDAO HisDiseaseRelationDAO { get { return (MOS.DAO.HisDiseaseRelation.HisDiseaseRelationDAO)Worker.Get<MOS.DAO.HisDiseaseRelation.HisDiseaseRelationDAO>(); } }
        internal static MOS.DAO.HisMestPeriodMaty.HisMestPeriodMatyDAO HisMestPeriodMatyDAO { get { return (MOS.DAO.HisMestPeriodMaty.HisMestPeriodMatyDAO)Worker.Get<MOS.DAO.HisMestPeriodMaty.HisMestPeriodMatyDAO>(); } }
        internal static MOS.DAO.HisExpMestMaterial.HisExpMestMaterialDAO HisExpMestMaterialDAO { get { return (MOS.DAO.HisExpMestMaterial.HisExpMestMaterialDAO)Worker.Get<MOS.DAO.HisExpMestMaterial.HisExpMestMaterialDAO>(); } }
        internal static MOS.DAO.HisMestPeriodMedi.HisMestPeriodMediDAO HisMestPeriodMediDAO { get { return (MOS.DAO.HisMestPeriodMedi.HisMestPeriodMediDAO)Worker.Get<MOS.DAO.HisMestPeriodMedi.HisMestPeriodMediDAO>(); } }
        internal static MOS.DAO.HisDeathCause.HisDeathCauseDAO HisDeathCauseDAO { get { return (MOS.DAO.HisDeathCause.HisDeathCauseDAO)Worker.Get<MOS.DAO.HisDeathCause.HisDeathCauseDAO>(); } }
        internal static MOS.DAO.HisDeathWithin.HisDeathWithinDAO HisDeathWithinDAO { get { return (MOS.DAO.HisDeathWithin.HisDeathWithinDAO)Worker.Get<MOS.DAO.HisDeathWithin.HisDeathWithinDAO>(); } }
        internal static MOS.DAO.HisRoomType.HisRoomTypeDAO HisRoomTypeDAO { get { return (MOS.DAO.HisRoomType.HisRoomTypeDAO)Worker.Get<MOS.DAO.HisRoomType.HisRoomTypeDAO>(); } }
        internal static MOS.DAO.HisServiceUnit.HisServiceUnitDAO HisServiceUnitDAO { get { return (MOS.DAO.HisServiceUnit.HisServiceUnitDAO)Worker.Get<MOS.DAO.HisServiceUnit.HisServiceUnitDAO>(); } }
        internal static MOS.DAO.HisTestIndexUnit.HisTestIndexUnitDAO HisTestIndexUnitDAO { get { return (MOS.DAO.HisTestIndexUnit.HisTestIndexUnitDAO)Worker.Get<MOS.DAO.HisTestIndexUnit.HisTestIndexUnitDAO>(); } }
        internal static MOS.DAO.HisTreatmentResult.HisTreatmentResultDAO HisTreatmentResultDAO { get { return (MOS.DAO.HisTreatmentResult.HisTreatmentResultDAO)Worker.Get<MOS.DAO.HisTreatmentResult.HisTreatmentResultDAO>(); } }
        internal static MOS.DAO.HisManufacturer.HisManufacturerDAO HisManufacturerDAO { get { return (MOS.DAO.HisManufacturer.HisManufacturerDAO)Worker.Get<MOS.DAO.HisManufacturer.HisManufacturerDAO>(); } }
        internal static MOS.DAO.HisMaterialPaty.HisMaterialPatyDAO HisMaterialPatyDAO { get { return (MOS.DAO.HisMaterialPaty.HisMaterialPatyDAO)Worker.Get<MOS.DAO.HisMaterialPaty.HisMaterialPatyDAO>(); } }
        internal static MOS.DAO.HisMedicineTypeAcin.HisMedicineTypeAcinDAO HisMedicineTypeAcinDAO { get { return (MOS.DAO.HisMedicineTypeAcin.HisMedicineTypeAcinDAO)Worker.Get<MOS.DAO.HisMedicineTypeAcin.HisMedicineTypeAcinDAO>(); } }
        internal static MOS.DAO.HisServSegr.HisServSegrDAO HisServSegrDAO { get { return (MOS.DAO.HisServSegr.HisServSegrDAO)Worker.Get<MOS.DAO.HisServSegr.HisServSegrDAO>(); } }
        internal static MOS.DAO.HisTextLib.HisTextLibDAO HisTextLibDAO { get { return (MOS.DAO.HisTextLib.HisTextLibDAO)Worker.Get<MOS.DAO.HisTextLib.HisTextLibDAO>(); } }
        internal static MOS.DAO.HisAcinInteractive.HisAcinInteractiveDAO HisAcinInteractiveDAO { get { return (MOS.DAO.HisAcinInteractive.HisAcinInteractiveDAO)Worker.Get<MOS.DAO.HisAcinInteractive.HisAcinInteractiveDAO>(); } }
        internal static MOS.DAO.HisReceptionRoom.HisReceptionRoomDAO HisReceptionRoomDAO { get { return (MOS.DAO.HisReceptionRoom.HisReceptionRoomDAO)Worker.Get<MOS.DAO.HisReceptionRoom.HisReceptionRoomDAO>(); } }
        internal static MOS.DAO.HisDataStore.HisDataStoreDAO HisDataStoreDAO { get { return (MOS.DAO.HisDataStore.HisDataStoreDAO)Worker.Get<MOS.DAO.HisDataStore.HisDataStoreDAO>(); } }
        internal static MOS.DAO.HisSereServFile.HisSereServFileDAO HisSereServFileDAO { get { return (MOS.DAO.HisSereServFile.HisSereServFileDAO)Worker.Get<MOS.DAO.HisSereServFile.HisSereServFileDAO>(); } }
        internal static MOS.DAO.HisMediReactType.HisMediReactTypeDAO HisMediReactTypeDAO { get { return (MOS.DAO.HisMediReactType.HisMediReactTypeDAO)Worker.Get<MOS.DAO.HisMediReactType.HisMediReactTypeDAO>(); } }
        internal static MOS.DAO.HisMediReact.HisMediReactDAO HisMediReactDAO { get { return (MOS.DAO.HisMediReact.HisMediReactDAO)Worker.Get<MOS.DAO.HisMediReact.HisMediReactDAO>(); } }
        internal static MOS.DAO.HisTreatment.HisTreatmentDAO HisTreatmentDAO { get { return (MOS.DAO.HisTreatment.HisTreatmentDAO)Worker.Get<MOS.DAO.HisTreatment.HisTreatmentDAO>(); } }
        internal static MOS.DAO.HisTreatmentLogType.HisTreatmentLogTypeDAO HisTreatmentLogTypeDAO { get { return (MOS.DAO.HisTreatmentLogType.HisTreatmentLogTypeDAO)Worker.Get<MOS.DAO.HisTreatmentLogType.HisTreatmentLogTypeDAO>(); } }
        internal static MOS.DAO.HisPatientTypeAlter.HisPatientTypeAlterDAO HisPatientTypeAlterDAO { get { return (MOS.DAO.HisPatientTypeAlter.HisPatientTypeAlterDAO)Worker.Get<MOS.DAO.HisPatientTypeAlter.HisPatientTypeAlterDAO>(); } }
        internal static MOS.DAO.HisDepartmentTran.HisDepartmentTranDAO HisDepartmentTranDAO { get { return (MOS.DAO.HisDepartmentTran.HisDepartmentTranDAO)Worker.Get<MOS.DAO.HisDepartmentTran.HisDepartmentTranDAO>(); } }
        internal static MOS.DAO.HisPatientTypeAllow.HisPatientTypeAllowDAO HisPatientTypeAllowDAO { get { return (MOS.DAO.HisPatientTypeAllow.HisPatientTypeAllowDAO)Worker.Get<MOS.DAO.HisPatientTypeAllow.HisPatientTypeAllowDAO>(); } }
        internal static MOS.DAO.HisSuimSetySuin.HisSuimSetySuinDAO HisSuimSetySuinDAO { get { return (MOS.DAO.HisSuimSetySuin.HisSuimSetySuinDAO)Worker.Get<MOS.DAO.HisSuimSetySuin.HisSuimSetySuinDAO>(); } }
        internal static MOS.DAO.HisSereServSuin.HisSereServSuinDAO HisSereServSuinDAO { get { return (MOS.DAO.HisSereServSuin.HisSereServSuinDAO)Worker.Get<MOS.DAO.HisSereServSuin.HisSereServSuinDAO>(); } }
        internal static MOS.DAO.HisTreatmentEndType.HisTreatmentEndTypeDAO HisTreatmentEndTypeDAO { get { return (MOS.DAO.HisTreatmentEndType.HisTreatmentEndTypeDAO)Worker.Get<MOS.DAO.HisTreatmentEndType.HisTreatmentEndTypeDAO>(); } }
        internal static MOS.DAO.HisBlood.HisBloodDAO HisBloodDAO { get { return (MOS.DAO.HisBlood.HisBloodDAO)Worker.Get<MOS.DAO.HisBlood.HisBloodDAO>(); } }
        internal static MOS.DAO.HisBloodRh.HisBloodRhDAO HisBloodRhDAO { get { return (MOS.DAO.HisBloodRh.HisBloodRhDAO)Worker.Get<MOS.DAO.HisBloodRh.HisBloodRhDAO>(); } }
        internal static MOS.DAO.HisEmotionlessMethod.HisEmotionlessMethodDAO HisEmotionlessMethodDAO { get { return (MOS.DAO.HisEmotionlessMethod.HisEmotionlessMethodDAO)Worker.Get<MOS.DAO.HisEmotionlessMethod.HisEmotionlessMethodDAO>(); } }
        internal static MOS.DAO.HisPtttCatastrophe.HisPtttCatastropheDAO HisPtttCatastropheDAO { get { return (MOS.DAO.HisPtttCatastrophe.HisPtttCatastropheDAO)Worker.Get<MOS.DAO.HisPtttCatastrophe.HisPtttCatastropheDAO>(); } }
        internal static MOS.DAO.HisPtttCondition.HisPtttConditionDAO HisPtttConditionDAO { get { return (MOS.DAO.HisPtttCondition.HisPtttConditionDAO)Worker.Get<MOS.DAO.HisPtttCondition.HisPtttConditionDAO>(); } }
        internal static MOS.DAO.HisPtttGroup.HisPtttGroupDAO HisPtttGroupDAO { get { return (MOS.DAO.HisPtttGroup.HisPtttGroupDAO)Worker.Get<MOS.DAO.HisPtttGroup.HisPtttGroupDAO>(); } }
        internal static MOS.DAO.HisPtttMethod.HisPtttMethodDAO HisPtttMethodDAO { get { return (MOS.DAO.HisPtttMethod.HisPtttMethodDAO)Worker.Get<MOS.DAO.HisPtttMethod.HisPtttMethodDAO>(); } }
        internal static MOS.DAO.HisSereServPttt.HisSereServPtttDAO HisSereServPtttDAO { get { return (MOS.DAO.HisSereServPttt.HisSereServPtttDAO)Worker.Get<MOS.DAO.HisSereServPttt.HisSereServPtttDAO>(); } }
        internal static MOS.DAO.HisCare.HisCareDAO HisCareDAO { get { return (MOS.DAO.HisCare.HisCareDAO)Worker.Get<MOS.DAO.HisCare.HisCareDAO>(); } }
        internal static MOS.DAO.HisMaterialBean.HisMaterialBeanDAO HisMaterialBeanDAO { get { return (MOS.DAO.HisMaterialBean.HisMaterialBeanDAO)Worker.Get<MOS.DAO.HisMaterialBean.HisMaterialBeanDAO>(); } }
        internal static MOS.DAO.HisInfusion.HisInfusionDAO HisInfusionDAO { get { return (MOS.DAO.HisInfusion.HisInfusionDAO)Worker.Get<MOS.DAO.HisInfusion.HisInfusionDAO>(); } }
        internal static MOS.DAO.HisExamSereDire.HisExamSereDireDAO HisExamSereDireDAO { get { return (MOS.DAO.HisExamSereDire.HisExamSereDireDAO)Worker.Get<MOS.DAO.HisExamSereDire.HisExamSereDireDAO>(); } }
        internal static MOS.DAO.HisHeinApproval.HisHeinApprovalDAO HisHeinApprovalDAO { get { return (MOS.DAO.HisHeinApproval.HisHeinApprovalDAO)Worker.Get<MOS.DAO.HisHeinApproval.HisHeinApprovalDAO>(); } }
        internal static MOS.DAO.HisMestPeriodMate.HisMestPeriodMateDAO HisMestPeriodMateDAO { get { return (MOS.DAO.HisMestPeriodMate.HisMestPeriodMateDAO)Worker.Get<MOS.DAO.HisMestPeriodMate.HisMestPeriodMateDAO>(); } }
        internal static MOS.DAO.HisServiceReqType.HisServiceReqTypeDAO HisServiceReqTypeDAO { get { return (MOS.DAO.HisServiceReqType.HisServiceReqTypeDAO)Worker.Get<MOS.DAO.HisServiceReqType.HisServiceReqTypeDAO>(); } }
        internal static MOS.DAO.HisHeinServiceType.HisHeinServiceTypeDAO HisHeinServiceTypeDAO { get { return (MOS.DAO.HisHeinServiceType.HisHeinServiceTypeDAO)Worker.Get<MOS.DAO.HisHeinServiceType.HisHeinServiceTypeDAO>(); } }
        internal static MOS.DAO.HisMestPatientType.HisMestPatientTypeDAO HisMestPatientTypeDAO { get { return (MOS.DAO.HisMestPatientType.HisMestPatientTypeDAO)Worker.Get<MOS.DAO.HisMestPatientType.HisMestPatientTypeDAO>(); } }
        internal static MOS.DAO.HisEmteMaterialType.HisEmteMaterialTypeDAO HisEmteMaterialTypeDAO { get { return (MOS.DAO.HisEmteMaterialType.HisEmteMaterialTypeDAO)Worker.Get<MOS.DAO.HisEmteMaterialType.HisEmteMaterialTypeDAO>(); } }
        internal static MOS.DAO.HisAccidentHurt.HisAccidentHurtDAO HisAccidentHurtDAO { get { return (MOS.DAO.HisAccidentHurt.HisAccidentHurtDAO)Worker.Get<MOS.DAO.HisAccidentHurt.HisAccidentHurtDAO>(); } }
        internal static MOS.DAO.HisTreatmentType.HisTreatmentTypeDAO HisTreatmentTypeDAO { get { return (MOS.DAO.HisTreatmentType.HisTreatmentTypeDAO)Worker.Get<MOS.DAO.HisTreatmentType.HisTreatmentTypeDAO>(); } }
        internal static MOS.DAO.HisTreatmentBedRoom.HisTreatmentBedRoomDAO HisTreatmentBedRoomDAO { get { return (MOS.DAO.HisTreatmentBedRoom.HisTreatmentBedRoomDAO)Worker.Get<MOS.DAO.HisTreatmentBedRoom.HisTreatmentBedRoomDAO>(); } }
        internal static MOS.DAO.HisKskContract.HisKskContractDAO HisKskContractDAO { get { return (MOS.DAO.HisKskContract.HisKskContractDAO)Worker.Get<MOS.DAO.HisKskContract.HisKskContractDAO>(); } }
        internal static MOS.DAO.HisSuimIndexUnit.HisSuimIndexUnitDAO HisSuimIndexUnitDAO { get { return (MOS.DAO.HisSuimIndexUnit.HisSuimIndexUnitDAO)Worker.Get<MOS.DAO.HisSuimIndexUnit.HisSuimIndexUnitDAO>(); } }
        internal static MOS.DAO.HisSuimIndex.HisSuimIndexDAO HisSuimIndexDAO { get { return (MOS.DAO.HisSuimIndex.HisSuimIndexDAO)Worker.Get<MOS.DAO.HisSuimIndex.HisSuimIndexDAO>(); } }
        internal static MOS.DAO.HisMedicineLine.HisMedicineLineDAO HisMedicineLineDAO { get { return (MOS.DAO.HisMedicineLine.HisMedicineLineDAO)Worker.Get<MOS.DAO.HisMedicineLine.HisMedicineLineDAO>(); } }
        internal static MOS.DAO.HisTracking.HisTrackingDAO HisTrackingDAO { get { return (MOS.DAO.HisTracking.HisTrackingDAO)Worker.Get<MOS.DAO.HisTracking.HisTrackingDAO>(); } }
        internal static MOS.DAO.HisDebate.HisDebateDAO HisDebateDAO { get { return (MOS.DAO.HisDebate.HisDebateDAO)Worker.Get<MOS.DAO.HisDebate.HisDebateDAO>(); } }
        internal static MOS.DAO.HisDebateUser.HisDebateUserDAO HisDebateUserDAO { get { return (MOS.DAO.HisDebateUser.HisDebateUserDAO)Worker.Get<MOS.DAO.HisDebateUser.HisDebateUserDAO>(); } }
        internal static MOS.DAO.HisAwareness.HisAwarenessDAO HisAwarenessDAO { get { return (MOS.DAO.HisAwareness.HisAwarenessDAO)Worker.Get<MOS.DAO.HisAwareness.HisAwarenessDAO>(); } }
        internal static MOS.DAO.HisCareType.HisCareTypeDAO HisCareTypeDAO { get { return (MOS.DAO.HisCareType.HisCareTypeDAO)Worker.Get<MOS.DAO.HisCareType.HisCareTypeDAO>(); } }
        internal static MOS.DAO.HisPackingType.HisPackingTypeDAO HisPackingTypeDAO { get { return (MOS.DAO.HisPackingType.HisPackingTypeDAO)Worker.Get<MOS.DAO.HisPackingType.HisPackingTypeDAO>(); } }
        internal static MOS.DAO.HisCareDetail.HisCareDetailDAO HisCareDetailDAO { get { return (MOS.DAO.HisCareDetail.HisCareDetailDAO)Worker.Get<MOS.DAO.HisCareDetail.HisCareDetailDAO>(); } }
        internal static MOS.DAO.HisAnticipate.HisAnticipateDAO HisAnticipateDAO { get { return (MOS.DAO.HisAnticipate.HisAnticipateDAO)Worker.Get<MOS.DAO.HisAnticipate.HisAnticipateDAO>(); } }
        internal static MOS.DAO.HisAnticipateMaty.HisAnticipateMatyDAO HisAnticipateMatyDAO { get { return (MOS.DAO.HisAnticipateMaty.HisAnticipateMatyDAO)Worker.Get<MOS.DAO.HisAnticipateMaty.HisAnticipateMatyDAO>(); } }
        internal static MOS.DAO.HisAnticipateMety.HisAnticipateMetyDAO HisAnticipateMetyDAO { get { return (MOS.DAO.HisAnticipateMety.HisAnticipateMetyDAO)Worker.Get<MOS.DAO.HisAnticipateMety.HisAnticipateMetyDAO>(); } }
        internal static MOS.DAO.HisServiceMaty.HisServiceMatyDAO HisServiceMatyDAO { get { return (MOS.DAO.HisServiceMaty.HisServiceMatyDAO)Worker.Get<MOS.DAO.HisServiceMaty.HisServiceMatyDAO>(); } }
        internal static MOS.DAO.HisServiceMety.HisServiceMetyDAO HisServiceMetyDAO { get { return (MOS.DAO.HisServiceMety.HisServiceMetyDAO)Worker.Get<MOS.DAO.HisServiceMety.HisServiceMetyDAO>(); } }
        internal static MOS.DAO.HisSereServReha.HisSereServRehaDAO HisSereServRehaDAO { get { return (MOS.DAO.HisSereServReha.HisSereServRehaDAO)Worker.Get<MOS.DAO.HisSereServReha.HisSereServRehaDAO>(); } }
        internal static MOS.DAO.HisRehaTrainUnit.HisRehaTrainUnitDAO HisRehaTrainUnitDAO { get { return (MOS.DAO.HisRehaTrainUnit.HisRehaTrainUnitDAO)Worker.Get<MOS.DAO.HisRehaTrainUnit.HisRehaTrainUnitDAO>(); } }
        internal static MOS.DAO.HisRehaSum.HisRehaSumDAO HisRehaSumDAO { get { return (MOS.DAO.HisRehaSum.HisRehaSumDAO)Worker.Get<MOS.DAO.HisRehaSum.HisRehaSumDAO>(); } }
        internal static MOS.DAO.HisCareSum.HisCareSumDAO HisCareSumDAO { get { return (MOS.DAO.HisCareSum.HisCareSumDAO)Worker.Get<MOS.DAO.HisCareSum.HisCareSumDAO>(); } }
        internal static MOS.DAO.HisInfusionSum.HisInfusionSumDAO HisInfusionSumDAO { get { return (MOS.DAO.HisInfusionSum.HisInfusionSumDAO)Worker.Get<MOS.DAO.HisInfusionSum.HisInfusionSumDAO>(); } }
        internal static MOS.DAO.HisInvoiceBook.HisInvoiceBookDAO HisInvoiceBookDAO { get { return (MOS.DAO.HisInvoiceBook.HisInvoiceBookDAO)Worker.Get<MOS.DAO.HisInvoiceBook.HisInvoiceBookDAO>(); } }
        internal static MOS.DAO.HisInvoice.HisInvoiceDAO HisInvoiceDAO { get { return (MOS.DAO.HisInvoice.HisInvoiceDAO)Worker.Get<MOS.DAO.HisInvoice.HisInvoiceDAO>(); } }
        internal static MOS.DAO.HisUserInvoiceBook.HisUserInvoiceBookDAO HisUserInvoiceBookDAO { get { return (MOS.DAO.HisUserInvoiceBook.HisUserInvoiceBookDAO)Worker.Get<MOS.DAO.HisUserInvoiceBook.HisUserInvoiceBookDAO>(); } }
        internal static MOS.DAO.HisInvoiceDetail.HisInvoiceDetailDAO HisInvoiceDetailDAO { get { return (MOS.DAO.HisInvoiceDetail.HisInvoiceDetailDAO)Worker.Get<MOS.DAO.HisInvoiceDetail.HisInvoiceDetailDAO>(); } }
        internal static MOS.DAO.HisRehaTrainType.HisRehaTrainTypeDAO HisRehaTrainTypeDAO { get { return (MOS.DAO.HisRehaTrainType.HisRehaTrainTypeDAO)Worker.Get<MOS.DAO.HisRehaTrainType.HisRehaTrainTypeDAO>(); } }
        internal static MOS.DAO.HisRestRetrType.HisRestRetrTypeDAO HisRestRetrTypeDAO { get { return (MOS.DAO.HisRestRetrType.HisRestRetrTypeDAO)Worker.Get<MOS.DAO.HisRestRetrType.HisRestRetrTypeDAO>(); } }
        internal static MOS.DAO.HisRehaTrain.HisRehaTrainDAO HisRehaTrainDAO { get { return (MOS.DAO.HisRehaTrain.HisRehaTrainDAO)Worker.Get<MOS.DAO.HisRehaTrain.HisRehaTrainDAO>(); } }
        internal static MOS.DAO.HisMilitaryRank.HisMilitaryRankDAO HisMilitaryRankDAO { get { return (MOS.DAO.HisMilitaryRank.HisMilitaryRankDAO)Worker.Get<MOS.DAO.HisMilitaryRank.HisMilitaryRankDAO>(); } }
        internal static MOS.DAO.HisWorkPlace.HisWorkPlaceDAO HisWorkPlaceDAO { get { return (MOS.DAO.HisWorkPlace.HisWorkPlaceDAO)Worker.Get<MOS.DAO.HisWorkPlace.HisWorkPlaceDAO>(); } }
        internal static MOS.DAO.HisReportTypeCat.HisReportTypeCatDAO HisReportTypeCatDAO { get { return (MOS.DAO.HisReportTypeCat.HisReportTypeCatDAO)Worker.Get<MOS.DAO.HisReportTypeCat.HisReportTypeCatDAO>(); } }
        internal static MOS.DAO.HisServiceRetyCat.HisServiceRetyCatDAO HisServiceRetyCatDAO { get { return (MOS.DAO.HisServiceRetyCat.HisServiceRetyCatDAO)Worker.Get<MOS.DAO.HisServiceRetyCat.HisServiceRetyCatDAO>(); } }
        internal static MOS.DAO.HisEmergencyWtime.HisEmergencyWtimeDAO HisEmergencyWtimeDAO { get { return (MOS.DAO.HisEmergencyWtime.HisEmergencyWtimeDAO)Worker.Get<MOS.DAO.HisEmergencyWtime.HisEmergencyWtimeDAO>(); } }
        internal static MOS.DAO.HisIcdGroup.HisIcdGroupDAO HisIcdGroupDAO { get { return (MOS.DAO.HisIcdGroup.HisIcdGroupDAO)Worker.Get<MOS.DAO.HisIcdGroup.HisIcdGroupDAO>(); } }
        internal static MOS.DAO.HisSampleRoom.HisSampleRoomDAO HisSampleRoomDAO { get { return (MOS.DAO.HisSampleRoom.HisSampleRoomDAO)Worker.Get<MOS.DAO.HisSampleRoom.HisSampleRoomDAO>(); } }
        internal static MOS.DAO.HisExecuteGroup.HisExecuteGroupDAO HisExecuteGroupDAO { get { return (MOS.DAO.HisExecuteGroup.HisExecuteGroupDAO)Worker.Get<MOS.DAO.HisExecuteGroup.HisExecuteGroupDAO>(); } }
        internal static MOS.DAO.HisAccidentHurtType.HisAccidentHurtTypeDAO HisAccidentHurtTypeDAO { get { return (MOS.DAO.HisAccidentHurtType.HisAccidentHurtTypeDAO)Worker.Get<MOS.DAO.HisAccidentHurtType.HisAccidentHurtTypeDAO>(); } }
        internal static MOS.DAO.HisSaroExro.HisSaroExroDAO HisSaroExroDAO { get { return (MOS.DAO.HisSaroExro.HisSaroExroDAO)Worker.Get<MOS.DAO.HisSaroExro.HisSaroExroDAO>(); } }
        internal static MOS.DAO.HisAccidentBodyPart.HisAccidentBodyPartDAO HisAccidentBodyPartDAO { get { return (MOS.DAO.HisAccidentBodyPart.HisAccidentBodyPartDAO)Worker.Get<MOS.DAO.HisAccidentBodyPart.HisAccidentBodyPartDAO>(); } }
        internal static MOS.DAO.HisAccidentCare.HisAccidentCareDAO HisAccidentCareDAO { get { return (MOS.DAO.HisAccidentCare.HisAccidentCareDAO)Worker.Get<MOS.DAO.HisAccidentCare.HisAccidentCareDAO>(); } }
        internal static MOS.DAO.HisAccidentHelmet.HisAccidentHelmetDAO HisAccidentHelmetDAO { get { return (MOS.DAO.HisAccidentHelmet.HisAccidentHelmetDAO)Worker.Get<MOS.DAO.HisAccidentHelmet.HisAccidentHelmetDAO>(); } }
        internal static MOS.DAO.HisAccidentLocation.HisAccidentLocationDAO HisAccidentLocationDAO { get { return (MOS.DAO.HisAccidentLocation.HisAccidentLocationDAO)Worker.Get<MOS.DAO.HisAccidentLocation.HisAccidentLocationDAO>(); } }
        internal static MOS.DAO.HisAccidentPoison.HisAccidentPoisonDAO HisAccidentPoisonDAO { get { return (MOS.DAO.HisAccidentPoison.HisAccidentPoisonDAO)Worker.Get<MOS.DAO.HisAccidentPoison.HisAccidentPoisonDAO>(); } }
        internal static MOS.DAO.HisAccidentResult.HisAccidentResultDAO HisAccidentResultDAO { get { return (MOS.DAO.HisAccidentResult.HisAccidentResultDAO)Worker.Get<MOS.DAO.HisAccidentResult.HisAccidentResultDAO>(); } }
        internal static MOS.DAO.HisAccidentVehicle.HisAccidentVehicleDAO HisAccidentVehicleDAO { get { return (MOS.DAO.HisAccidentVehicle.HisAccidentVehicleDAO)Worker.Get<MOS.DAO.HisAccidentVehicle.HisAccidentVehicleDAO>(); } }
        internal static MOS.DAO.HisBid.HisBidDAO HisBidDAO { get { return (MOS.DAO.HisBid.HisBidDAO)Worker.Get<MOS.DAO.HisBid.HisBidDAO>(); } }
        internal static MOS.DAO.HisBidMaterialType.HisBidMaterialTypeDAO HisBidMaterialTypeDAO { get { return (MOS.DAO.HisBidMaterialType.HisBidMaterialTypeDAO)Worker.Get<MOS.DAO.HisBidMaterialType.HisBidMaterialTypeDAO>(); } }
        internal static MOS.DAO.HisBidMedicineType.HisBidMedicineTypeDAO HisBidMedicineTypeDAO { get { return (MOS.DAO.HisBidMedicineType.HisBidMedicineTypeDAO)Worker.Get<MOS.DAO.HisBidMedicineType.HisBidMedicineTypeDAO>(); } }
        internal static MOS.DAO.HisInvoicePrint.HisInvoicePrintDAO HisInvoicePrintDAO { get { return (MOS.DAO.HisInvoicePrint.HisInvoicePrintDAO)Worker.Get<MOS.DAO.HisInvoicePrint.HisInvoicePrintDAO>(); } }
        internal static MOS.DAO.HisMestPatySub.HisMestPatySubDAO HisMestPatySubDAO { get { return (MOS.DAO.HisMestPatySub.HisMestPatySubDAO)Worker.Get<MOS.DAO.HisMestPatySub.HisMestPatySubDAO>(); } }
        internal static MOS.DAO.HisPatientTypeSub.HisPatientTypeSubDAO HisPatientTypeSubDAO { get { return (MOS.DAO.HisPatientTypeSub.HisPatientTypeSubDAO)Worker.Get<MOS.DAO.HisPatientTypeSub.HisPatientTypeSubDAO>(); } }
        internal static MOS.DAO.HisPatientProgram.HisPatientProgramDAO HisPatientProgramDAO { get { return (MOS.DAO.HisPatientProgram.HisPatientProgramDAO)Worker.Get<MOS.DAO.HisPatientProgram.HisPatientProgramDAO>(); } }
        internal static MOS.DAO.HisProgram.HisProgramDAO HisProgramDAO { get { return (MOS.DAO.HisProgram.HisProgramDAO)Worker.Get<MOS.DAO.HisProgram.HisProgramDAO>(); } }
        internal static MOS.DAO.HisDepositReq.HisDepositReqDAO HisDepositReqDAO { get { return (MOS.DAO.HisDepositReq.HisDepositReqDAO)Worker.Get<MOS.DAO.HisDepositReq.HisDepositReqDAO>(); } }
        internal static MOS.DAO.HisBillFund.HisBillFundDAO HisBillFundDAO { get { return (MOS.DAO.HisBillFund.HisBillFundDAO)Worker.Get<MOS.DAO.HisBillFund.HisBillFundDAO>(); } }
        internal static MOS.DAO.HisBranch.HisBranchDAO HisBranchDAO { get { return (MOS.DAO.HisBranch.HisBranchDAO)Worker.Get<MOS.DAO.HisBranch.HisBranchDAO>(); } }
        internal static MOS.DAO.HisFund.HisFundDAO HisFundDAO { get { return (MOS.DAO.HisFund.HisFundDAO)Worker.Get<MOS.DAO.HisFund.HisFundDAO>(); } }
        internal static MOS.DAO.HisExecuteRole.HisExecuteRoleDAO HisExecuteRoleDAO { get { return (MOS.DAO.HisExecuteRole.HisExecuteRoleDAO)Worker.Get<MOS.DAO.HisExecuteRole.HisExecuteRoleDAO>(); } }
        internal static MOS.DAO.HisCashierRoom.HisCashierRoomDAO HisCashierRoomDAO { get { return (MOS.DAO.HisCashierRoom.HisCashierRoomDAO)Worker.Get<MOS.DAO.HisCashierRoom.HisCashierRoomDAO>(); } }
        internal static MOS.DAO.HisCaroDepartment.HisCaroDepartmentDAO HisCaroDepartmentDAO { get { return (MOS.DAO.HisCaroDepartment.HisCaroDepartmentDAO)Worker.Get<MOS.DAO.HisCaroDepartment.HisCaroDepartmentDAO>(); } }
        internal static MOS.DAO.HisBed.HisBedDAO HisBedDAO { get { return (MOS.DAO.HisBed.HisBedDAO)Worker.Get<MOS.DAO.HisBed.HisBedDAO>(); } }
        internal static MOS.DAO.HisBedLog.HisBedLogDAO HisBedLogDAO { get { return (MOS.DAO.HisBedLog.HisBedLogDAO)Worker.Get<MOS.DAO.HisBedLog.HisBedLogDAO>(); } }
        internal static MOS.DAO.HisBedType.HisBedTypeDAO HisBedTypeDAO { get { return (MOS.DAO.HisBedType.HisBedTypeDAO)Worker.Get<MOS.DAO.HisBedType.HisBedTypeDAO>(); } }
        internal static MOS.DAO.HisEkip.HisEkipDAO HisEkipDAO { get { return (MOS.DAO.HisEkip.HisEkipDAO)Worker.Get<MOS.DAO.HisEkip.HisEkipDAO>(); } }
        internal static MOS.DAO.HisEkipUser.HisEkipUserDAO HisEkipUserDAO { get { return (MOS.DAO.HisEkipUser.HisEkipUserDAO)Worker.Get<MOS.DAO.HisEkipUser.HisEkipUserDAO>(); } }
        internal static MOS.DAO.HisBloodAbo.HisBloodAboDAO HisBloodAboDAO { get { return (MOS.DAO.HisBloodAbo.HisBloodAboDAO)Worker.Get<MOS.DAO.HisBloodAbo.HisBloodAboDAO>(); } }
        internal static MOS.DAO.HisServiceFollow.HisServiceFollowDAO HisServiceFollowDAO { get { return (MOS.DAO.HisServiceFollow.HisServiceFollowDAO)Worker.Get<MOS.DAO.HisServiceFollow.HisServiceFollowDAO>(); } }
        internal static MOS.DAO.HisBedBsty.HisBedBstyDAO HisBedBstyDAO { get { return (MOS.DAO.HisBedBsty.HisBedBstyDAO)Worker.Get<MOS.DAO.HisBedBsty.HisBedBstyDAO>(); } }
        internal static MOS.DAO.HisBloodType.HisBloodTypeDAO HisBloodTypeDAO { get { return (MOS.DAO.HisBloodType.HisBloodTypeDAO)Worker.Get<MOS.DAO.HisBloodType.HisBloodTypeDAO>(); } }
        internal static MOS.DAO.HisBloodVolume.HisBloodVolumeDAO HisBloodVolumeDAO { get { return (MOS.DAO.HisBloodVolume.HisBloodVolumeDAO)Worker.Get<MOS.DAO.HisBloodVolume.HisBloodVolumeDAO>(); } }
        internal static MOS.DAO.HisBloodGroup.HisBloodGroupDAO HisBloodGroupDAO { get { return (MOS.DAO.HisBloodGroup.HisBloodGroupDAO)Worker.Get<MOS.DAO.HisBloodGroup.HisBloodGroupDAO>(); } }
        internal static MOS.DAO.HisExpMestBlood.HisExpMestBloodDAO HisExpMestBloodDAO { get { return (MOS.DAO.HisExpMestBlood.HisExpMestBloodDAO)Worker.Get<MOS.DAO.HisExpMestBlood.HisExpMestBloodDAO>(); } }
        internal static MOS.DAO.HisImpSource.HisImpSourceDAO HisImpSourceDAO { get { return (MOS.DAO.HisImpSource.HisImpSourceDAO)Worker.Get<MOS.DAO.HisImpSource.HisImpSourceDAO>(); } }
        internal static MOS.DAO.HisImpMestBlood.HisImpMestBloodDAO HisImpMestBloodDAO { get { return (MOS.DAO.HisImpMestBlood.HisImpMestBloodDAO)Worker.Get<MOS.DAO.HisImpMestBlood.HisImpMestBloodDAO>(); } }
        internal static MOS.DAO.HisMestPeriodBlty.HisMestPeriodBltyDAO HisMestPeriodBltyDAO { get { return (MOS.DAO.HisMestPeriodBlty.HisMestPeriodBltyDAO)Worker.Get<MOS.DAO.HisMestPeriodBlty.HisMestPeriodBltyDAO>(); } }
        internal static MOS.DAO.HisMestPeriodBlood.HisMestPeriodBloodDAO HisMestPeriodBloodDAO { get { return (MOS.DAO.HisMestPeriodBlood.HisMestPeriodBloodDAO)Worker.Get<MOS.DAO.HisMestPeriodBlood.HisMestPeriodBloodDAO>(); } }
        internal static MOS.DAO.HisRoomTypeModule.HisRoomTypeModuleDAO HisRoomTypeModuleDAO { get { return (MOS.DAO.HisRoomTypeModule.HisRoomTypeModuleDAO)Worker.Get<MOS.DAO.HisRoomTypeModule.HisRoomTypeModuleDAO>(); } }
        internal static MOS.DAO.HisAnticipateBlty.HisAnticipateBltyDAO HisAnticipateBltyDAO { get { return (MOS.DAO.HisAnticipateBlty.HisAnticipateBltyDAO)Worker.Get<MOS.DAO.HisAnticipateBlty.HisAnticipateBltyDAO>(); } }
        internal static MOS.DAO.HisBidBloodType.HisBidBloodTypeDAO HisBidBloodTypeDAO { get { return (MOS.DAO.HisBidBloodType.HisBidBloodTypeDAO)Worker.Get<MOS.DAO.HisBidBloodType.HisBidBloodTypeDAO>(); } }
        internal static MOS.DAO.HisRegisterGate.HisRegisterGateDAO HisRegisterGateDAO { get { return (MOS.DAO.HisRegisterGate.HisRegisterGateDAO)Worker.Get<MOS.DAO.HisRegisterGate.HisRegisterGateDAO>(); } }
        internal static MOS.DAO.HisRegisterReq.HisRegisterReqDAO HisRegisterReqDAO { get { return (MOS.DAO.HisRegisterReq.HisRegisterReqDAO)Worker.Get<MOS.DAO.HisRegisterReq.HisRegisterReqDAO>(); } }
        internal static MOS.DAO.HisSereServTemp.HisSereServTempDAO HisSereServTempDAO { get { return (MOS.DAO.HisSereServTemp.HisSereServTempDAO)Worker.Get<MOS.DAO.HisSereServTemp.HisSereServTempDAO>(); } }
        internal static MOS.DAO.HisBaby.HisBabyDAO HisBabyDAO { get { return (MOS.DAO.HisBaby.HisBabyDAO)Worker.Get<MOS.DAO.HisBaby.HisBabyDAO>(); } }
        internal static MOS.DAO.HisBornType.HisBornTypeDAO HisBornTypeDAO { get { return (MOS.DAO.HisBornType.HisBornTypeDAO)Worker.Get<MOS.DAO.HisBornType.HisBornTypeDAO>(); } }
        internal static MOS.DAO.HisBornPosition.HisBornPositionDAO HisBornPositionDAO { get { return (MOS.DAO.HisBornPosition.HisBornPositionDAO)Worker.Get<MOS.DAO.HisBornPosition.HisBornPositionDAO>(); } }
        internal static MOS.DAO.HisBornResult.HisBornResultDAO HisBornResultDAO { get { return (MOS.DAO.HisBornResult.HisBornResultDAO)Worker.Get<MOS.DAO.HisBornResult.HisBornResultDAO>(); } }
        internal static MOS.DAO.HisSereServExt.HisSereServExtDAO HisSereServExtDAO { get { return (MOS.DAO.HisSereServExt.HisSereServExtDAO)Worker.Get<MOS.DAO.HisSereServExt.HisSereServExtDAO>(); } }
        internal static MOS.DAO.HisExamServiceTemp.HisExamServiceTempDAO HisExamServiceTempDAO { get { return (MOS.DAO.HisExamServiceTemp.HisExamServiceTempDAO)Worker.Get<MOS.DAO.HisExamServiceTemp.HisExamServiceTempDAO>(); } }
        internal static MOS.DAO.HisHtu.HisHtuDAO HisHtuDAO { get { return (MOS.DAO.HisHtu.HisHtuDAO)Worker.Get<MOS.DAO.HisHtu.HisHtuDAO>(); } }
        internal static MOS.DAO.HisMediReactSum.HisMediReactSumDAO HisMediReactSumDAO { get { return (MOS.DAO.HisMediReactSum.HisMediReactSumDAO)Worker.Get<MOS.DAO.HisMediReactSum.HisMediReactSumDAO>(); } }
        internal static MOS.DAO.HisBhytWhitelist.HisBhytWhitelistDAO HisBhytWhitelistDAO { get { return (MOS.DAO.HisBhytWhitelist.HisBhytWhitelistDAO)Worker.Get<MOS.DAO.HisBhytWhitelist.HisBhytWhitelistDAO>(); } }
        internal static MOS.DAO.HisBhytBlacklist.HisBhytBlacklistDAO HisBhytBlacklistDAO { get { return (MOS.DAO.HisBhytBlacklist.HisBhytBlacklistDAO)Worker.Get<MOS.DAO.HisBhytBlacklist.HisBhytBlacklistDAO>(); } }
        internal static MOS.DAO.HisImpMestTypeUser.HisImpMestTypeUserDAO HisImpMestTypeUserDAO { get { return (MOS.DAO.HisImpMestTypeUser.HisImpMestTypeUserDAO)Worker.Get<MOS.DAO.HisImpMestTypeUser.HisImpMestTypeUserDAO>(); } }
        internal static MOS.DAO.HisExecuteRoleUser.HisExecuteRoleUserDAO HisExecuteRoleUserDAO { get { return (MOS.DAO.HisExecuteRoleUser.HisExecuteRoleUserDAO)Worker.Get<MOS.DAO.HisExecuteRoleUser.HisExecuteRoleUserDAO>(); } }
        internal static MOS.DAO.HisMestMetyDepa.HisMestMetyDepaDAO HisMestMetyDepaDAO { get { return (MOS.DAO.HisMestMetyDepa.HisMestMetyDepaDAO)Worker.Get<MOS.DAO.HisMestMetyDepa.HisMestMetyDepaDAO>(); } }
        internal static MOS.DAO.HisServiceReqMaty.HisServiceReqMatyDAO HisServiceReqMatyDAO { get { return (MOS.DAO.HisServiceReqMaty.HisServiceReqMatyDAO)Worker.Get<MOS.DAO.HisServiceReqMaty.HisServiceReqMatyDAO>(); } }
        internal static MOS.DAO.HisPaanLiquid.HisPaanLiquidDAO HisPaanLiquidDAO { get { return (MOS.DAO.HisPaanLiquid.HisPaanLiquidDAO)Worker.Get<MOS.DAO.HisPaanLiquid.HisPaanLiquidDAO>(); } }
        internal static MOS.DAO.HisPaanPosition.HisPaanPositionDAO HisPaanPositionDAO { get { return (MOS.DAO.HisPaanPosition.HisPaanPositionDAO)Worker.Get<MOS.DAO.HisPaanPosition.HisPaanPositionDAO>(); } }
        internal static MOS.DAO.HisIcdCm.HisIcdCmDAO HisIcdCmDAO { get { return (MOS.DAO.HisIcdCm.HisIcdCmDAO)Worker.Get<MOS.DAO.HisIcdCm.HisIcdCmDAO>(); } }
        internal static MOS.DAO.HisMedicineTypeTut.HisMedicineTypeTutDAO HisMedicineTypeTutDAO { get { return (MOS.DAO.HisMedicineTypeTut.HisMedicineTypeTutDAO)Worker.Get<MOS.DAO.HisMedicineTypeTut.HisMedicineTypeTutDAO>(); } }
        internal static MOS.DAO.HisBidType.HisBidTypeDAO HisBidTypeDAO { get { return (MOS.DAO.HisBidType.HisBidTypeDAO)Worker.Get<MOS.DAO.HisBidType.HisBidTypeDAO>(); } }
        internal static MOS.DAO.HisExpMestReason.HisExpMestReasonDAO HisExpMestReasonDAO { get { return (MOS.DAO.HisExpMestReason.HisExpMestReasonDAO)Worker.Get<MOS.DAO.HisExpMestReason.HisExpMestReasonDAO>(); } }
        internal static MOS.DAO.HisRemuneration.HisRemunerationDAO HisRemunerationDAO { get { return (MOS.DAO.HisRemuneration.HisRemunerationDAO)Worker.Get<MOS.DAO.HisRemuneration.HisRemunerationDAO>(); } }
        internal static MOS.DAO.HisOweType.HisOweTypeDAO HisOweTypeDAO { get { return (MOS.DAO.HisOweType.HisOweTypeDAO)Worker.Get<MOS.DAO.HisOweType.HisOweTypeDAO>(); } }
        internal static MOS.DAO.HisCashout.HisCashoutDAO HisCashoutDAO { get { return (MOS.DAO.HisCashout.HisCashoutDAO)Worker.Get<MOS.DAO.HisCashout.HisCashoutDAO>(); } }
        internal static MOS.DAO.HisSereServBill.HisSereServBillDAO HisSereServBillDAO { get { return (MOS.DAO.HisSereServBill.HisSereServBillDAO)Worker.Get<MOS.DAO.HisSereServBill.HisSereServBillDAO>(); } }
        internal static MOS.DAO.HisEmployee.HisEmployeeDAO HisEmployeeDAO { get { return (MOS.DAO.HisEmployee.HisEmployeeDAO)Worker.Get<MOS.DAO.HisEmployee.HisEmployeeDAO>(); } }
        internal static MOS.DAO.HisImpMestUser.HisImpMestUserDAO HisImpMestUserDAO { get { return (MOS.DAO.HisImpMestUser.HisImpMestUserDAO)Worker.Get<MOS.DAO.HisImpMestUser.HisImpMestUserDAO>(); } }
        internal static MOS.DAO.HisMestInveUser.HisMestInveUserDAO HisMestInveUserDAO { get { return (MOS.DAO.HisMestInveUser.HisMestInveUserDAO)Worker.Get<MOS.DAO.HisMestInveUser.HisMestInveUserDAO>(); } }
        internal static MOS.DAO.HisMestInventory.HisMestInventoryDAO HisMestInventoryDAO { get { return (MOS.DAO.HisMestInventory.HisMestInventoryDAO)Worker.Get<MOS.DAO.HisMestInventory.HisMestInventoryDAO>(); } }
        internal static MOS.DAO.HisBillGoods.HisBillGoodsDAO HisBillGoodsDAO { get { return (MOS.DAO.HisBillGoods.HisBillGoodsDAO)Worker.Get<MOS.DAO.HisBillGoods.HisBillGoodsDAO>(); } }
        internal static MOS.DAO.HisMediOrg.HisMediOrgDAO HisMediOrgDAO { get { return (MOS.DAO.HisMediOrg.HisMediOrgDAO)Worker.Get<MOS.DAO.HisMediOrg.HisMediOrgDAO>(); } }
        internal static MOS.DAO.HisMemaGroup.HisMemaGroupDAO HisMemaGroupDAO { get { return (MOS.DAO.HisMemaGroup.HisMemaGroupDAO)Worker.Get<MOS.DAO.HisMemaGroup.HisMemaGroupDAO>(); } }
        internal static MOS.DAO.HisTreatmentLogging.HisTreatmentLoggingDAO HisTreatmentLoggingDAO { get { return (MOS.DAO.HisTreatmentLogging.HisTreatmentLoggingDAO)Worker.Get<MOS.DAO.HisTreatmentLogging.HisTreatmentLoggingDAO>(); } }
        internal static MOS.DAO.HisExpMestUser.HisExpMestUserDAO HisExpMestUserDAO { get { return (MOS.DAO.HisExpMestUser.HisExpMestUserDAO)Worker.Get<MOS.DAO.HisExpMestUser.HisExpMestUserDAO>(); } }
        internal static MOS.DAO.HisConfig.HisConfigDAO HisConfigDAO { get { return (MOS.DAO.HisConfig.HisConfigDAO)Worker.Get<MOS.DAO.HisConfig.HisConfigDAO>(); } }
        internal static MOS.DAO.HisPackage.HisPackageDAO HisPackageDAO { get { return (MOS.DAO.HisPackage.HisPackageDAO)Worker.Get<MOS.DAO.HisPackage.HisPackageDAO>(); } }
        internal static MOS.DAO.HisServiceReqMety.HisServiceReqMetyDAO HisServiceReqMetyDAO { get { return (MOS.DAO.HisServiceReqMety.HisServiceReqMetyDAO)Worker.Get<MOS.DAO.HisServiceReqMety.HisServiceReqMetyDAO>(); } }
        internal static MOS.DAO.Sql.SqlDAO SqlDAO { get { return (MOS.DAO.Sql.SqlDAO)Worker.Get<MOS.DAO.Sql.SqlDAO>(); } }
        internal static MOS.DAO.HisExpMestMatyReq.HisExpMestMatyReqDAO HisExpMestMatyReqDAO { get { return (MOS.DAO.HisExpMestMatyReq.HisExpMestMatyReqDAO)Worker.Get<MOS.DAO.HisExpMestMatyReq.HisExpMestMatyReqDAO>(); } }
        internal static MOS.DAO.HisExpMestMetyReq.HisExpMestMetyReqDAO HisExpMestMetyReqDAO { get { return (MOS.DAO.HisExpMestMetyReq.HisExpMestMetyReqDAO)Worker.Get<MOS.DAO.HisExpMestMetyReq.HisExpMestMetyReqDAO>(); } }
        internal static MOS.DAO.HisSereServDeposit.HisSereServDepositDAO HisSereServDepositDAO { get { return (MOS.DAO.HisSereServDeposit.HisSereServDepositDAO)Worker.Get<MOS.DAO.HisSereServDeposit.HisSereServDepositDAO>(); } }
        internal static MOS.DAO.HisSeseDepoRepay.HisSeseDepoRepayDAO HisSeseDepoRepayDAO { get { return (MOS.DAO.HisSeseDepoRepay.HisSeseDepoRepayDAO)Worker.Get<MOS.DAO.HisSeseDepoRepay.HisSeseDepoRepayDAO>(); } }
        internal static MOS.DAO.HisExpMestBltyReq.HisExpMestBltyReqDAO HisExpMestBltyReqDAO { get { return (MOS.DAO.HisExpMestBltyReq.HisExpMestBltyReqDAO)Worker.Get<MOS.DAO.HisExpMestBltyReq.HisExpMestBltyReqDAO>(); } }
        internal static MOS.DAO.HisRepayReason.HisRepayReasonDAO HisRepayReasonDAO { get { return (MOS.DAO.HisRepayReason.HisRepayReasonDAO)Worker.Get<MOS.DAO.HisRepayReason.HisRepayReasonDAO>(); } }
		internal static MOS.DAO.HisCacheMonitor.HisCacheMonitorDAO HisCacheMonitorDAO { get { return (MOS.DAO.HisCacheMonitor.HisCacheMonitorDAO)Worker.Get<MOS.DAO.HisCacheMonitor.HisCacheMonitorDAO>(); } }
	}
}
