//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDA.EFMODEL.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SDA_COMMUNE> SDA_COMMUNE { get; set; }
        public DbSet<SDA_COMMUNE_MAP> SDA_COMMUNE_MAP { get; set; }
        public DbSet<SDA_CONFIG> SDA_CONFIG { get; set; }
        public DbSet<SDA_CONFIG_APP> SDA_CONFIG_APP { get; set; }
        public DbSet<SDA_CONFIG_APP_USER> SDA_CONFIG_APP_USER { get; set; }
        public DbSet<SDA_CUSTOMIZE_BUTTON> SDA_CUSTOMIZE_BUTTON { get; set; }
        public DbSet<SDA_CUSTOMIZE_UI> SDA_CUSTOMIZE_UI { get; set; }
        public DbSet<SDA_DELETE_DATA> SDA_DELETE_DATA { get; set; }
        public DbSet<SDA_DISTRICT> SDA_DISTRICT { get; set; }
        public DbSet<SDA_DISTRICT_MAP> SDA_DISTRICT_MAP { get; set; }
        public DbSet<SDA_ETHNIC> SDA_ETHNIC { get; set; }
        public DbSet<SDA_EVENT_LOG> SDA_EVENT_LOG { get; set; }
        public DbSet<SDA_GROUP> SDA_GROUP { get; set; }
        public DbSet<SDA_GROUP_TYPE> SDA_GROUP_TYPE { get; set; }
        public DbSet<SDA_HIDE_CONTROL> SDA_HIDE_CONTROL { get; set; }
        public DbSet<SDA_LANGUAGE> SDA_LANGUAGE { get; set; }
        public DbSet<SDA_LICENSE> SDA_LICENSE { get; set; }
        public DbSet<SDA_METADATA> SDA_METADATA { get; set; }
        public DbSet<SDA_MODULE_FIELD> SDA_MODULE_FIELD { get; set; }
        public DbSet<SDA_NATIONAL> SDA_NATIONAL { get; set; }
        public DbSet<SDA_NOTIFY> SDA_NOTIFY { get; set; }
        public DbSet<SDA_PROVINCE> SDA_PROVINCE { get; set; }
        public DbSet<SDA_PROVINCE_MAP> SDA_PROVINCE_MAP { get; set; }
        public DbSet<SDA_RELIGION> SDA_RELIGION { get; set; }
        public DbSet<SDA_SQL> SDA_SQL { get; set; }
        public DbSet<SDA_SQL_PARAM> SDA_SQL_PARAM { get; set; }
        public DbSet<SDA_TRANSLATE> SDA_TRANSLATE { get; set; }
        public DbSet<SDA_TROUBLE> SDA_TROUBLE { get; set; }
        public DbSet<V_SDA_COMMUNE> V_SDA_COMMUNE { get; set; }
        public DbSet<V_SDA_CONFIG_APP_USER> V_SDA_CONFIG_APP_USER { get; set; }
        public DbSet<V_SDA_DISTRICT> V_SDA_DISTRICT { get; set; }
        public DbSet<V_SDA_GROUP> V_SDA_GROUP { get; set; }
        public DbSet<V_SDA_NATIONAL> V_SDA_NATIONAL { get; set; }
        public DbSet<V_SDA_PROVINCE> V_SDA_PROVINCE { get; set; }
    }
}
