//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDA.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDA_SQL
    {
        public SDA_SQL()
        {
            this.SDA_SQL_PARAM = new HashSet<SDA_SQL_PARAM>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string SQL_NAME { get; set; }
        public string SQL_CODE { get; set; }
        public long SQL_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string SCHEMA_CODE { get; set; }
        public string CONTENT { get; set; }
    
        public virtual ICollection<SDA_SQL_PARAM> SDA_SQL_PARAM { get; set; }
    }
}
