//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDA.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDA_EVENT_LOG
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string LOGIN_NAME { get; set; }
        public string IP { get; set; }
        public string DESCRIPTION { get; set; }
        public string APP_CODE { get; set; }
        public Nullable<long> EVENT_TIME { get; set; }
        public string TITLE { get; set; }
        public Nullable<long> CREATE_DATE { get; set; }
        public Nullable<decimal> EVENT_DATE { get; set; }
        public Nullable<decimal> EVENT_MONTH { get; set; }
    }
}
