using System; 
using System.Collections.Generic; 
using System.Linq; 
using System.Text; 
using System.Threading.Tasks; 

namespace MRS.Processor.Mrs00486
{
    class Mrs00486RDO
    {
        public string SERVICE_TYPE_NAME { get;  set;  }
        public string TDL_SERVICE_NAME { get;  set;  }

        public decimal AMOUNT_BHYT_1 { get;  set;  }
        public decimal AMOUNT_BHYT_2 { get;  set;  }
        public decimal AMOUNT_BHYT_3 { get;  set;  }
        public decimal AMOUNT_BHYT_4 { get;  set;  }
        public decimal AMOUNT_BHYT_5 { get;  set;  }
        public decimal AMOUNT_BHYT_6 { get;  set;  }
        public decimal AMOUNT_BHYT_7 { get;  set;  }
        public decimal AMOUNT_BHYT_8 { get;  set;  }
        public decimal AMOUNT_BHYT_9 { get;  set;  }
        public decimal AMOUNT_BHYT_10 { get;  set;  }
        public decimal AMOUNT_BHYT_11 { get;  set;  }
        public decimal AMOUNT_BHYT_12 { get;  set;  }
        public decimal AMOUNT_BHYT_13 { get;  set;  }
        public decimal AMOUNT_BHYT_14 { get;  set;  }
        public decimal AMOUNT_BHYT_15 { get;  set;  }
        public decimal AMOUNT_BHYT_16 { get;  set;  }
        public decimal AMOUNT_BHYT_17 { get;  set;  }
        public decimal AMOUNT_BHYT_18 { get;  set;  }
        public decimal AMOUNT_BHYT_19 { get;  set;  }
        public decimal AMOUNT_BHYT_20 { get;  set;  }
        public decimal AMOUNT_BHYT_21 { get;  set;  }
        public decimal AMOUNT_BHYT_22 { get;  set;  }
        public decimal AMOUNT_BHYT_23 { get;  set;  }
        public decimal AMOUNT_BHYT_24 { get;  set;  }
        public decimal AMOUNT_BHYT_25 { get;  set;  }
        public decimal AMOUNT_BHYT_26 { get;  set;  }
        public decimal AMOUNT_BHYT_27 { get;  set;  }
        public decimal AMOUNT_BHYT_28 { get;  set;  }
        public decimal AMOUNT_BHYT_29 { get;  set;  }
        public decimal AMOUNT_BHYT_30 { get;  set;  }
        public decimal AMOUNT_BHYT_31 { get;  set;  }
        public decimal AMOUNT_BHYT_32 { get;  set;  }
        public decimal AMOUNT_BHYT_33 { get;  set;  }
        public decimal AMOUNT_BHYT_34 { get;  set;  }
        public decimal AMOUNT_BHYT_35 { get;  set;  }
        public decimal AMOUNT_BHYT_36 { get;  set;  }
        public decimal AMOUNT_BHYT_37 { get;  set;  }
        public decimal AMOUNT_BHYT_38 { get;  set;  }
        public decimal AMOUNT_BHYT_39 { get;  set;  }
        public decimal AMOUNT_BHYT_40 { get;  set;  }
        public decimal AMOUNT_BHYT_41 { get;  set;  }
        public decimal AMOUNT_BHYT_42 { get;  set;  }
        public decimal AMOUNT_BHYT_43 { get;  set;  }
        public decimal AMOUNT_BHYT_44 { get;  set;  }
        public decimal AMOUNT_BHYT_45 { get;  set;  }
        public decimal AMOUNT_BHYT_46 { get;  set;  }
        public decimal AMOUNT_BHYT_47 { get;  set;  }
        public decimal AMOUNT_BHYT_48 { get;  set;  }
        public decimal AMOUNT_BHYT_49 { get;  set;  }
        public decimal AMOUNT_BHYT_50 { get;  set;  }

        public decimal AMOUNT_VP_1 { get;  set;  }
        public decimal AMOUNT_VP_2 { get;  set;  }
        public decimal AMOUNT_VP_3 { get;  set;  }
        public decimal AMOUNT_VP_4 { get;  set;  }
        public decimal AMOUNT_VP_5 { get;  set;  }
        public decimal AMOUNT_VP_6 { get;  set;  }
        public decimal AMOUNT_VP_7 { get;  set;  }
        public decimal AMOUNT_VP_8 { get;  set;  }
        public decimal AMOUNT_VP_9 { get;  set;  }
        public decimal AMOUNT_VP_10 { get;  set;  }
        public decimal AMOUNT_VP_11 { get;  set;  }
        public decimal AMOUNT_VP_12 { get;  set;  }
        public decimal AMOUNT_VP_13 { get;  set;  }
        public decimal AMOUNT_VP_14 { get;  set;  }
        public decimal AMOUNT_VP_15 { get;  set;  }
        public decimal AMOUNT_VP_16 { get;  set;  }
        public decimal AMOUNT_VP_17 { get;  set;  }
        public decimal AMOUNT_VP_18 { get;  set;  }
        public decimal AMOUNT_VP_19 { get;  set;  }
        public decimal AMOUNT_VP_20 { get;  set;  }
        public decimal AMOUNT_VP_21 { get;  set;  }
        public decimal AMOUNT_VP_22 { get;  set;  }
        public decimal AMOUNT_VP_23 { get;  set;  }
        public decimal AMOUNT_VP_24 { get;  set;  }
        public decimal AMOUNT_VP_25 { get;  set;  }
        public decimal AMOUNT_VP_26 { get;  set;  }
        public decimal AMOUNT_VP_27 { get;  set;  }
        public decimal AMOUNT_VP_28 { get;  set;  }
        public decimal AMOUNT_VP_29 { get;  set;  }
        public decimal AMOUNT_VP_30 { get;  set;  }
        public decimal AMOUNT_VP_31 { get;  set;  }
        public decimal AMOUNT_VP_32 { get;  set;  }
        public decimal AMOUNT_VP_33 { get;  set;  }
        public decimal AMOUNT_VP_34 { get;  set;  }
        public decimal AMOUNT_VP_35 { get;  set;  }
        public decimal AMOUNT_VP_36 { get;  set;  }
        public decimal AMOUNT_VP_37 { get;  set;  }
        public decimal AMOUNT_VP_38 { get;  set;  }
        public decimal AMOUNT_VP_39 { get;  set;  }
        public decimal AMOUNT_VP_40 { get;  set;  }
        public decimal AMOUNT_VP_41 { get;  set;  }
        public decimal AMOUNT_VP_42 { get;  set;  }
        public decimal AMOUNT_VP_43 { get;  set;  }
        public decimal AMOUNT_VP_44 { get;  set;  }
        public decimal AMOUNT_VP_45 { get;  set;  }
        public decimal AMOUNT_VP_46 { get;  set;  }
        public decimal AMOUNT_VP_47 { get;  set;  }
        public decimal AMOUNT_VP_48 { get;  set;  }
        public decimal AMOUNT_VP_49 { get;  set;  }
        public decimal AMOUNT_VP_50 { get;  set;  }
        

        public decimal VIR_TOTAL_PRICE_BHYT_1 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_2 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_3 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_4 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_5 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_6 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_7 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_8 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_9 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_10 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_11 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_12 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_13 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_14 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_15 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_16 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_17 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_18 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_19 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_20 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_21 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_22 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_23 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_24 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_25 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_26 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_27 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_28 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_29 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_30 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_31 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_32 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_33 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_34 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_35 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_36 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_37 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_38 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_39 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_40 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_41 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_42 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_43 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_44 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_45 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_46 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_47 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_48 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_49 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_BHYT_50 { get;  set;  }

        public decimal VIR_TOTAL_PRICE_VP_1 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_2 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_3 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_4 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_5 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_6 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_7 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_8 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_9 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_10 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_11 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_12 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_13 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_14 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_15 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_16 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_17 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_18 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_19 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_20 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_21 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_22 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_23 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_24 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_25 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_26 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_27 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_28 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_29 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_30 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_31 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_32 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_33 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_34 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_35 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_36 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_37 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_38 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_39 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_40 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_41 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_42 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_43 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_44 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_45 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_46 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_47 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_48 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_49 { get;  set;  }
        public decimal VIR_TOTAL_PRICE_VP_50 { get;  set;  }
    }
}
