//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TYT.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYT_FETUS_BORN
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string PATIENT_CODE { get; set; }
        public string PERSON_CODE { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string VIR_PERSON_NAME { get; set; }
        public long DOB { get; set; }
        public Nullable<short> IS_HAS_NOT_DAY_DOB { get; set; }
        public string GENDER_NAME { get; set; }
        public string PERSON_ADDRESS { get; set; }
        public string CAREER_NAME { get; set; }
        public string ETHNIC_NAME { get; set; }
        public string BHYT_NUMBER { get; set; }
        public Nullable<short> IS_FETUS_MANAGE { get; set; }
        public Nullable<short> IS_UV_FULL { get; set; }
        public Nullable<long> CHECK_CASE { get; set; }
        public Nullable<short> IS_HIV_BEFORE { get; set; }
        public Nullable<short> IS_HIV_BORN { get; set; }
        public Nullable<long> PARA_NORMAL_COUNT { get; set; }
        public Nullable<long> PARA_PREMATURELY_COUNT { get; set; }
        public Nullable<long> PARA_MISCARRIAGE_COUNT { get; set; }
        public Nullable<long> PARA_CHILD_COUNT { get; set; }
        public string BORN_METHOD { get; set; }
        public string OBSTETRIC_COMPLICATION { get; set; }
        public Nullable<short> IS_DEATH { get; set; }
        public Nullable<long> CHILD_GENDER_ID { get; set; }
        public Nullable<decimal> CHILD_WEIGHT { get; set; }
        public string CHILD_STATUS { get; set; }
        public Nullable<short> IS_CHILD_DEATH { get; set; }
        public string BORN_PLACE { get; set; }
        public string MIDWIFE_NAME { get; set; }
        public Nullable<short> IS_BREASTFEEDING_FIRST_HOUR { get; set; }
        public Nullable<short> IS_K1 { get; set; }
        public string FIRST_WEEK_EXAM { get; set; }
        public string EXAM_742 { get; set; }
        public string NOTE { get; set; }
    }
}
