//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TYT.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYT_UNINFECT_ICD
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string UNINFECT_ICD_CODE { get; set; }
        public string UNINFECT_ICD_NAME { get; set; }
        public long UNINFECT_ICD_GROUP_ID { get; set; }
    
        public virtual TYT_UNINFECT_ICD_GROUP TYT_UNINFECT_ICD_GROUP { get; set; }
    }
}
