using MOS.EFMODEL.DataModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MRS.Processor.Mrs00312
{
    public class Mrs00312RDO 
    {
        public int TYPE { get; set; }
        public long PARENT_TYPE_ID { get; set; }
        public string PARENT_NAME { get; set; }

        public long MEDICINE_ID { get; set; }
        public string PACKAGE_NUMBER { get; set; }
        public long? EXPIRED_DATE { get; set; }

        public long SERVICE_ID { get; set; }

        public long MEDICINE_TYPE_ID { get; set; }
        public string MEDICINE_TYPE_CODE { get; set; }
        public string MEDICINE_TYPE_NAME { get; set; }
        public long PARENT_NUM_ORDER { get; set; }
        public string PARENT_MEDICINE_TYPE_CODE { get; set; }
        public string PARENT_MEDICINE_TYPE_NAME { get; set; }

        public string CONCENTRA { get; set; }
        public string ACTIVE_INGR_CODE { get; set; }
        public string ACTIVE_INGR_NAME { get; set; }
        public string SERVICE_UNIT_NAME { get; set; }
        public decimal IMP_PRICE { get; set; }
        public decimal IMP_VAT_RATIO { get; set; }
        public decimal AMOUNT { get; set; }
        public decimal TH_AMOUNT { get; set; }
        public decimal MOBA_AMOUNT { get; set; }
        public decimal EXP_AMOUNT { get; set; }
        public string MANUFACTURER_NAME { get; set; }
        public string NATIONAL_NAME { get; set; }
        public string REGISTER_NUMBER { get; set; }
        public Dictionary<string, decimal> DIC_AMOUNT { get; set; }
        public Dictionary<string, decimal> DIC_MOBA_AMOUNT { get; set; }
        //public decimal AMOUNT_DDT { get; set; }
        //public decimal AMOUNT_CK { get; set; }
        //public decimal AMOUNT_HPKP { get; set; }


        public Dictionary<string, decimal> DIC_REASON_AMOUNT { get; set; }
        //public decimal MOBA_AMOUNT_DDT { get; set; }
        //public decimal MOBA_AMOUNT_CK { get; set; }
        //public decimal MOBA_AMOUNT_HPKP { get; set; }

        public decimal AMOUNT_1 { get; set; }
        public decimal AMOUNT_2 { get; set; }
        public decimal AMOUNT_3 { get; set; }
        public decimal AMOUNT_4 { get; set; }
        public decimal AMOUNT_5 { get; set; }
        public decimal AMOUNT_6 { get; set; }
        public decimal AMOUNT_7 { get; set; }
        public decimal AMOUNT_8 { get; set; }
        public decimal AMOUNT_9 { get; set; }
        public decimal AMOUNT_10 { get; set; }
        public decimal AMOUNT_11 { get; set; }
        public decimal AMOUNT_12 { get; set; }
        public decimal AMOUNT_13 { get; set; }
        public decimal AMOUNT_14 { get; set; }
        public decimal AMOUNT_15 { get; set; }
        public decimal AMOUNT_16 { get; set; }
        public decimal AMOUNT_17 { get; set; }
        public decimal AMOUNT_18 { get; set; }
        public decimal AMOUNT_19 { get; set; }
        public decimal AMOUNT_20 { get; set; }
        public decimal AMOUNT_21 { get; set; }
        public decimal AMOUNT_22 { get; set; }
        public decimal AMOUNT_23 { get; set; }
        public decimal AMOUNT_24 { get; set; }
        public decimal AMOUNT_25 { get; set; }
        public decimal AMOUNT_26 { get; set; }
        public decimal AMOUNT_27 { get; set; }
        public decimal AMOUNT_28 { get; set; }
        public decimal AMOUNT_29 { get; set; }
        public decimal AMOUNT_30 { get; set; }
        public decimal AMOUNT_31 { get; set; }
        public decimal AMOUNT_32 { get; set; }
        public decimal AMOUNT_33 { get; set; }
        public decimal AMOUNT_34 { get; set; }
        public decimal AMOUNT_35 { get; set; }
        public decimal AMOUNT_36 { get; set; }
        public decimal AMOUNT_37 { get; set; }
        public decimal AMOUNT_38 { get; set; }
        public decimal AMOUNT_39 { get; set; }
        public decimal AMOUNT_40 { get; set; }
        public decimal AMOUNT_41 { get; set; }
        public decimal AMOUNT_42 { get; set; }
        public decimal AMOUNT_43 { get; set; }
        public decimal AMOUNT_44 { get; set; }
        public decimal AMOUNT_45 { get; set; }
        public decimal AMOUNT_46 { get; set; }
        public decimal AMOUNT_47 { get; set; }
        public decimal AMOUNT_48 { get; set; }
        public decimal AMOUNT_49 { get; set; }
        public decimal AMOUNT_50 { get; set; }
        public decimal AMOUNT_51 { get; set; }
        public decimal AMOUNT_52 { get; set; }
        public decimal AMOUNT_53 { get; set; }
        public decimal AMOUNT_54 { get; set; }
        public decimal AMOUNT_55 { get; set; }
        public decimal AMOUNT_56 { get; set; }
        public decimal AMOUNT_57 { get; set; }
        public decimal AMOUNT_58 { get; set; }
        public decimal AMOUNT_59 { get; set; }
        public decimal AMOUNT_60 { get; set; }
        public decimal AMOUNT_61 { get; set; }
        public decimal AMOUNT_62 { get; set; }
        public decimal AMOUNT_63 { get; set; }
        public decimal AMOUNT_64 { get; set; }
        public decimal AMOUNT_65 { get; set; }
        public decimal AMOUNT_66 { get; set; }
        public decimal AMOUNT_67 { get; set; }
        public decimal AMOUNT_68 { get; set; }
        public decimal AMOUNT_69 { get; set; }
        public decimal AMOUNT_70 { get; set; }
        public decimal AMOUNT_71 { get; set; }
        public decimal AMOUNT_72 { get; set; }
        public decimal AMOUNT_73 { get; set; }
        public decimal AMOUNT_74 { get; set; }
        public decimal AMOUNT_75 { get; set; }
        public decimal AMOUNT_76 { get; set; }
        public decimal AMOUNT_77 { get; set; }
        public decimal AMOUNT_78 { get; set; }
        public decimal AMOUNT_79 { get; set; }
        public decimal AMOUNT_80 { get; set; }
        public decimal AMOUNT_81 { get; set; }
        public decimal AMOUNT_82 { get; set; }
        public decimal AMOUNT_83 { get; set; }
        public decimal AMOUNT_84 { get; set; }
        public decimal AMOUNT_85 { get; set; }
        public decimal AMOUNT_86 { get; set; }
        public decimal AMOUNT_87 { get; set; }
        public decimal AMOUNT_88 { get; set; }
        public decimal AMOUNT_89 { get; set; }
        public decimal AMOUNT_90 { get; set; }
        public decimal AMOUNT_91 { get; set; }
        public decimal AMOUNT_92 { get; set; }
        public decimal AMOUNT_93 { get; set; }
        public decimal AMOUNT_94 { get; set; }
        public decimal AMOUNT_95 { get; set; }
        public decimal AMOUNT_96 { get; set; }
        public decimal AMOUNT_97 { get; set; }
        public decimal AMOUNT_98 { get; set; }
        public decimal AMOUNT_99 { get; set; }
        public decimal AMOUNT_100 { get; set; }
        public decimal AMOUNT_101 { get; set; }
        public decimal AMOUNT_102 { get; set; }
        public decimal AMOUNT_103 { get; set; }
        public decimal AMOUNT_104 { get; set; }
        public decimal AMOUNT_105 { get; set; }
        public decimal AMOUNT_106 { get; set; }
        public decimal AMOUNT_107 { get; set; }
        public decimal AMOUNT_108 { get; set; }
        public decimal AMOUNT_109 { get; set; }
        public decimal AMOUNT_110 { get; set; }
        public decimal AMOUNT_111 { get; set; }
        public decimal AMOUNT_112 { get; set; }
        public decimal AMOUNT_113 { get; set; }
        public decimal AMOUNT_114 { get; set; }
        public decimal AMOUNT_115 { get; set; }
        public decimal AMOUNT_116 { get; set; }
        public decimal AMOUNT_117 { get; set; }
        public decimal AMOUNT_118 { get; set; }
        public decimal AMOUNT_119 { get; set; }
        public decimal AMOUNT_120 { get; set; }
        public decimal AMOUNT_121 { get; set; }
        public decimal AMOUNT_122 { get; set; }
        public decimal AMOUNT_123 { get; set; }
        public decimal AMOUNT_124 { get; set; }
        public decimal AMOUNT_125 { get; set; }
        public decimal AMOUNT_126 { get; set; }
        public decimal AMOUNT_127 { get; set; }
        public decimal AMOUNT_128 { get; set; }
        public decimal AMOUNT_129 { get; set; }
        public decimal AMOUNT_130 { get; set; }
        public decimal AMOUNT_131 { get; set; }
        public decimal AMOUNT_132 { get; set; }
        public decimal AMOUNT_133 { get; set; }
        public decimal AMOUNT_134 { get; set; }
        public decimal AMOUNT_135 { get; set; }
        public decimal AMOUNT_136 { get; set; }
        public decimal AMOUNT_137 { get; set; }
        public decimal AMOUNT_138 { get; set; }
        public decimal AMOUNT_139 { get; set; }
        public decimal AMOUNT_140 { get; set; }
        public decimal AMOUNT_141 { get; set; }
        public decimal AMOUNT_142 { get; set; }
        public decimal AMOUNT_143 { get; set; }
        public decimal AMOUNT_144 { get; set; }
        public decimal AMOUNT_145 { get; set; }
        public decimal AMOUNT_146 { get; set; }
        public decimal AMOUNT_147 { get; set; }
        public decimal AMOUNT_148 { get; set; }
        public decimal AMOUNT_149 { get; set; }
        public decimal AMOUNT_150 { get; set; }
        public decimal AMOUNT_151 { get; set; }
        public decimal AMOUNT_152 { get; set; }
        public decimal AMOUNT_153 { get; set; }
        public decimal AMOUNT_154 { get; set; }
        public decimal AMOUNT_155 { get; set; }
        public decimal AMOUNT_156 { get; set; }
        public decimal AMOUNT_157 { get; set; }
        public decimal AMOUNT_158 { get; set; }
        public decimal AMOUNT_159 { get; set; }
        public decimal AMOUNT_160 { get; set; }
        public decimal AMOUNT_161 { get; set; }
        public decimal AMOUNT_162 { get; set; }
        public decimal AMOUNT_163 { get; set; }
        public decimal AMOUNT_164 { get; set; }
        public decimal AMOUNT_165 { get; set; }
        public decimal AMOUNT_166 { get; set; }
        public decimal AMOUNT_167 { get; set; }
        public decimal AMOUNT_168 { get; set; }
        public decimal AMOUNT_169 { get; set; }
        public decimal AMOUNT_170 { get; set; }
        public decimal AMOUNT_171 { get; set; }
        public decimal AMOUNT_172 { get; set; }
        public decimal AMOUNT_173 { get; set; }
        public decimal AMOUNT_174 { get; set; }
        public decimal AMOUNT_175 { get; set; }
        public decimal AMOUNT_176 { get; set; }
        public decimal AMOUNT_177 { get; set; }
        public decimal AMOUNT_178 { get; set; }
        public decimal AMOUNT_179 { get; set; }
        public decimal AMOUNT_180 { get; set; }
        public decimal AMOUNT_181 { get; set; }
        public decimal AMOUNT_182 { get; set; }
        public decimal AMOUNT_183 { get; set; }
        public decimal AMOUNT_184 { get; set; }
        public decimal AMOUNT_185 { get; set; }
        public decimal AMOUNT_186 { get; set; }
        public decimal AMOUNT_187 { get; set; }
        public decimal AMOUNT_188 { get; set; }
        public decimal AMOUNT_189 { get; set; }
        public decimal AMOUNT_190 { get; set; }
        public decimal AMOUNT_191 { get; set; }
        public decimal AMOUNT_192 { get; set; }
        public decimal AMOUNT_193 { get; set; }
        public decimal AMOUNT_194 { get; set; }
        public decimal AMOUNT_195 { get; set; }
        public decimal AMOUNT_196 { get; set; }
        public decimal AMOUNT_197 { get; set; }
        public decimal AMOUNT_198 { get; set; }
        public decimal AMOUNT_199 { get; set; }
        public decimal AMOUNT_200 { get; set; }

        public decimal MOBA_AMOUNT_1 { get; set; }
        public decimal MOBA_AMOUNT_2 { get; set; }
        public decimal MOBA_AMOUNT_3 { get; set; }
        public decimal MOBA_AMOUNT_4 { get; set; }
        public decimal MOBA_AMOUNT_5 { get; set; }
        public decimal MOBA_AMOUNT_6 { get; set; }
        public decimal MOBA_AMOUNT_7 { get; set; }
        public decimal MOBA_AMOUNT_8 { get; set; }
        public decimal MOBA_AMOUNT_9 { get; set; }
        public decimal MOBA_AMOUNT_10 { get; set; }
        public decimal MOBA_AMOUNT_11 { get; set; }
        public decimal MOBA_AMOUNT_12 { get; set; }
        public decimal MOBA_AMOUNT_13 { get; set; }
        public decimal MOBA_AMOUNT_14 { get; set; }
        public decimal MOBA_AMOUNT_15 { get; set; }
        public decimal MOBA_AMOUNT_16 { get; set; }
        public decimal MOBA_AMOUNT_17 { get; set; }
        public decimal MOBA_AMOUNT_18 { get; set; }
        public decimal MOBA_AMOUNT_19 { get; set; }
        public decimal MOBA_AMOUNT_20 { get; set; }
        public decimal MOBA_AMOUNT_21 { get; set; }
        public decimal MOBA_AMOUNT_22 { get; set; }
        public decimal MOBA_AMOUNT_23 { get; set; }
        public decimal MOBA_AMOUNT_24 { get; set; }
        public decimal MOBA_AMOUNT_25 { get; set; }
        public decimal MOBA_AMOUNT_26 { get; set; }
        public decimal MOBA_AMOUNT_27 { get; set; }
        public decimal MOBA_AMOUNT_28 { get; set; }
        public decimal MOBA_AMOUNT_29 { get; set; }
        public decimal MOBA_AMOUNT_30 { get; set; }
        public decimal MOBA_AMOUNT_31 { get; set; }
        public decimal MOBA_AMOUNT_32 { get; set; }
        public decimal MOBA_AMOUNT_33 { get; set; }
        public decimal MOBA_AMOUNT_34 { get; set; }
        public decimal MOBA_AMOUNT_35 { get; set; }
        public decimal MOBA_AMOUNT_36 { get; set; }
        public decimal MOBA_AMOUNT_37 { get; set; }
        public decimal MOBA_AMOUNT_38 { get; set; }
        public decimal MOBA_AMOUNT_39 { get; set; }
        public decimal MOBA_AMOUNT_40 { get; set; }
        public decimal MOBA_AMOUNT_41 { get; set; }
        public decimal MOBA_AMOUNT_42 { get; set; }
        public decimal MOBA_AMOUNT_43 { get; set; }
        public decimal MOBA_AMOUNT_44 { get; set; }
        public decimal MOBA_AMOUNT_45 { get; set; }
        public decimal MOBA_AMOUNT_46 { get; set; }
        public decimal MOBA_AMOUNT_47 { get; set; }
        public decimal MOBA_AMOUNT_48 { get; set; }
        public decimal MOBA_AMOUNT_49 { get; set; }
        public decimal MOBA_AMOUNT_50 { get; set; }
        public decimal MOBA_AMOUNT_51 { get; set; }
        public decimal MOBA_AMOUNT_52 { get; set; }
        public decimal MOBA_AMOUNT_53 { get; set; }
        public decimal MOBA_AMOUNT_54 { get; set; }
        public decimal MOBA_AMOUNT_55 { get; set; }
        public decimal MOBA_AMOUNT_56 { get; set; }
        public decimal MOBA_AMOUNT_57 { get; set; }
        public decimal MOBA_AMOUNT_58 { get; set; }
        public decimal MOBA_AMOUNT_59 { get; set; }
        public decimal MOBA_AMOUNT_60 { get; set; }
        public decimal MOBA_AMOUNT_61 { get; set; }
        public decimal MOBA_AMOUNT_62 { get; set; }
        public decimal MOBA_AMOUNT_63 { get; set; }
        public decimal MOBA_AMOUNT_64 { get; set; }
        public decimal MOBA_AMOUNT_65 { get; set; }
        public decimal MOBA_AMOUNT_66 { get; set; }
        public decimal MOBA_AMOUNT_67 { get; set; }
        public decimal MOBA_AMOUNT_68 { get; set; }
        public decimal MOBA_AMOUNT_69 { get; set; }
        public decimal MOBA_AMOUNT_70 { get; set; }
        public decimal MOBA_AMOUNT_71 { get; set; }
        public decimal MOBA_AMOUNT_72 { get; set; }
        public decimal MOBA_AMOUNT_73 { get; set; }
        public decimal MOBA_AMOUNT_74 { get; set; }
        public decimal MOBA_AMOUNT_75 { get; set; }
        public decimal MOBA_AMOUNT_76 { get; set; }
        public decimal MOBA_AMOUNT_77 { get; set; }
        public decimal MOBA_AMOUNT_78 { get; set; }
        public decimal MOBA_AMOUNT_79 { get; set; }
        public decimal MOBA_AMOUNT_80 { get; set; }
        public decimal MOBA_AMOUNT_81 { get; set; }
        public decimal MOBA_AMOUNT_82 { get; set; }
        public decimal MOBA_AMOUNT_83 { get; set; }
        public decimal MOBA_AMOUNT_84 { get; set; }
        public decimal MOBA_AMOUNT_85 { get; set; }
        public decimal MOBA_AMOUNT_86 { get; set; }
        public decimal MOBA_AMOUNT_87 { get; set; }
        public decimal MOBA_AMOUNT_88 { get; set; }
        public decimal MOBA_AMOUNT_89 { get; set; }
        public decimal MOBA_AMOUNT_90 { get; set; }
        public decimal MOBA_AMOUNT_91 { get; set; }
        public decimal MOBA_AMOUNT_92 { get; set; }
        public decimal MOBA_AMOUNT_93 { get; set; }
        public decimal MOBA_AMOUNT_94 { get; set; }
        public decimal MOBA_AMOUNT_95 { get; set; }
        public decimal MOBA_AMOUNT_96 { get; set; }
        public decimal MOBA_AMOUNT_97 { get; set; }
        public decimal MOBA_AMOUNT_98 { get; set; }
        public decimal MOBA_AMOUNT_99 { get; set; }
        public decimal MOBA_AMOUNT_100 { get; set; }
        public decimal MOBA_AMOUNT_101 { get; set; }
        public decimal MOBA_AMOUNT_102 { get; set; }
        public decimal MOBA_AMOUNT_103 { get; set; }
        public decimal MOBA_AMOUNT_104 { get; set; }
        public decimal MOBA_AMOUNT_105 { get; set; }
        public decimal MOBA_AMOUNT_106 { get; set; }
        public decimal MOBA_AMOUNT_107 { get; set; }
        public decimal MOBA_AMOUNT_108 { get; set; }
        public decimal MOBA_AMOUNT_109 { get; set; }
        public decimal MOBA_AMOUNT_110 { get; set; }
        public decimal MOBA_AMOUNT_111 { get; set; }
        public decimal MOBA_AMOUNT_112 { get; set; }
        public decimal MOBA_AMOUNT_113 { get; set; }
        public decimal MOBA_AMOUNT_114 { get; set; }
        public decimal MOBA_AMOUNT_115 { get; set; }
        public decimal MOBA_AMOUNT_116 { get; set; }
        public decimal MOBA_AMOUNT_117 { get; set; }
        public decimal MOBA_AMOUNT_118 { get; set; }
        public decimal MOBA_AMOUNT_119 { get; set; }
        public decimal MOBA_AMOUNT_120 { get; set; }
        public decimal MOBA_AMOUNT_121 { get; set; }
        public decimal MOBA_AMOUNT_122 { get; set; }
        public decimal MOBA_AMOUNT_123 { get; set; }
        public decimal MOBA_AMOUNT_124 { get; set; }
        public decimal MOBA_AMOUNT_125 { get; set; }
        public decimal MOBA_AMOUNT_126 { get; set; }
        public decimal MOBA_AMOUNT_127 { get; set; }
        public decimal MOBA_AMOUNT_128 { get; set; }
        public decimal MOBA_AMOUNT_129 { get; set; }
        public decimal MOBA_AMOUNT_130 { get; set; }
        public decimal MOBA_AMOUNT_131 { get; set; }
        public decimal MOBA_AMOUNT_132 { get; set; }
        public decimal MOBA_AMOUNT_133 { get; set; }
        public decimal MOBA_AMOUNT_134 { get; set; }
        public decimal MOBA_AMOUNT_135 { get; set; }
        public decimal MOBA_AMOUNT_136 { get; set; }
        public decimal MOBA_AMOUNT_137 { get; set; }
        public decimal MOBA_AMOUNT_138 { get; set; }
        public decimal MOBA_AMOUNT_139 { get; set; }
        public decimal MOBA_AMOUNT_140 { get; set; }
        public decimal MOBA_AMOUNT_141 { get; set; }
        public decimal MOBA_AMOUNT_142 { get; set; }
        public decimal MOBA_AMOUNT_143 { get; set; }
        public decimal MOBA_AMOUNT_144 { get; set; }
        public decimal MOBA_AMOUNT_145 { get; set; }
        public decimal MOBA_AMOUNT_146 { get; set; }
        public decimal MOBA_AMOUNT_147 { get; set; }
        public decimal MOBA_AMOUNT_148 { get; set; }
        public decimal MOBA_AMOUNT_149 { get; set; }
        public decimal MOBA_AMOUNT_150 { get; set; }
        public decimal MOBA_AMOUNT_151 { get; set; }
        public decimal MOBA_AMOUNT_152 { get; set; }
        public decimal MOBA_AMOUNT_153 { get; set; }
        public decimal MOBA_AMOUNT_154 { get; set; }
        public decimal MOBA_AMOUNT_155 { get; set; }
        public decimal MOBA_AMOUNT_156 { get; set; }
        public decimal MOBA_AMOUNT_157 { get; set; }
        public decimal MOBA_AMOUNT_158 { get; set; }
        public decimal MOBA_AMOUNT_159 { get; set; }
        public decimal MOBA_AMOUNT_160 { get; set; }
        public decimal MOBA_AMOUNT_161 { get; set; }
        public decimal MOBA_AMOUNT_162 { get; set; }
        public decimal MOBA_AMOUNT_163 { get; set; }
        public decimal MOBA_AMOUNT_164 { get; set; }
        public decimal MOBA_AMOUNT_165 { get; set; }
        public decimal MOBA_AMOUNT_166 { get; set; }
        public decimal MOBA_AMOUNT_167 { get; set; }
        public decimal MOBA_AMOUNT_168 { get; set; }
        public decimal MOBA_AMOUNT_169 { get; set; }
        public decimal MOBA_AMOUNT_170 { get; set; }
        public decimal MOBA_AMOUNT_171 { get; set; }
        public decimal MOBA_AMOUNT_172 { get; set; }
        public decimal MOBA_AMOUNT_173 { get; set; }
        public decimal MOBA_AMOUNT_174 { get; set; }
        public decimal MOBA_AMOUNT_175 { get; set; }
        public decimal MOBA_AMOUNT_176 { get; set; }
        public decimal MOBA_AMOUNT_177 { get; set; }
        public decimal MOBA_AMOUNT_178 { get; set; }
        public decimal MOBA_AMOUNT_179 { get; set; }
        public decimal MOBA_AMOUNT_180 { get; set; }
        public decimal MOBA_AMOUNT_181 { get; set; }
        public decimal MOBA_AMOUNT_182 { get; set; }
        public decimal MOBA_AMOUNT_183 { get; set; }
        public decimal MOBA_AMOUNT_184 { get; set; }
        public decimal MOBA_AMOUNT_185 { get; set; }
        public decimal MOBA_AMOUNT_186 { get; set; }
        public decimal MOBA_AMOUNT_187 { get; set; }
        public decimal MOBA_AMOUNT_188 { get; set; }
        public decimal MOBA_AMOUNT_189 { get; set; }
        public decimal MOBA_AMOUNT_190 { get; set; }
        public decimal MOBA_AMOUNT_191 { get; set; }
        public decimal MOBA_AMOUNT_192 { get; set; }
        public decimal MOBA_AMOUNT_193 { get; set; }
        public decimal MOBA_AMOUNT_194 { get; set; }
        public decimal MOBA_AMOUNT_195 { get; set; }
        public decimal MOBA_AMOUNT_196 { get; set; }
        public decimal MOBA_AMOUNT_197 { get; set; }
        public decimal MOBA_AMOUNT_198 { get; set; }
        public decimal MOBA_AMOUNT_199 { get; set; }
        public decimal MOBA_AMOUNT_200 { get; set; }

        public decimal EXP_AMOUNT_1 { get; set; }
        public decimal EXP_AMOUNT_2 { get; set; }
        public decimal EXP_AMOUNT_3 { get; set; }
        public decimal EXP_AMOUNT_4 { get; set; }
        public decimal EXP_AMOUNT_5 { get; set; }
        public decimal EXP_AMOUNT_6 { get; set; }
        public decimal EXP_AMOUNT_7 { get; set; }
        public decimal EXP_AMOUNT_8 { get; set; }
        public decimal EXP_AMOUNT_9 { get; set; }
        public decimal EXP_AMOUNT_10 { get; set; }
        public decimal EXP_AMOUNT_11 { get; set; }
        public decimal EXP_AMOUNT_12 { get; set; }
        public decimal EXP_AMOUNT_13 { get; set; }
        public decimal EXP_AMOUNT_14 { get; set; }
        public decimal EXP_AMOUNT_15 { get; set; }
        public decimal EXP_AMOUNT_16 { get; set; }
        public decimal EXP_AMOUNT_17 { get; set; }
        public decimal EXP_AMOUNT_18 { get; set; }
        public decimal EXP_AMOUNT_19 { get; set; }
        public decimal EXP_AMOUNT_20 { get; set; }
        public decimal EXP_AMOUNT_21 { get; set; }
        public decimal EXP_AMOUNT_22 { get; set; }
        public decimal EXP_AMOUNT_23 { get; set; }
        public decimal EXP_AMOUNT_24 { get; set; }
        public decimal EXP_AMOUNT_25 { get; set; }
        public decimal EXP_AMOUNT_26 { get; set; }
        public decimal EXP_AMOUNT_27 { get; set; }
        public decimal EXP_AMOUNT_28 { get; set; }
        public decimal EXP_AMOUNT_29 { get; set; }
        public decimal EXP_AMOUNT_30 { get; set; }
        public decimal EXP_AMOUNT_31 { get; set; }
        public decimal EXP_AMOUNT_32 { get; set; }
        public decimal EXP_AMOUNT_33 { get; set; }
        public decimal EXP_AMOUNT_34 { get; set; }
        public decimal EXP_AMOUNT_35 { get; set; }
        public decimal EXP_AMOUNT_36 { get; set; }
        public decimal EXP_AMOUNT_37 { get; set; }
        public decimal EXP_AMOUNT_38 { get; set; }
        public decimal EXP_AMOUNT_39 { get; set; }
        public decimal EXP_AMOUNT_40 { get; set; }
        public decimal EXP_AMOUNT_41 { get; set; }
        public decimal EXP_AMOUNT_42 { get; set; }
        public decimal EXP_AMOUNT_43 { get; set; }
        public decimal EXP_AMOUNT_44 { get; set; }
        public decimal EXP_AMOUNT_45 { get; set; }
        public decimal EXP_AMOUNT_46 { get; set; }
        public decimal EXP_AMOUNT_47 { get; set; }
        public decimal EXP_AMOUNT_48 { get; set; }
        public decimal EXP_AMOUNT_49 { get; set; }
        public decimal EXP_AMOUNT_50 { get; set; }
        public decimal EXP_AMOUNT_51 { get; set; }
        public decimal EXP_AMOUNT_52 { get; set; }
        public decimal EXP_AMOUNT_53 { get; set; }
        public decimal EXP_AMOUNT_54 { get; set; }
        public decimal EXP_AMOUNT_55 { get; set; }
        public decimal EXP_AMOUNT_56 { get; set; }
        public decimal EXP_AMOUNT_57 { get; set; }
        public decimal EXP_AMOUNT_58 { get; set; }
        public decimal EXP_AMOUNT_59 { get; set; }
        public decimal EXP_AMOUNT_60 { get; set; }
        public decimal EXP_AMOUNT_61 { get; set; }
        public decimal EXP_AMOUNT_62 { get; set; }
        public decimal EXP_AMOUNT_63 { get; set; }
        public decimal EXP_AMOUNT_64 { get; set; }
        public decimal EXP_AMOUNT_65 { get; set; }
        public decimal EXP_AMOUNT_66 { get; set; }
        public decimal EXP_AMOUNT_67 { get; set; }
        public decimal EXP_AMOUNT_68 { get; set; }
        public decimal EXP_AMOUNT_69 { get; set; }
        public decimal EXP_AMOUNT_70 { get; set; }
        public decimal EXP_AMOUNT_71 { get; set; }
        public decimal EXP_AMOUNT_72 { get; set; }
        public decimal EXP_AMOUNT_73 { get; set; }
        public decimal EXP_AMOUNT_74 { get; set; }
        public decimal EXP_AMOUNT_75 { get; set; }
        public decimal EXP_AMOUNT_76 { get; set; }
        public decimal EXP_AMOUNT_77 { get; set; }
        public decimal EXP_AMOUNT_78 { get; set; }
        public decimal EXP_AMOUNT_79 { get; set; }
        public decimal EXP_AMOUNT_80 { get; set; }
        public decimal EXP_AMOUNT_81 { get; set; }
        public decimal EXP_AMOUNT_82 { get; set; }
        public decimal EXP_AMOUNT_83 { get; set; }
        public decimal EXP_AMOUNT_84 { get; set; }
        public decimal EXP_AMOUNT_85 { get; set; }
        public decimal EXP_AMOUNT_86 { get; set; }
        public decimal EXP_AMOUNT_87 { get; set; }
        public decimal EXP_AMOUNT_88 { get; set; }
        public decimal EXP_AMOUNT_89 { get; set; }
        public decimal EXP_AMOUNT_90 { get; set; }
        public decimal EXP_AMOUNT_91 { get; set; }
        public decimal EXP_AMOUNT_92 { get; set; }
        public decimal EXP_AMOUNT_93 { get; set; }
        public decimal EXP_AMOUNT_94 { get; set; }
        public decimal EXP_AMOUNT_95 { get; set; }
        public decimal EXP_AMOUNT_96 { get; set; }
        public decimal EXP_AMOUNT_97 { get; set; }
        public decimal EXP_AMOUNT_98 { get; set; }
        public decimal EXP_AMOUNT_99 { get; set; }
        public decimal EXP_AMOUNT_100 { get; set; }
        public decimal EXP_AMOUNT_101 { get; set; }
        public decimal EXP_AMOUNT_102 { get; set; }
        public decimal EXP_AMOUNT_103 { get; set; }
        public decimal EXP_AMOUNT_104 { get; set; }
        public decimal EXP_AMOUNT_105 { get; set; }
        public decimal EXP_AMOUNT_106 { get; set; }
        public decimal EXP_AMOUNT_107 { get; set; }
        public decimal EXP_AMOUNT_108 { get; set; }
        public decimal EXP_AMOUNT_109 { get; set; }
        public decimal EXP_AMOUNT_110 { get; set; }
        public decimal EXP_AMOUNT_111 { get; set; }
        public decimal EXP_AMOUNT_112 { get; set; }
        public decimal EXP_AMOUNT_113 { get; set; }
        public decimal EXP_AMOUNT_114 { get; set; }
        public decimal EXP_AMOUNT_115 { get; set; }
        public decimal EXP_AMOUNT_116 { get; set; }
        public decimal EXP_AMOUNT_117 { get; set; }
        public decimal EXP_AMOUNT_118 { get; set; }
        public decimal EXP_AMOUNT_119 { get; set; }
        public decimal EXP_AMOUNT_120 { get; set; }
        public decimal EXP_AMOUNT_121 { get; set; }
        public decimal EXP_AMOUNT_122 { get; set; }
        public decimal EXP_AMOUNT_123 { get; set; }
        public decimal EXP_AMOUNT_124 { get; set; }
        public decimal EXP_AMOUNT_125 { get; set; }
        public decimal EXP_AMOUNT_126 { get; set; }
        public decimal EXP_AMOUNT_127 { get; set; }
        public decimal EXP_AMOUNT_128 { get; set; }
        public decimal EXP_AMOUNT_129 { get; set; }
        public decimal EXP_AMOUNT_130 { get; set; }
        public decimal EXP_AMOUNT_131 { get; set; }
        public decimal EXP_AMOUNT_132 { get; set; }
        public decimal EXP_AMOUNT_133 { get; set; }
        public decimal EXP_AMOUNT_134 { get; set; }
        public decimal EXP_AMOUNT_135 { get; set; }
        public decimal EXP_AMOUNT_136 { get; set; }
        public decimal EXP_AMOUNT_137 { get; set; }
        public decimal EXP_AMOUNT_138 { get; set; }
        public decimal EXP_AMOUNT_139 { get; set; }
        public decimal EXP_AMOUNT_140 { get; set; }
        public decimal EXP_AMOUNT_141 { get; set; }
        public decimal EXP_AMOUNT_142 { get; set; }
        public decimal EXP_AMOUNT_143 { get; set; }
        public decimal EXP_AMOUNT_144 { get; set; }
        public decimal EXP_AMOUNT_145 { get; set; }
        public decimal EXP_AMOUNT_146 { get; set; }
        public decimal EXP_AMOUNT_147 { get; set; }
        public decimal EXP_AMOUNT_148 { get; set; }
        public decimal EXP_AMOUNT_149 { get; set; }
        public decimal EXP_AMOUNT_150 { get; set; }
        public decimal EXP_AMOUNT_151 { get; set; }
        public decimal EXP_AMOUNT_152 { get; set; }
        public decimal EXP_AMOUNT_153 { get; set; }
        public decimal EXP_AMOUNT_154 { get; set; }
        public decimal EXP_AMOUNT_155 { get; set; }
        public decimal EXP_AMOUNT_156 { get; set; }
        public decimal EXP_AMOUNT_157 { get; set; }
        public decimal EXP_AMOUNT_158 { get; set; }
        public decimal EXP_AMOUNT_159 { get; set; }
        public decimal EXP_AMOUNT_160 { get; set; }
        public decimal EXP_AMOUNT_161 { get; set; }
        public decimal EXP_AMOUNT_162 { get; set; }
        public decimal EXP_AMOUNT_163 { get; set; }
        public decimal EXP_AMOUNT_164 { get; set; }
        public decimal EXP_AMOUNT_165 { get; set; }
        public decimal EXP_AMOUNT_166 { get; set; }
        public decimal EXP_AMOUNT_167 { get; set; }
        public decimal EXP_AMOUNT_168 { get; set; }
        public decimal EXP_AMOUNT_169 { get; set; }
        public decimal EXP_AMOUNT_170 { get; set; }
        public decimal EXP_AMOUNT_171 { get; set; }
        public decimal EXP_AMOUNT_172 { get; set; }
        public decimal EXP_AMOUNT_173 { get; set; }
        public decimal EXP_AMOUNT_174 { get; set; }
        public decimal EXP_AMOUNT_175 { get; set; }
        public decimal EXP_AMOUNT_176 { get; set; }
        public decimal EXP_AMOUNT_177 { get; set; }
        public decimal EXP_AMOUNT_178 { get; set; }
        public decimal EXP_AMOUNT_179 { get; set; }
        public decimal EXP_AMOUNT_180 { get; set; }
        public decimal EXP_AMOUNT_181 { get; set; }
        public decimal EXP_AMOUNT_182 { get; set; }
        public decimal EXP_AMOUNT_183 { get; set; }
        public decimal EXP_AMOUNT_184 { get; set; }
        public decimal EXP_AMOUNT_185 { get; set; }
        public decimal EXP_AMOUNT_186 { get; set; }
        public decimal EXP_AMOUNT_187 { get; set; }
        public decimal EXP_AMOUNT_188 { get; set; }
        public decimal EXP_AMOUNT_189 { get; set; }
        public decimal EXP_AMOUNT_190 { get; set; }
        public decimal EXP_AMOUNT_191 { get; set; }
        public decimal EXP_AMOUNT_192 { get; set; }
        public decimal EXP_AMOUNT_193 { get; set; }
        public decimal EXP_AMOUNT_194 { get; set; }
        public decimal EXP_AMOUNT_195 { get; set; }
        public decimal EXP_AMOUNT_196 { get; set; }
        public decimal EXP_AMOUNT_197 { get; set; }
        public decimal EXP_AMOUNT_198 { get; set; }
        public decimal EXP_AMOUNT_199 { get; set; }
        public decimal EXP_AMOUNT_200 { get; set; }


        public decimal TH_AMOUNT_1 { get; set; }
        public decimal TH_AMOUNT_2 { get; set; }
        public decimal TH_AMOUNT_3 { get; set; }
        public decimal TH_AMOUNT_4 { get; set; }
        public decimal TH_AMOUNT_5 { get; set; }
        public decimal TH_AMOUNT_6 { get; set; }
        public decimal TH_AMOUNT_7 { get; set; }
        public decimal TH_AMOUNT_8 { get; set; }
        public decimal TH_AMOUNT_9 { get; set; }
        public decimal TH_AMOUNT_10 { get; set; }
        public decimal TH_AMOUNT_11 { get; set; }
        public decimal TH_AMOUNT_12 { get; set; }
        public decimal TH_AMOUNT_13 { get; set; }
        public decimal TH_AMOUNT_14 { get; set; }
        public decimal TH_AMOUNT_15 { get; set; }
        public decimal TH_AMOUNT_16 { get; set; }
        public decimal TH_AMOUNT_17 { get; set; }
        public decimal TH_AMOUNT_18 { get; set; }
        public decimal TH_AMOUNT_19 { get; set; }
        public decimal TH_AMOUNT_20 { get; set; }
        public decimal TH_AMOUNT_21 { get; set; }
        public decimal TH_AMOUNT_22 { get; set; }
        public decimal TH_AMOUNT_23 { get; set; }
        public decimal TH_AMOUNT_24 { get; set; }
        public decimal TH_AMOUNT_25 { get; set; }
        public decimal TH_AMOUNT_26 { get; set; }
        public decimal TH_AMOUNT_27 { get; set; }
        public decimal TH_AMOUNT_28 { get; set; }
        public decimal TH_AMOUNT_29 { get; set; }
        public decimal TH_AMOUNT_30 { get; set; }
        public decimal TH_AMOUNT_31 { get; set; }
        public decimal TH_AMOUNT_32 { get; set; }
        public decimal TH_AMOUNT_33 { get; set; }
        public decimal TH_AMOUNT_34 { get; set; }
        public decimal TH_AMOUNT_35 { get; set; }
        public decimal TH_AMOUNT_36 { get; set; }
        public decimal TH_AMOUNT_37 { get; set; }
        public decimal TH_AMOUNT_38 { get; set; }
        public decimal TH_AMOUNT_39 { get; set; }
        public decimal TH_AMOUNT_40 { get; set; }
        public decimal TH_AMOUNT_41 { get; set; }
        public decimal TH_AMOUNT_42 { get; set; }
        public decimal TH_AMOUNT_43 { get; set; }
        public decimal TH_AMOUNT_44 { get; set; }
        public decimal TH_AMOUNT_45 { get; set; }
        public decimal TH_AMOUNT_46 { get; set; }
        public decimal TH_AMOUNT_47 { get; set; }
        public decimal TH_AMOUNT_48 { get; set; }
        public decimal TH_AMOUNT_49 { get; set; }
        public decimal TH_AMOUNT_50 { get; set; }
        public decimal TH_AMOUNT_51 { get; set; }
        public decimal TH_AMOUNT_52 { get; set; }
        public decimal TH_AMOUNT_53 { get; set; }
        public decimal TH_AMOUNT_54 { get; set; }
        public decimal TH_AMOUNT_55 { get; set; }
        public decimal TH_AMOUNT_56 { get; set; }
        public decimal TH_AMOUNT_57 { get; set; }
        public decimal TH_AMOUNT_58 { get; set; }
        public decimal TH_AMOUNT_59 { get; set; }
        public decimal TH_AMOUNT_60 { get; set; }
        public decimal TH_AMOUNT_61 { get; set; }
        public decimal TH_AMOUNT_62 { get; set; }
        public decimal TH_AMOUNT_63 { get; set; }
        public decimal TH_AMOUNT_64 { get; set; }
        public decimal TH_AMOUNT_65 { get; set; }
        public decimal TH_AMOUNT_66 { get; set; }
        public decimal TH_AMOUNT_67 { get; set; }
        public decimal TH_AMOUNT_68 { get; set; }
        public decimal TH_AMOUNT_69 { get; set; }
        public decimal TH_AMOUNT_70 { get; set; }
        public decimal TH_AMOUNT_71 { get; set; }
        public decimal TH_AMOUNT_72 { get; set; }
        public decimal TH_AMOUNT_73 { get; set; }
        public decimal TH_AMOUNT_74 { get; set; }
        public decimal TH_AMOUNT_75 { get; set; }
        public decimal TH_AMOUNT_76 { get; set; }
        public decimal TH_AMOUNT_77 { get; set; }
        public decimal TH_AMOUNT_78 { get; set; }
        public decimal TH_AMOUNT_79 { get; set; }
        public decimal TH_AMOUNT_80 { get; set; }
        public decimal TH_AMOUNT_81 { get; set; }
        public decimal TH_AMOUNT_82 { get; set; }
        public decimal TH_AMOUNT_83 { get; set; }
        public decimal TH_AMOUNT_84 { get; set; }
        public decimal TH_AMOUNT_85 { get; set; }
        public decimal TH_AMOUNT_86 { get; set; }
        public decimal TH_AMOUNT_87 { get; set; }
        public decimal TH_AMOUNT_88 { get; set; }
        public decimal TH_AMOUNT_89 { get; set; }
        public decimal TH_AMOUNT_90 { get; set; }
        public decimal TH_AMOUNT_91 { get; set; }
        public decimal TH_AMOUNT_92 { get; set; }
        public decimal TH_AMOUNT_93 { get; set; }
        public decimal TH_AMOUNT_94 { get; set; }
        public decimal TH_AMOUNT_95 { get; set; }
        public decimal TH_AMOUNT_96 { get; set; }
        public decimal TH_AMOUNT_97 { get; set; }
        public decimal TH_AMOUNT_98 { get; set; }
        public decimal TH_AMOUNT_99 { get; set; }
        public decimal TH_AMOUNT_100 { get; set; }
        public decimal TH_AMOUNT_101 { get; set; }
        public decimal TH_AMOUNT_102 { get; set; }
        public decimal TH_AMOUNT_103 { get; set; }
        public decimal TH_AMOUNT_104 { get; set; }
        public decimal TH_AMOUNT_105 { get; set; }
        public decimal TH_AMOUNT_106 { get; set; }
        public decimal TH_AMOUNT_107 { get; set; }
        public decimal TH_AMOUNT_108 { get; set; }
        public decimal TH_AMOUNT_109 { get; set; }
        public decimal TH_AMOUNT_110 { get; set; }
        public decimal TH_AMOUNT_111 { get; set; }
        public decimal TH_AMOUNT_112 { get; set; }
        public decimal TH_AMOUNT_113 { get; set; }
        public decimal TH_AMOUNT_114 { get; set; }
        public decimal TH_AMOUNT_115 { get; set; }
        public decimal TH_AMOUNT_116 { get; set; }
        public decimal TH_AMOUNT_117 { get; set; }
        public decimal TH_AMOUNT_118 { get; set; }
        public decimal TH_AMOUNT_119 { get; set; }
        public decimal TH_AMOUNT_120 { get; set; }
        public decimal TH_AMOUNT_121 { get; set; }
        public decimal TH_AMOUNT_122 { get; set; }
        public decimal TH_AMOUNT_123 { get; set; }
        public decimal TH_AMOUNT_124 { get; set; }
        public decimal TH_AMOUNT_125 { get; set; }
        public decimal TH_AMOUNT_126 { get; set; }
        public decimal TH_AMOUNT_127 { get; set; }
        public decimal TH_AMOUNT_128 { get; set; }
        public decimal TH_AMOUNT_129 { get; set; }
        public decimal TH_AMOUNT_130 { get; set; }
        public decimal TH_AMOUNT_131 { get; set; }
        public decimal TH_AMOUNT_132 { get; set; }
        public decimal TH_AMOUNT_133 { get; set; }
        public decimal TH_AMOUNT_134 { get; set; }
        public decimal TH_AMOUNT_135 { get; set; }
        public decimal TH_AMOUNT_136 { get; set; }
        public decimal TH_AMOUNT_137 { get; set; }
        public decimal TH_AMOUNT_138 { get; set; }
        public decimal TH_AMOUNT_139 { get; set; }
        public decimal TH_AMOUNT_140 { get; set; }
        public decimal TH_AMOUNT_141 { get; set; }
        public decimal TH_AMOUNT_142 { get; set; }
        public decimal TH_AMOUNT_143 { get; set; }
        public decimal TH_AMOUNT_144 { get; set; }
        public decimal TH_AMOUNT_145 { get; set; }
        public decimal TH_AMOUNT_146 { get; set; }
        public decimal TH_AMOUNT_147 { get; set; }
        public decimal TH_AMOUNT_148 { get; set; }
        public decimal TH_AMOUNT_149 { get; set; }
        public decimal TH_AMOUNT_150 { get; set; }
        public decimal TH_AMOUNT_151 { get; set; }
        public decimal TH_AMOUNT_152 { get; set; }
        public decimal TH_AMOUNT_153 { get; set; }
        public decimal TH_AMOUNT_154 { get; set; }
        public decimal TH_AMOUNT_155 { get; set; }
        public decimal TH_AMOUNT_156 { get; set; }
        public decimal TH_AMOUNT_157 { get; set; }
        public decimal TH_AMOUNT_158 { get; set; }
        public decimal TH_AMOUNT_159 { get; set; }
        public decimal TH_AMOUNT_160 { get; set; }
        public decimal TH_AMOUNT_161 { get; set; }
        public decimal TH_AMOUNT_162 { get; set; }
        public decimal TH_AMOUNT_163 { get; set; }
        public decimal TH_AMOUNT_164 { get; set; }
        public decimal TH_AMOUNT_165 { get; set; }
        public decimal TH_AMOUNT_166 { get; set; }
        public decimal TH_AMOUNT_167 { get; set; }
        public decimal TH_AMOUNT_168 { get; set; }
        public decimal TH_AMOUNT_169 { get; set; }
        public decimal TH_AMOUNT_170 { get; set; }
        public decimal TH_AMOUNT_171 { get; set; }
        public decimal TH_AMOUNT_172 { get; set; }
        public decimal TH_AMOUNT_173 { get; set; }
        public decimal TH_AMOUNT_174 { get; set; }
        public decimal TH_AMOUNT_175 { get; set; }
        public decimal TH_AMOUNT_176 { get; set; }
        public decimal TH_AMOUNT_177 { get; set; }
        public decimal TH_AMOUNT_178 { get; set; }
        public decimal TH_AMOUNT_179 { get; set; }
        public decimal TH_AMOUNT_180 { get; set; }
        public decimal TH_AMOUNT_181 { get; set; }
        public decimal TH_AMOUNT_182 { get; set; }
        public decimal TH_AMOUNT_183 { get; set; }
        public decimal TH_AMOUNT_184 { get; set; }
        public decimal TH_AMOUNT_185 { get; set; }
        public decimal TH_AMOUNT_186 { get; set; }
        public decimal TH_AMOUNT_187 { get; set; }
        public decimal TH_AMOUNT_188 { get; set; }
        public decimal TH_AMOUNT_189 { get; set; }
        public decimal TH_AMOUNT_190 { get; set; }
        public decimal TH_AMOUNT_191 { get; set; }
        public decimal TH_AMOUNT_192 { get; set; }
        public decimal TH_AMOUNT_193 { get; set; }
        public decimal TH_AMOUNT_194 { get; set; }
        public decimal TH_AMOUNT_195 { get; set; }
        public decimal TH_AMOUNT_196 { get; set; }
        public decimal TH_AMOUNT_197 { get; set; }
        public decimal TH_AMOUNT_198 { get; set; }
        public decimal TH_AMOUNT_199 { get; set; }
        public decimal TH_AMOUNT_200 { get; set; }


        //public long DEPARTMENT_ID { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string BID_NUMBER { get; set; }
        public string BID_NUM_ORDER { get; set; }

        public string BID_GROUP_CODE { get; set; }

        public Dictionary<string, decimal> DIC_EXP_AMOUNT { get; set; }

        public Dictionary<string, decimal> DIC_TH_AMOUNT { get; set; }

        public string IMP_SOURCE_NAME { get; set; }

        public long IMP_SOURCE_ID { get; set; }
        public Dictionary<string, decimal> DIC_ROOM_AMOUNT { get;  set; }
        public Dictionary<string, decimal> DIC_ROOM_EXP_AMOUNT { get; set; }
        public Dictionary<string, decimal> DIC_ROOM_MOBA_AMOUNT { get; set; }
        public Dictionary<string, decimal> DIC_ROOM_TH_AMOUNT { get; set; }

        public Dictionary<string, decimal> DIC_DEPARTMENT_TH_AMOUNT { get; set; }

        public Dictionary<string, decimal> DIC_DEPARTMENT_MOBA_AMOUNT { get; set; }

        public Dictionary<string, decimal> DIC_DEPARTMENT_EXP_AMOUNT { get; set; }

        public Dictionary<string, decimal> DIC_DEPARTMENT_AMOUNT { get; set; }

        public string REQUEST_DEPARTMENT_CODE { get; set; }
        public string REQUEST_DEPARTMENT_NAME { get; set; }

        public string PACKING_TYPE_NAME { get; set; }

        public string BID_PACKAGE_CODE { get; set; }

        public string BID_YEAR { get; set; }

        public string APPROVAL_TIME_STR { get; set; }
    }


   public class DataGet
   {
       public short TYPE { get; set; }
       public decimal AMOUNT { get; set; }
       public string BID_NUMBER { get; set; }//
       public long? EXP_MEST_ID { get; set; }
       public long? EXP_MEST_TYPE_ID { get; set; }
       public long? IMP_MEST_ID { get; set; }
       public long? IMP_MEST_TYPE_ID { get; set; }
        public long? EXP_MEST_REASON_ID { get; set; }
        public long ID { get; set; }
        public decimal IMP_PRICE { get; set; }
        public decimal IMP_VAT_RATIO { get; set; }
        public long MEDI_STOCK_ID { get; set; }
        public long? MEMA_ID { get; set; }
        public long MEMA_TYPE_ID { get; set; }
        public string PACKAGE_NUMBER { get; set; }
        public decimal PRICE { get; set; }
        public long REQ_DEPARTMENT_ID { get; set; }
        public long REQ_ROOM_ID { get; set; }
        public long SERVICE_UNIT_ID { get; set; }
        public string SERVICE_UNIT_NAME { get; set; }
        public long? SUPPLIER_ID { get; set; }//nha cung cap
        public decimal TH_AMOUNT { get; set; }
        public decimal MOBA_AMOUNT { get; set; }
        public decimal VAT_RATIO { get; set; }
        public string REGISTER_NUMBER { get; set; }
        public long? EXPIRED_DATE { get; set; }

        public string SUPPLIER_NAME { get; set; }

        public long? MEDICINE_GROUP_ID { get; set; }
        public decimal EXP_EXCLUDE_AMOUNT { get; set; }

        public long IMP_SOURCE_ID { get; set; }

        public string IMP_SOURCE_NAME { get; set; }

        public string KEY_PLACE { get; set; }
        public long? CHMS_MEDI_STOCK_ID { get; set; }
        public long? TDL_TREATMENT_TYPE_ID { get; set; }
        public long? DOCUMENT_DATE { get; set; }
    }

   public class PLACE_USE
   {
       public bool IS_NOI_TRU { get; set; }
       public string KEY_PLACE { get; set; }
        public long PLACK_NUMBER { get; set; }
        public string PLACK_USE_CODE { get; set; }
        public string PLACK_USE_NAME { get; set; }
       public string MEDICINE_TYPE_CODE { get; set; }
       public string MEDICINE_TYPE_NAME { get; set; }
       public string CATEGORY_CODE { get; set; }
       public string CATEGORY_NAME { get; set; }
       public string EXP_MEST_TYPE_CODE { get; set; }
       public string MEDICINE_GROUP_CODE { get; set; }
       public string EXP_MEST_REASON_CODE { get; set; }
       public decimal AMOUNT { get; set; }
       public decimal MOBA_AMOUNT { get; set; }
       public decimal PRICE { get; set; }
       public decimal VAT_RATIO { get; set; }
       public decimal TOTAL_PRICE { get; set; }

       public decimal EXP_AMOUNT { get; set; }
       public decimal TH_AMOUNT { get; set; }

       public string IMP_SOURCE_CODE { get; set; }
       public string IMP_SOURCE_NAME { get; set; }

       public long IMP_SOURCE_ID { get; set; }

       public string SERVICE_UNIT_NAME { get; set; }
   }

}
