using MOS.EFMODEL.DataModels;
using System;
using System.Collections.Generic;
using System.Reflection;

namespace MOS.EFMODEL.Decorator
{
    public partial class DenyUpdateDecorator
    {
        private static Dictionary<Type, List<string>> properties = new Dictionary<Type, List<string>>();
        private static bool isLoaded = false;
        private static void Load()
        {
            try
            {
                if (!isLoaded)
                {
                    LoadHisAccidentHurt();
                    LoadHisAccidentHurtType();
                    LoadHisAccountBook();
                    LoadHisAcinInteractive();
                    LoadHisActiveIngredient();
                    LoadHisAwareness();
                    LoadHisBed();
                    LoadHisBedRoom();
                    LoadHisBlood();
                    LoadHisBloodRh();
                    LoadHisCacheMonitor();
                    LoadHisCard();
                    LoadHisCare();
                    LoadHisCareer();
                    LoadHisCareDetail();
                    LoadHisCareType();
                    LoadHisCaroDepartment();
                    LoadHisCashierRoom();
                    LoadHisDataStore();
                    LoadHisDbLog();
                    LoadHisDeathCause();
                    LoadHisDeathWithin();
                    LoadHisDebate();
                    LoadHisDebateUser();
                    LoadHisDepartment();
                    LoadHisDepartmentTran();
                    LoadHisDhst();
                    LoadHisDiseaseRelation();
                    LoadHisEmotionlessMethod();
                    LoadHisEmteMaterialType();
                    LoadHisEmteMedicineType();
                    LoadHisExamSereDire();
                    LoadHisExecuteRoom();
                    LoadHisExpMest();
                    LoadHisExpMestMaterial();
                    LoadHisExpMestMedicine();
                    LoadHisExpMestStt();
                    LoadHisExpMestTemplate();
                    LoadHisExpMestType();
                    LoadHisGender();
                    LoadHisHeinApproval();
                    LoadHisIcd();
                    LoadHisImpMest();
                    LoadHisImpMestMaterial();
                    LoadHisImpMestMedicine();
                    LoadHisImpMestStt();
                    LoadHisImpMestType();
                    LoadHisInfusion();
                    LoadHisKskContract();
                    LoadHisManufacturer();
                    LoadHisMaterial();
                    LoadHisMaterialBean();
                    LoadHisMaterialPaty();
                    LoadHisMaterialType();
                    LoadHisMedicine();
                    LoadHisMedicineBean();
                    LoadHisMedicineLine();
                    LoadHisMedicinePaty();
                    LoadHisMedicineType();
                    LoadHisMedicineTypeAcin();
                    LoadHisMedicineUseForm();
                    LoadHisMediReact();
                    LoadHisMediReactType();
                    LoadHisMediStock();
                    LoadHisMediStockMaty();
                    LoadHisMediStockMety();
                    LoadHisMediStockPeriod();
                    LoadHisMestPatientType();
                    LoadHisMestPeriodMate();
                    LoadHisMestPeriodMaty();
                    LoadHisMestPeriodMedi();
                    LoadHisMestPeriodMety();
                    LoadHisMestRoom();
                    LoadHisPackingType();
                    LoadHisPatient();
                    LoadHisPatientType();
                    LoadHisPatientTypeAllow();
                    LoadHisPatientTypeAlter();
                    LoadHisPayForm();
                    LoadHisPtttCatastrophe();
                    LoadHisPtttCondition();
                    LoadHisPtttGroup();
                    LoadHisPtttMethod();
                    LoadHisReceptionRoom();
                    LoadHisRemuneration();
                    LoadHisRoom();
                    LoadHisRoomType();
                    LoadHisSereServ();
                    LoadHisSereServFile();
                    LoadHisSereServPttt();
                    LoadHisSereServSuin();
                    LoadHisSereServTein();
                    LoadHisService();
                    LoadHisServiceGroup();
                    LoadHisServiceMaty();
                    LoadHisServiceMety();
                    LoadHisServicePackage();
                    LoadHisServicePaty();
                    LoadHisServiceReq();
                    LoadHisServiceReqStt();
                    LoadHisServiceReqType();
                    LoadHisServiceRoom();
                    LoadHisServiceType();
                    LoadHisServiceUnit();
                    LoadHisServSegr();
                    LoadHisSuimIndex();
                    LoadHisSuimIndexUnit();
                    LoadHisSuimSetySuin();
                    LoadHisSupplier();
                    LoadHisTestIndex();
                    LoadHisTestIndexRange();
                    LoadHisTestIndexUnit();
                    LoadHisTextLib();
                    LoadHisTracking();
                    LoadHisTransaction();
                    LoadHisTransactionType();
                    LoadHisTranPatiForm();
                    LoadHisTranPatiReason();
                    LoadHisTreatment();
                    LoadHisTreatmentBedRoom();
                    LoadHisTreatmentEndType();
                    LoadHisTreatmentLogType();
                    LoadHisTreatmentResult();
                    LoadHisTreatmentType();
                    LoadHisUserRoom();
                    LoadHisSereServReha();
                    LoadHisCareSum();
                    LoadHisInfusionSum();
                    LoadHisRehaSum();
                    LoadHisRehaTrainUnit();
                    LoadHisInvoice();
                    LoadHisInvoiceBook();
                    LoadHisUserInvoiceBook();
                    LoadHisInvoiceDetail();
                    LoadHisRehaTrain();
                    LoadHisRehaTrainType();
                    LoadHisRestRetrType();
                    LoadHisAnticipate();
                    LoadHisMilitaryRank();
                    LoadHisReportTypeCat();
                    LoadHisServiceRetyCat();
                    LoadHisEmergencyWtime();
                    LoadHisIcdGroup();
                    LoadHisExecuteGroup();
                    LoadHisSaroExro();
                    LoadHisAccidentBodyPart();
                    LoadHisAccidentCare();
                    LoadHisAccidentHelmet();
                    LoadHisAccidentLocation();
                    LoadHisAccidentPoison();
                    LoadHisAccidentResult();
                    LoadHisAccidentVehicle();
                    LoadHisBid();
                    LoadHisBidMaterialType();
                    LoadHisBidMedicineType();
                    LoadHisInvoicePrint();
                    LoadHisMestPatySub();
                    LoadHisPatientTypeSub();
                    LoadHisPatientProgram();
                    LoadHisProgram();
                    LoadHisDepositReq();
                    LoadHisBillFund();
                    LoadHisBranch();
                    LoadHisFund();
                    LoadHisExecuteRole();
                    LoadHisBedLog();
                    LoadHisBedType();
                    LoadHisEkip();
                    LoadHisEkipUser();
                    LoadHisBloodAbo();
                    LoadHisServiceFollow();
                    LoadHisBedBsty();
                    LoadHisBloodType();
                    LoadHisBloodVolume();
                    LoadHisBloodGroup();
                    LoadHisExpMestBlood();
                    LoadHisImpSource();
                    LoadHisImpMestBlood();
                    LoadHisMestPeriodBlood();
                    LoadHisMestPeriodBlty();
                    LoadHisRoomTypeModule();
                    LoadHisAnticipateBlty();
                    LoadHisBidBloodType();
                    LoadHisRegisterGate();
                    LoadHisRegisterReq();
                    LoadHisSereServTemp();
                    LoadHisBaby();
                    LoadHisBornType();
                    LoadHisBornPosition();
                    LoadHisBornResult();
                    LoadHisExamServiceTemp();
                    LoadHisSereServExt();
                    LoadHisHtu();
                    LoadHisMediReactSum();
                    LoadHisBhytBlacklist();
                    LoadHisBhytWhitelist();
                    LoadHisImpMestTypeUser();
                    LoadHisExecuteRoleUser();
                    LoadHisMestMetyDepa();
                    LoadHisServiceReqMaty();
                    LoadHisPaanLiquid();
                    LoadHisPaanPosition();
                    LoadHisIcdCm();
                    LoadHisMedicineTypeTut();
                    LoadHisBidType();
                    LoadHisExpMestReason();
                    LoadHisOweType();
                    LoadHisCashout();
                    LoadHisSereServBill();
                    LoadHisEmployee();
                    LoadHisImpMestUser();
                    LoadHisMestInveUser();
                    LoadHisMestInventory();
                    LoadHisBillGoods();
                    LoadHisMediOrg();
                    LoadHisMemaGroup();
                    LoadHisTreatmentLogging();
                    LoadHisExpMestUser();
                    LoadHisPackage();
                    LoadHisConfig();
                    LoadHisServiceReqMety();
                    LoadHisExpMestMatyReq();
                    LoadHisExpMestMetyReq();
                    LoadHisSampleRoom();
                    LoadHisSereServDeposit();
                    LoadHisExpMestBltyReq();
                    LoadHisRepayReason();
                    LoadHisMediStockImty();
                    LoadHisMediStockExty();
                    LoadHisSereServMaty();
                    LoadHisEkipTemp();
                    LoadHisEkipTempUser();
                    LoadHisRoomGroup();
                    LoadHisMachine();
                    LoadHisServiceMachine();
                    LoadHisIcdService();
                    LoadHisEquipmentSet();
                    LoadHisEquipmentSetMaty();

                    isLoaded = true;
                }
            }
            catch (Exception)
            {

            }
        }

        public static List<string> Get<RAW>()
        {
            try
            {
                Load();
                if (properties.ContainsKey(typeof(RAW)))
                {
                    return properties[typeof(RAW)];
                }
            }
            catch (Exception)
            {

            }
            return null;
        }
    }
}
