using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HIS.Desktop.Plugins.Library.PrintOtherForm.Base
{
    public class PrintType
    {
        public enum TYPE
        {
            TONG_KET_BENH_AN,
            PHIEU_PHAU_THUAT_THU_THUAT,
            PHIEU_THEO_DOI_THUOC,
            PHIEU_PHCN,
            MPS000345_PHIEU_KHAM_GAY_ME_TRUOC_MO,
            MPS000402_PHIEU_DKSD_THUOC_DVKT_NGOAI_BHYT,
            MPS000400_PHIEU_TU_VAN,
            MPS000403_CAM_KET_NAM_GIUONG_TU_NGUYEN,
            MPS000404_BAN_GIAO_BN_TRUOC_PTTT,
            MPS000405_PHIEU_KHAI_THAC_TIEN_SU_DI_UNG,
            MPS000406_PHIEU_XN_DUONG_MAU_MAO_MACH,
            MPS000407_PHIEU_KHAM_BENH_CHUYEN_KHAM_PHONG_PTTT,
            MPS000408_BANG_KIEN_AN_TOAN_PHAU_THUAT,
            MPS000409_PHIEU_SANG_LOC_DINH_DUONG_NGUOI_BENH,
            MPS000410_BENH_AN_DIEU_TRI_NGOAI_TRU_PTTT_PHONG_KHAM_PTTT,
            MPS000411_BANG_GAY_ME_HOI_SUC,
            MPS000412_BANG_TRAC_NGHIEM_CO_VA_CAM_GIAC,
            MPS000413_PHIEU_PHAU_THUAT,
            MPS000414_PHIEU_THU_THUAT,
            MPS000416_SO_KET_BENH_AN_TRUOC_PHAU_THUAT,
            MPS000417_SO_KET_BENH_AN_TRUOC_THU_THUAT,
            MPS000418_BENH_AN_NGOAI_TRU_DAY_MAT,
            MPS000419_BENH_AN_NGOAI_TRU_GLAUCOMA,
            MPS000476_CHAN_DOAN_NGUYEN_NHAN_TU_VONG
        }
    }
}
