using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MRS.Processor.Mrs00546
{
    class Mrs00546RDO
    {
        public string TDL_PATIENT_NAME { get; set; }
        public string EXP_MEST_CODE { get; set; }
        public decimal TOTAL_PRICE { get; set; }

        public decimal MEDICINE_AMOUNT_1 { get; set; }
        public decimal MEDICINE_AMOUNT_2 { get; set; }
        public decimal MEDICINE_AMOUNT_3 { get; set; }
        public decimal MEDICINE_AMOUNT_4 { get; set; }
        public decimal MEDICINE_AMOUNT_5 { get; set; }
        public decimal MEDICINE_AMOUNT_6 { get; set; }
        public decimal MEDICINE_AMOUNT_7 { get; set; }
        public decimal MEDICINE_AMOUNT_8 { get; set; }
        public decimal MEDICINE_AMOUNT_9 { get; set; }
        public decimal MEDICINE_AMOUNT_10 { get; set; }
        public decimal MEDICINE_AMOUNT_11 { get; set; }
        public decimal MEDICINE_AMOUNT_12 { get; set; }
        public decimal MEDICINE_AMOUNT_13 { get; set; }
        public decimal MEDICINE_AMOUNT_14 { get; set; }
        public decimal MEDICINE_AMOUNT_15 { get; set; }
        public decimal MEDICINE_AMOUNT_16 { get; set; }
        public decimal MEDICINE_AMOUNT_17 { get; set; }
        public decimal MEDICINE_AMOUNT_18 { get; set; }
        public decimal MEDICINE_AMOUNT_19 { get; set; }
        public decimal MEDICINE_AMOUNT_20 { get; set; }
        public decimal MEDICINE_AMOUNT_21 { get; set; }
        public decimal MEDICINE_AMOUNT_22 { get; set; }
        public decimal MEDICINE_AMOUNT_23 { get; set; }
        public decimal MEDICINE_AMOUNT_24 { get; set; }
        public decimal MEDICINE_AMOUNT_25 { get; set; }
        public decimal MEDICINE_AMOUNT_26 { get; set; }
        public decimal MEDICINE_AMOUNT_27 { get; set; }
        public decimal MEDICINE_AMOUNT_28 { get; set; }
        public decimal MEDICINE_AMOUNT_29 { get; set; }
        public decimal MEDICINE_AMOUNT_30 { get; set; }
        public decimal MEDICINE_AMOUNT_31 { get; set; }
        public decimal MEDICINE_AMOUNT_32 { get; set; }
        public decimal MEDICINE_AMOUNT_33 { get; set; }
        public decimal MEDICINE_AMOUNT_34 { get; set; }
        public decimal MEDICINE_AMOUNT_35 { get; set; }
        public decimal MEDICINE_AMOUNT_36 { get; set; }
        public decimal MEDICINE_AMOUNT_37 { get; set; }
        public decimal MEDICINE_AMOUNT_38 { get; set; }
        public decimal MEDICINE_AMOUNT_39 { get; set; }
        public decimal MEDICINE_AMOUNT_40 { get; set; }
        public decimal MEDICINE_AMOUNT_41 { get; set; }
        public decimal MEDICINE_AMOUNT_42 { get; set; }
        public decimal MEDICINE_AMOUNT_43 { get; set; }
        public decimal MEDICINE_AMOUNT_44 { get; set; }
        public decimal MEDICINE_AMOUNT_45 { get; set; }
        public decimal MEDICINE_AMOUNT_46 { get; set; }
        public decimal MEDICINE_AMOUNT_47 { get; set; }
        public decimal MEDICINE_AMOUNT_48 { get; set; }
        public decimal MEDICINE_AMOUNT_49 { get; set; }
        public decimal MEDICINE_AMOUNT_50 { get; set; }
        public decimal MEDICINE_AMOUNT_51 { get; set; }
        public decimal MEDICINE_AMOUNT_52 { get; set; }
        public decimal MEDICINE_AMOUNT_53 { get; set; }
        public decimal MEDICINE_AMOUNT_54 { get; set; }
        public decimal MEDICINE_AMOUNT_55 { get; set; }
        public decimal MEDICINE_AMOUNT_56 { get; set; }
        public decimal MEDICINE_AMOUNT_57 { get; set; }
        public decimal MEDICINE_AMOUNT_58 { get; set; }
        public decimal MEDICINE_AMOUNT_59 { get; set; }
        public decimal MEDICINE_AMOUNT_60 { get; set; }

        public long MEDICINE_TYPE_ID_1 { get; set; }
        public long MEDICINE_TYPE_ID_2 { get; set; }
        public long MEDICINE_TYPE_ID_3 { get; set; }
        public long MEDICINE_TYPE_ID_4 { get; set; }
        public long MEDICINE_TYPE_ID_5 { get; set; }
        public long MEDICINE_TYPE_ID_6 { get; set; }
        public long MEDICINE_TYPE_ID_7 { get; set; }
        public long MEDICINE_TYPE_ID_8 { get; set; }
        public long MEDICINE_TYPE_ID_9 { get; set; }
        public long MEDICINE_TYPE_ID_10 { get; set; }
        public long MEDICINE_TYPE_ID_11 { get; set; }
        public long MEDICINE_TYPE_ID_12 { get; set; }
        public long MEDICINE_TYPE_ID_13 { get; set; }
        public long MEDICINE_TYPE_ID_14 { get; set; }
        public long MEDICINE_TYPE_ID_15 { get; set; }
        public long MEDICINE_TYPE_ID_16 { get; set; }
        public long MEDICINE_TYPE_ID_17 { get; set; }
        public long MEDICINE_TYPE_ID_18 { get; set; }
        public long MEDICINE_TYPE_ID_19 { get; set; }
        public long MEDICINE_TYPE_ID_20 { get; set; }
        public long MEDICINE_TYPE_ID_21 { get; set; }
        public long MEDICINE_TYPE_ID_22 { get; set; }
        public long MEDICINE_TYPE_ID_23 { get; set; }
        public long MEDICINE_TYPE_ID_24 { get; set; }
        public long MEDICINE_TYPE_ID_25 { get; set; }
        public long MEDICINE_TYPE_ID_26 { get; set; }
        public long MEDICINE_TYPE_ID_27 { get; set; }
        public long MEDICINE_TYPE_ID_28 { get; set; }
        public long MEDICINE_TYPE_ID_29 { get; set; }
        public long MEDICINE_TYPE_ID_30 { get; set; }
        public long MEDICINE_TYPE_ID_31 { get; set; }
        public long MEDICINE_TYPE_ID_32 { get; set; }
        public long MEDICINE_TYPE_ID_33 { get; set; }
        public long MEDICINE_TYPE_ID_34 { get; set; }
        public long MEDICINE_TYPE_ID_35 { get; set; }
        public long MEDICINE_TYPE_ID_36 { get; set; }
        public long MEDICINE_TYPE_ID_37 { get; set; }
        public long MEDICINE_TYPE_ID_38 { get; set; }
        public long MEDICINE_TYPE_ID_39 { get; set; }
        public long MEDICINE_TYPE_ID_40 { get; set; }
        public long MEDICINE_TYPE_ID_41 { get; set; }
        public long MEDICINE_TYPE_ID_42 { get; set; }
        public long MEDICINE_TYPE_ID_43 { get; set; }
        public long MEDICINE_TYPE_ID_44 { get; set; }
        public long MEDICINE_TYPE_ID_45 { get; set; }
        public long MEDICINE_TYPE_ID_46 { get; set; }
        public long MEDICINE_TYPE_ID_47 { get; set; }
        public long MEDICINE_TYPE_ID_48 { get; set; }
        public long MEDICINE_TYPE_ID_49 { get; set; }
        public long MEDICINE_TYPE_ID_50 { get; set; }
        public long MEDICINE_TYPE_ID_51 { get; set; }
        public long MEDICINE_TYPE_ID_52 { get; set; }
        public long MEDICINE_TYPE_ID_53 { get; set; }
        public long MEDICINE_TYPE_ID_54 { get; set; }
        public long MEDICINE_TYPE_ID_55 { get; set; }
        public long MEDICINE_TYPE_ID_56 { get; set; }
        public long MEDICINE_TYPE_ID_57 { get; set; }
        public long MEDICINE_TYPE_ID_58 { get; set; }
        public long MEDICINE_TYPE_ID_59 { get; set; }
        public long MEDICINE_TYPE_ID_60 { get; set; }

        public string MEDICINE_TYPE_NAME_1 { get; set; }
        public string MEDICINE_TYPE_NAME_2 { get; set; }
        public string MEDICINE_TYPE_NAME_3 { get; set; }
        public string MEDICINE_TYPE_NAME_4 { get; set; }
        public string MEDICINE_TYPE_NAME_5 { get; set; }
        public string MEDICINE_TYPE_NAME_6 { get; set; }
        public string MEDICINE_TYPE_NAME_7 { get; set; }
        public string MEDICINE_TYPE_NAME_8 { get; set; }
        public string MEDICINE_TYPE_NAME_9 { get; set; }
        public string MEDICINE_TYPE_NAME_10 { get; set; }
        public string MEDICINE_TYPE_NAME_11 { get; set; }
        public string MEDICINE_TYPE_NAME_12 { get; set; }
        public string MEDICINE_TYPE_NAME_13 { get; set; }
        public string MEDICINE_TYPE_NAME_14 { get; set; }
        public string MEDICINE_TYPE_NAME_15 { get; set; }
        public string MEDICINE_TYPE_NAME_16 { get; set; }
        public string MEDICINE_TYPE_NAME_17 { get; set; }
        public string MEDICINE_TYPE_NAME_18 { get; set; }
        public string MEDICINE_TYPE_NAME_19 { get; set; }
        public string MEDICINE_TYPE_NAME_20 { get; set; }
        public string MEDICINE_TYPE_NAME_21 { get; set; }
        public string MEDICINE_TYPE_NAME_22 { get; set; }
        public string MEDICINE_TYPE_NAME_23 { get; set; }
        public string MEDICINE_TYPE_NAME_24 { get; set; }
        public string MEDICINE_TYPE_NAME_25 { get; set; }
        public string MEDICINE_TYPE_NAME_26 { get; set; }
        public string MEDICINE_TYPE_NAME_27 { get; set; }
        public string MEDICINE_TYPE_NAME_28 { get; set; }
        public string MEDICINE_TYPE_NAME_29 { get; set; }
        public string MEDICINE_TYPE_NAME_30 { get; set; }
        public string MEDICINE_TYPE_NAME_31 { get; set; }
        public string MEDICINE_TYPE_NAME_32 { get; set; }
        public string MEDICINE_TYPE_NAME_33 { get; set; }
        public string MEDICINE_TYPE_NAME_34 { get; set; }
        public string MEDICINE_TYPE_NAME_35 { get; set; }
        public string MEDICINE_TYPE_NAME_36 { get; set; }
        public string MEDICINE_TYPE_NAME_37 { get; set; }
        public string MEDICINE_TYPE_NAME_38 { get; set; }
        public string MEDICINE_TYPE_NAME_39 { get; set; }
        public string MEDICINE_TYPE_NAME_40 { get; set; }
        public string MEDICINE_TYPE_NAME_41 { get; set; }
        public string MEDICINE_TYPE_NAME_42 { get; set; }
        public string MEDICINE_TYPE_NAME_43 { get; set; }
        public string MEDICINE_TYPE_NAME_44 { get; set; }
        public string MEDICINE_TYPE_NAME_45 { get; set; }
        public string MEDICINE_TYPE_NAME_46 { get; set; }
        public string MEDICINE_TYPE_NAME_47 { get; set; }
        public string MEDICINE_TYPE_NAME_48 { get; set; }
        public string MEDICINE_TYPE_NAME_49 { get; set; }
        public string MEDICINE_TYPE_NAME_50 { get; set; }
        public string MEDICINE_TYPE_NAME_51 { get; set; }
        public string MEDICINE_TYPE_NAME_52 { get; set; }
        public string MEDICINE_TYPE_NAME_53 { get; set; }
        public string MEDICINE_TYPE_NAME_54 { get; set; }
        public string MEDICINE_TYPE_NAME_55 { get; set; }
        public string MEDICINE_TYPE_NAME_56 { get; set; }
        public string MEDICINE_TYPE_NAME_57 { get; set; }
        public string MEDICINE_TYPE_NAME_58 { get; set; }
        public string MEDICINE_TYPE_NAME_59 { get; set; }
        public string MEDICINE_TYPE_NAME_60 { get; set; }

    }
}
