using System; 
using System.Collections.Generic; 
using System.Linq; 
using System.Text; 
using System.Threading.Tasks; 

namespace MRS.Processor.Mrs00681
{
    public class Mrs00681Filter
    {
        public List<string> FILTER { get; set; }

        public List<long> ACCIDENT_RESULT_IDs { get; set; }
        public long? ACCIDENT_RESULT_ID { get; set; }
        public List<long> WORKING_SHIFT_IDs { get; set; }
        public long? WORKING_SHIFT_ID { get; set; }
        public long? YEAR { get; set; }
        public List<string> XHT { get; set; }
        public List<string> VTL { get; set; }
        public List<string> VTH { get; set; }
        public List<string> VMB { get; set; }
        public List<string> VLG { get; set; }
        public List<string> VKMS { get; set; }
        public List<string> VKMC { get; set; }
        public List<string> VBM { get; set; }
        public List<string> UMM { get; set; }
        public List<string> UKM { get; set; }
        public List<string> UHM { get; set; }
        public string TYPE_OTHER { get; set; }
        public string TYPE_02 { get; set; }
        public string TYPE_01 { get; set; }
        public bool? TRUE_FALSE { get; set; }
        public List<long> MEDI_SUPPLIER_STOCK_IDs { get; set; }
        public long? MEDI_SUPPLIER_STOCK_ID { get; set; }
        public List<long> TREATMENT_TYPE_IDs { get; set; }
        public long? TREATMENT_TYPE_ID { get; set; }
        public List<long> TREATMENT_IDs { get; set; }
        public long? TREATMENT_ID { get; set; }
        public List<long> TREATMENT_END_TYPE_IDs { get; set; }
        public string TREATMENT_CODE__EXACT { get; set; }
        public string TREATMENT_CODE { get; set; }
        public long? TREAT_PATIENT_TYPE_ID { get; set; }
        public List<long> TRANSACTION_TYPE_IDs { get; set; }
        public long? TRANSACTION_TIME_TO { get; set; }
        public long? TRANSACTION_TIME_FROM { get; set; }
        public List<long> TRAN_TREATMENT_TYPE_IDs { get; set; }
        public bool TRAN_IS_SV { get; set; }
        public bool TRAN_IS_MEDI { get; set; }
        public bool TRAN_IS_MATE { get; set; }
        public List<long> TRACKING_IDs { get; set; }
        public long? TRACKING_ID { get; set; }
        public string TNT { get; set; }
        public List<string> TKX { get; set; }
        public short? TIME_TYPE { get; set; }
        public long? TIME_TO { get; set; }
        public long? TIME_FROM { get; set; }
        public long? TIME { get; set; }
        public bool? THROW_TREATMENT_TYPE_EXAM { get; set; }
        public bool? THROW_OUTTREAT_SERVICE { get; set; }
        public string TEST_DEPARTMENT_CODEs { get; set; }
        public long? TDL_PATIENT_ID { get; set; }
        public string TB { get; set; }
        public bool? TAKE_CANCEL { get; set; }
        public List<long> SUPPLIER_IDs { get; set; }
        public long? SUPPLIER_ID { get; set; }
        public string SUIM_ROOM_CODE_7 { get; set; }
        public string SUIM_ROOM_CODE_6 { get; set; }
        public string SUIM_ROOM_CODE_5 { get; set; }
        public string SUIM_ROOM_CODE_4 { get; set; }
        public string SUIM_ROOM_CODE_3 { get; set; }
        public string SUIM_ROOM_CODE_2 { get; set; }
        public string SUIM_ROOM_CODE_1 { get; set; }
        public long? START_TIME_TO { get; set; }
        public long? START_TIME_FROM { get; set; }
        public long? SESE_PATIENT_TYPE_ID { get; set; }
        public List<long> SERVICE_TYPE_IDs { get; set; }
        public long? SERVICE_TYPE_ID { get; set; }
        public List<long> SERVICE_REQ_TYPE_IDs { get; set; }
        public long? SERVICE_REQ_TYPE_ID { get; set; }
        public List<long> SERVICE_REQ_STT_IDs { get; set; }
        public long? SERVICE_REQ_STT_ID { get; set; }
        public string SERVICE_REQ_CODE__EXACT { get; set; }
        public string SERVICE_REQ_CODE__ENDS_WITH { get; set; }
        public List<long> SERVICE_IDs { get; set; }
        public long? SERVICE_ID { get; set; }
        public long? SERVICE_GROUP_ID { get; set; }
        public List<string> SERVICE_CODE_MANY_INDEX { get; set; }
        public List<string> SERVICE_CODE_KHAMYHCTs { get; set; }
        public string SERVICE_CODE__Z { get; set; }
        public List<string> SERVICE_CODE__TRANs { get; set; }
        public List<string> SERVICE_CODE__TEETHs { get; set; }
        public string SERVICE_CODE__P { get; set; }
        public List<string> SERVICE_CODE__KHAMSKs { get; set; }
        public string SERVICE_CODE__GKSK { get; set; }
        public List<string> SERVICE_CODE__ABORTIONs { get; set; }
        public long? SERE_SERV_PATIENT_TYPE_ID { get; set; }
        public List<long> ROOM_IDs { get; set; }
        public long? ROOM_ID { get; set; }
        public string ROOM_CODEs { get; set; }
        public List<string> ROOM_CODE_KHAMYHCTs { get; set; }
        public string ROOM_CODE__SAN { get; set; }
        public List<string> ROOM_CODE__PCBs { get; set; }
        public string ROOM_CODE__CC { get; set; }
        public List<long> REQUEST_TREATMENT_TYPE_IDs { get; set; }
        public long? REQUEST_TREATMENT_TYPE_ID { get; set; }
        public List<long> REQUEST_ROOM_IDs { get; set; }
        public long? REQUEST_ROOM_ID__OR__EXECUTE_ROOM_ID { get; set; }
        public List<string> REQUEST_LOGINNAMEs { get; set; }
        public List<long> REQUEST_DEPARTMENT_IDs { get; set; }
        public long? REQUEST_DEPARTMENT_ID__OR__EXECUTE_DEPARTMENT_ID { get; set; }
        public long? REQUEST_DEPARTMENT_ID { get; set; }
        public List<long> REQ_ROOM_IDs { get; set; }
        public List<long> REQ_DEPARTMENT_IDs { get; set; }
        public long? REQ_DEPARTMENT_ID { get; set; }
        public long? REQ_DEPARMTENT_ID { get; set; }
        public string REPORT_TYPE_CODE_CATEGORY_CODE { get; set; }
        public List<long> REPORT_TYPE_CAT_IDs { get; set; }
        public long? REPORT_TYPE_CAT_ID { get; set; }
        public List<long> REHA_SUM_IDs { get; set; }
        public long? REHA_SUM_ID { get; set; }
        public List<string> QUA { get; set; }
        public long? PAY_FORM_ID { get; set; }
        public string PAY_FORM_CODE__ELE { get; set; }
        public List<long> PATIENT_TYPE_IDs { get; set; }
        public List<long> PATIENT_TYPE_ID_WITH_SERVICEs { get; set; }
        public long? PATIENT_TYPE_ID_WITH_SERVICE { get; set; }
        public long? PATIENT_TYPE_ID_WITH_CARD { get; set; }
        public long? PATIENT_TYPE_ID { get; set; }
        public string PATIENT_TYPE_CODE__KSK { get; set; }
        public string PARENT_SERVICE_CODE { get; set; }
        public List<long> PARENT_IDs { get; set; }
        public long? PARENT_ID { get; set; }
        public long? PACKAGE_ID { get; set; }
        public List<long> PAAN_POSITION_IDs { get; set; }
        public long? PAAN_POSITION_ID { get; set; }
        public List<long> PAAN_LIQUID_IDs { get; set; }
        public long? PAAN_LIQUID_ID { get; set; }
        public long? OUT_TIME_TO { get; set; }
        public long? OUT_TIME_FROM { get; set; }
        public long? OUT_DATE { get; set; }
        public string ORDER_FIELD4 { get; set; }
        public string ORDER_FIELD3 { get; set; }
        public string ORDER_FIELD2 { get; set; }
        public string ORDER_FIELD1 { get; set; }
        public string ORDER_DIRECTION4 { get; set; }
        public string ORDER_DIRECTION3 { get; set; }
        public string ORDER_DIRECTION2 { get; set; }
        public string ORDER_DIRECTION1 { get; set; }
        public string NUM_ORDER_TO { get; set; }
        public string NUM_ORDER_FROM { get; set; }
        public List<long> NOT_IN_SERVICE_REQ_TYPE_IDs { get; set; }
        public long? MONTH { get; set; }
        public List<string> MON { get; set; }
        public long? MEST_ROOM_STOCK_ID { get; set; }
        public long? MEDICINE_TYPE_ID { get; set; }
        public List<long> MEDI_STOCK_IDs { get; set; }
        public long? MEDI_STOCK_ID { get; set; }
        public long? MEDI_STOCK_CABINET_ID { get; set; }
        public List<long> MEDI_STOCK_BUSINESS_IDs { get; set; }
        public long? MEDI_ORG_ID { get; set; }
        public List<long> MEDI_BIG_STOCK_IDs { get; set; }
        public long? MATERIAL_TYPE_ID { get; set; }
        public List<long> MACHINE_IDs { get; set; }
        public long? MACHINE_ID { get; set; }
        public List<string> LOGINNAMEs { get; set; }
        public string LOGINNAME_SALE { get; set; }
        public List<string> LOGINNAME_DOCTORs { get; set; }
        public string LOGINNAME_DOCTOR { get; set; }
        public string LOGINNAME { get; set; }
        public List<string> LEO { get; set; }
        public List<string> LAC { get; set; }
        public string KEYWORD__SERVICE_REQ_CODE__TREATMENT_CODE__PATIENT_NAME { get; set; }
        public string KB2 { get; set; }
        public string KB1 { get; set; }
        public bool? IS_TREATTING { get; set; }
        public bool? IS_TREATMENT_OUT_NOT_DEPOSIT { get; set; }
        public bool? IS_TREATING_OR_FEE_LOCK { get; set; }
        public bool? IS_TREAT_IN { get; set; }
        public bool? IS_TREAT { get; set; }
        public bool? IS_TRANSACTION_TIME_OR_INTRUCTION_TIME { get; set; }
        public bool? IS_TNT { get; set; }
        public bool? IS_SUIM_7 { get; set; }
        public bool? IS_SUIM_6 { get; set; }
        public bool? IS_SUIM_5 { get; set; }
        public bool? IS_SUIM_4 { get; set; }
        public bool? IS_SUIM_3 { get; set; }
        public bool? IS_SUIM_2 { get; set; }
        public bool? IS_SUIM_1 { get; set; }
        public bool? IS_SEND_LIS { get; set; }
        public bool? IS_ROUTE { get; set; }
        public short? IS_PT_TT { get; set; }
        public bool IS_PROVINCE { get; set; }
        public bool? IS_PARENT_FINISH_TIME { get; set; }
        public short? IS_NT_NGT { get; set; }
        public bool? IS_NOT_TRANSFER { get; set; }
        public bool? IS_NOT_IN_WORKING_TIME { get; set; }
        public short? IS_NOT_GATHER_DATA { get; set; }
        public short? IS_NOT_FEE { get; set; }
        public bool? IS_NOT_BHYT { get; set; }
        public bool? IS_NOT_ACTIVE { get; set; }
        public bool? IS_NO_PAY { get; set; }
        public bool? IS_NEUR_ADDI { get; set; }
        public bool? IS_MOBA_ON_TIME { get; set; }
        public bool? IS_MERGER_SUPPLIER { get; set; }
        public bool? IS_MERGER_PRICE { get; set; }
        public bool? IS_MERGER_PACKAGE_NUMBER { get; set; }
        public bool? IS_MERGER_MEDI_STOCK { get; set; }
        public bool? IS_MERGER_EXPIRED_DATE { get; set; }
        public bool? IS_MERGER_BID_NUMBER { get; set; }
        public bool? IS_MERGE_TREATMENT { get; set; }
        public bool? IS_MERGE_STOCK { get; set; }
        public bool? IS_MERGE_EXAM_ROOM { get; set; }
        public bool? IS_MERGE_BY_SERVICE { get; set; }
        public bool? IS_MERGE { get; set; }
        public bool? IS_MEDICINE_YHCT { get; set; }
        public bool? IS_MEDICINE_TD { get; set; }
        public bool? IS_MEDICINE_OTH { get; set; }
        public bool? IS_MEDICINE_GROUP { get; set; }
        public bool? IS_MEDICINE_CPYHCT { get; set; }
        public bool? IS_MEDICINE { get; set; }
        public bool? IS_MEDI_STOCK_TYPE__BUSINESS { get; set; }
        public short? IS_MEDI_MATE_CHEM { get; set; }
        public bool? IS_MATERIAL_PRICE_EQUAL_ORIGINAL_PRICE { get; set; }
        public bool? IS_MATERIAL { get; set; }
        public short? IS_KH { get; set; }
        public bool? IS_KB { get; set; }
        public bool? IS_INTRUCTION_TIME_OR_FINISH_TIME { get; set; }
        public bool? IS_FINISH_TIME { get; set; }
        public bool? IS_FINISH { get; set; }
        public bool? IS_EXTRA { get; set; }
        public bool? IS_EXPEND { get; set; }
        public bool? IS_EXAM_INFO { get; set; }
        public bool? IS_COUNT_EXAM { get; set; }
        public bool? IS_CHEMISTRY { get; set; }
        public bool? IS_CHEMICAL_SUBSTANCE { get; set; }
        public bool? IS_CC { get; set; }
        public bool? IS_BILL_NORMAL { get; set; }
        public bool? IS_BID_NUM_ORDER_MERGE { get; set; }
        public bool? IS_BHYT { get; set; }
        public bool? IS_ALL { get; set; }
        public bool? IS_AGGR_OR_CHMS_EXP_MEST { get; set; }
        public long? INVOICE_BOOK_ID { get; set; }
        public long? INTRUCTION_TIME_TO { get; set; }
        public long? INTRUCTION_TIME_FROM { get; set; }
        public long? INTRUCTION_DATE_TO { get; set; }
        public long? INTRUCTION_DATE_FROM { get; set; }
        public long? INTRUCTION_DATE__EQUAL { get; set; }
        public long? INSTRUCT_TIME_TO { get; set; }
        public long? INSTRUCT_TIME_FROM { get; set; }
        public long? IN_TIME_TO { get; set; }
        public long? IN_TIME_FROM { get; set; }
        public long? IMP_TIME_TO { get; set; }
        public long? IMP_TIME_FROM { get; set; }
        public List<long> IMP_MEST_TYPE_IDs { get; set; }
        public long? IMP_MEST_TYPE_ID { get; set; }
        public List<long> IMP_MEDI_STOCK_IDs { get; set; }
        public long? IMP_MEDI_STOCK_ID { get; set; }
        public List<long> EXP_MEDI_STOCK_IDs { get; set; }
        public long? EXP_MEDI_STOCK_ID { get; set; }
        public string ICD_GROUP_CODE { get; set; }
        public List<string> ICD_CODE__VPs { get; set; }
        public List<string> ICD_CODE__VGs { get; set; }
        public List<string> ICD_CODE__TDs { get; set; }
        public List<string> ICD_CODE__TCs { get; set; }
        public List<string> ICD_CODE__QBs { get; set; }
        public List<string> ICD_CODE__PROCREATE_SURGs { get; set; }
        public List<string> ICD_CODE__PROCREATE_FX_GHs { get; set; }
        public List<string> ICD_CODE__PROCREATE_EARLYs { get; set; }
        public List<string> ICD_CODE__PROCREATE_DIFFICULTs { get; set; }
        public List<string> ICD_CODE__PROCREATE_COMMONs { get; set; }
        public List<string> ICD_CODE__LTs { get; set; }
        public List<string> ICD_CODE__LAs { get; set; }
        public List<string> ICD_CODE__HHTs { get; set; }
        public List<string> ICD_CODE__GYNECOLOGICALs { get; set; }
        public List<string> ICD_CODE__GYNECOLOGICAL_SURGs { get; set; }
        public List<string> ICD_CODE__CUs { get; set; }
        public List<string> ICD_CODE__ADs { get; set; }
        public string ICD_CODE { get; set; }
        public long? HEIN_LOCK_TIME_TO { get; set; }
        public long? HEIN_LOCK_TIME_FROM { get; set; }
        public bool? HAS_ZERO_TOTAL_PRICE { get; set; }
        public bool? HAS_TRANSACTION { get; set; }
        public bool? HAS_RESULT { get; set; }
        public bool? HAS_NOT_DONE { get; set; }
        public bool? HAS_NOT_BILL { get; set; }
        public bool? HAS_EXPEND { get; set; }
        public bool? HAS_EXECUTE { get; set; }
        public bool? HAS_BILL_OR_BHYT { get; set; }
        public bool? HAS_BILL { get; set; }
        public string H_OTHER { get; set; }
        public string H_02 { get; set; }
        public string H_01 { get; set; }
        public List<string> GLU { get; set; }
        public long? GENDER_ID { get; set; }
        public long? FUND_ID { get; set; }
        public long? FIRST_DEPARTMENT_ID { get; set; }
        public long? FINISH_TIME_TO { get; set; }
        public long? FINISH_TIME_FROM { get; set; }
        public long? FEE_LOCK_TIME_TO { get; set; }
        public long? FEE_LOCK_TIME_FROM { get; set; }
        public long? EXPIRED_TIME_TO { get; set; }
        public long? EXPIRED_TIME_FROM { get; set; }
        public long? EXP_TIME_TO { get; set; }
        public long? EXP_TIME_FROM { get; set; }
        public List<long> EXP_MEST_TYPE_IDs { get; set; }
        public long? EXP_MEST_TYPE_ID { get; set; }
        public long? EXP_MEST_STT_ID { get; set; }
        public List<long> EXP_MEST_REASON_IDs { get; set; }
        public string EXP_LOGINNAME { get; set; }
        public List<long> EXECUTE_ROOM_IDs { get; set; }
        public long? EXECUTE_ROOM_ID { get; set; }
        public List<string> EXECUTE_LOGINNAMEs { get; set; }
        public long? EXECUTE_GROUP_ID { get; set; }
        public List<long> EXECUTE_DEPARTMENT_IDs { get; set; }
        public long? EXECUTE_DEPARTMENT_ID { get; set; }
        public long? EXECUTE_DEPARRTMENT_ID { get; set; }
        public List<long> EXE_ROOM_IDs { get; set; }
        public long? EXE_ROOM_ID { get; set; }
        public long? EXE_DEPARMTENT_ID { get; set; }
        public long? EXAM_TIME_TO { get; set; }
        public long? EXAM_TIME_FROM { get; set; }
        public List<long> EXAM_ROOM_IDs { get; set; }
        public List<long> EXACT_PARENT_SERVICE_IDs { get; set; }
        public List<long> EXACT_EXECUTE_ROOM_IDs__REQ { get; set; }
        public List<long> EXACT_EXECUTE_ROOM_IDs { get; set; }
        public long? EXACT_EXECUTE_ROOM_ID__EXE { get; set; }
        public long? EXACT_EXECUTE_ROOM_ID { get; set; }
        public List<long> EXACT_CASHIER_ROOM_IDs { get; set; }
        public long? EXACT_CASHIER_ROOM_ID { get; set; }
        public long? EXACT_BED_ROOM_ID { get; set; }
        public List<long> END_DEPARTMENT_IDs { get; set; }
        public long? END_DEPARTMENT_ID { get; set; }
        public List<string> DVK { get; set; }
        public List<string> DVG { get; set; }
        public string DV { get; set; }
        public List<string> DTT { get; set; }
        public long? DOCUMENT_DATE_TO { get; set; }
        public long? DOCUMENT_DATE_FROM { get; set; }
        public List<string> DISTRICT_CODEs { get; set; }
        public List<long> DHST_IDs { get; set; }
        public long? DHST_ID { get; set; }
        public List<long> DEPARTMENT_IDs { get; set; }
        public long? DEPARTMENT_ID { get; set; }
        public string DEPARTMENT_CODEs { get; set; }
        public string DEPARTMENT_CODE__OUTPATIENTs { get; set; }
        public string DEPARTMENT_CODE__KKB { get; set; }
        public string DEPARTMENT_CODE__KCCs { get; set; }
        public List<string> DEATH_CAUSE__LATE { get; set; }
        public List<string> DEATH_CAUSE__HEAVY { get; set; }
        public List<string> DEATH_CAUSE__EMERGENCY { get; set; }
        public long? DATE_TO { get; set; }
        public long? DATE_TIME_TO { get; set; }
        public long? DATE_TIME_FROM { get; set; }
        public long? DATE_FROM { get; set; }
        public long? DATE { get; set; }
        public List<long> CURRENTBRANCH_MEDI_STOCK_IDs { get; set; }
        public List<string> CTM { get; set; }
        public string CS { get; set; }
        public string CREATOR_LOGINNAME { get; set; }
        public long? CREATE_TIME_TO { get; set; }
        public long? CREATE_TIME_FROM { get; set; }
        public long? CREATE_TIME { get; set; }
        public List<string> CLN_MEDI_STOCK_CODEs { get; set; }
        public long? CLINICAL_IN_TIME_TO { get; set; }
        public long? CLINICAL_IN_TIME_FROM { get; set; }
        public long? CLINICAL_DEPARTMENT_ID { get; set; }
        public List<string> CLINICAL_DEPARTMENT_CODEs { get; set; }
        public long? CHOOSE_TIME_FILTER { get; set; }
        public bool? CHOOSE_TIME { get; set; }
        public bool? CHOOSE_DEPARTMENT { get; set; }
        public List<string> CHA { get; set; }
        public string CC { get; set; }
        public string CATEGORY_CODEs { get; set; }
        public string CATEGORY_CODE__XRAY { get; set; }
        public string CATEGORY_CODE__XQ { get; set; }
        public string CATEGORY_CODE__XHH { get; set; }
        public string CATEGORY_CODE__VS { get; set; }
        public string CATEGORY_CODE__VCM { get; set; }
        public string CATEGORY_CODE__SURG { get; set; }
        public string CATEGORY_CODE__SU_M { get; set; }
        public string CATEGORY_CODE__SU_E { get; set; }
        public string CATEGORY_CODE__SH { get; set; }
        public string CATEGORY_CODE__PTLT { get; set; }
        public string CATEGORY_CODE__OXY { get; set; }
        public string CATEGORY_CODE__NT { get; set; }
        public string CATEGORY_CODE__NORMAL { get; set; }
        public string CATEGORY_CODE__MRI { get; set; }
        public List<string> CATEGORY_CODE__KSKs { get; set; }
        public string CATEGORY_CODE__KHAC { get; set; }
        public string CATEGORY_CODE__HH { get; set; }
        public string CATEGORY_CODE__HARD { get; set; }
        public string CATEGORY_CODE__GP { get; set; }
        public string CATEGORY_CODE__EEG { get; set; }
        public string CATEGORY_CODE__ECG { get; set; }
        public string CATEGORY_CODE__DC { get; set; }
        public string CATEGORY_CODE__CT { get; set; }
        public string CATEGORY_CODE__CERVICAL_ENDO { get; set; }
        public string CATEGORY_CODE__BRAIN_BLOOD { get; set; }
        public string CATEGORY_CODE__BRAIN { get; set; }
        public string CATEGORY_CODE__BONE_DENSITY { get; set; }
        public List<string> CASHIER_LOGINNAMEs { get; set; }
        public string CASHIER_LOGINNAME { get; set; }
        public string CANCEL_LOGINNAME { get; set; }
        public List<long> BRANCH_IDs { get; set; }
        public long? BRANCH_ID { get; set; }
        public List<string> BON { get; set; }
        public bool BLOOD_IS_SV { get; set; }
        public bool BLOOD_IS_MEDI { get; set; }
        public bool BLOOD_IS_MATE { get; set; }
        public bool BLOOD_IS_GENERIC_MEDI { get; set; }
        public List<long> BID_IDs { get; set; }
        public long? BID_ID { get; set; }
        public long? BED_ID { get; set; }
        public List<string> BDM { get; set; }
        public string BARCODE__EXACT { get; set; }
        public List<string> ADDRESS_EMPLOYEEs { get; set; }
        public bool? ADD_SALE { get; set; }
        public string ACTIVE_INGR_BHYT { get; set; }
        public List<long> ACCOUNT_BOOK_IDs { get; set; }
        public long? ACCOUNT_BOOK_ID { get; set; }
        public long? ACCIDENT_HURT_TYPE_ID { get; set; }
        public List<string> ACCIDENT_BODY_PART_CODE__SOFT { get; set; }
        public List<string> ACCIDENT_BODY_PART_CODE__MULTI { get; set; }
        public List<string> ACCIDENT_BODY_PART_CODE__BRAIN { get; set; }
        public List<string> ACCIDENT_BODY_PART_CODE__BONE { get; set; }
        public List<long> KSK_CONTRACT_IDs { get; set; }
        public long? KSK_CONTRACT_ID { get; set; }
    }
}
