//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACS_MODULE_GROUP
    {
        public ACS_MODULE_GROUP()
        {
            this.ACS_MODULE = new HashSet<ACS_MODULE>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string MODULE_GROUP_CODE { get; set; }
        public string MODULE_GROUP_NAME { get; set; }
        public Nullable<long> NUM_ORDER { get; set; }
        public string ICON_LINK { get; set; }
    
        public virtual ICollection<ACS_MODULE> ACS_MODULE { get; set; }
    }
}
