//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACS_ROLE
    {
        public ACS_ROLE()
        {
            this.ACS_APPLICATION_ROLE = new HashSet<ACS_APPLICATION_ROLE>();
            this.ACS_CONTROL_ROLE = new HashSet<ACS_CONTROL_ROLE>();
            this.ACS_MODULE_ROLE = new HashSet<ACS_MODULE_ROLE>();
            this.ACS_ROLE_BASE = new HashSet<ACS_ROLE_BASE>();
            this.ACS_ROLE_BASE1 = new HashSet<ACS_ROLE_BASE>();
            this.ACS_ROLE_USER = new HashSet<ACS_ROLE_USER>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string ROLE_CODE { get; set; }
        public string ROLE_NAME { get; set; }
        public Nullable<short> IS_FULL { get; set; }
    
        public virtual ICollection<ACS_APPLICATION_ROLE> ACS_APPLICATION_ROLE { get; set; }
        public virtual ICollection<ACS_CONTROL_ROLE> ACS_CONTROL_ROLE { get; set; }
        public virtual ICollection<ACS_MODULE_ROLE> ACS_MODULE_ROLE { get; set; }
        public virtual ICollection<ACS_ROLE_BASE> ACS_ROLE_BASE { get; set; }
        public virtual ICollection<ACS_ROLE_BASE> ACS_ROLE_BASE1 { get; set; }
        public virtual ICollection<ACS_ROLE_USER> ACS_ROLE_USER { get; set; }
    }
}
