//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_HIS_TREATMENT_BED_ROOM_1
    {
        public long DEPARTMENT_ID { get; set; }
        public Nullable<decimal> PATIENT_COUNT { get; set; }
    }
}
