//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_HIS_EXP_MEST_DETAIL_1
    {
        public long ID { get; set; }
        public long EXP_MEST_TYPE_ID { get; set; }
        public long MEDI_STOCK_ID { get; set; }
        public string EXP_MEST_CODE { get; set; }
        public Nullable<long> BILL_ID { get; set; }
        public Nullable<long> DEBT_ID { get; set; }
        public string TDL_TREATMENT_CODE { get; set; }
        public string TDL_PATIENT_CODE { get; set; }
        public string TDL_PATIENT_NAME { get; set; }
        public string TDL_PATIENT_GENDER_NAME { get; set; }
        public Nullable<long> TDL_PATIENT_DOB { get; set; }
        public Nullable<short> TDL_PATIENT_IS_HAS_NOT_DAY_DOB { get; set; }
        public string TDL_PATIENT_ADDRESS { get; set; }
        public Nullable<long> EXP_MEST_ID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> VIR_PRICE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> VAT_RATIO { get; set; }
        public Nullable<long> TYPE_ID { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<long> TDL_SERVICE_UNIT_ID { get; set; }
        public string SERVICE_UNIT_NAME { get; set; }
        public Nullable<decimal> IS_MEDICINE { get; set; }
    }
}
