//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_HIS_MEDI_STOCK_1
    {
        public Nullable<long> ID { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public string MEDICINE_TYPE_CODE { get; set; }
        public string MEDICINE_TYPE_NAME { get; set; }
        public Nullable<long> SERVICE_ID { get; set; }
        public Nullable<long> MANUFACTURER_ID { get; set; }
        public Nullable<decimal> ALERT_MIN_IN_STOCK { get; set; }
        public Nullable<decimal> MEDICINE_USE_FORM_ID { get; set; }
        public string TUTORIAL { get; set; }
        public string NATIONAL_NAME { get; set; }
        public string CONCENTRA { get; set; }
        public Nullable<decimal> USE_ON_DAY { get; set; }
        public Nullable<decimal> IS_STAR_MARK { get; set; }
        public string ACTIVE_INGR_BHYT_CODE { get; set; }
        public string ACTIVE_INGR_BHYT_NAME { get; set; }
        public Nullable<decimal> ALERT_MAX_IN_TREATMENT { get; set; }
        public Nullable<decimal> IS_STENT { get; set; }
        public Nullable<decimal> ALERT_MAX_IN_PRESCRIPTION { get; set; }
        public Nullable<decimal> IS_VACCINE { get; set; }
        public Nullable<decimal> RANK { get; set; }
        public Nullable<decimal> IMP_PRICE { get; set; }
        public Nullable<decimal> IMP_VAT_RATIO { get; set; }
        public Nullable<decimal> IS_REUSABLE { get; set; }
        public Nullable<decimal> LAST_EXP_PRICE { get; set; }
        public Nullable<decimal> LAST_EXP_VAT_RATIO { get; set; }
        public string CONTRAINDICATION { get; set; }
        public Nullable<decimal> MATERIAL_TYPE_MAP_ID { get; set; }
        public Nullable<long> PARENT_ID { get; set; }
        public string MANUFACTURER_CODE { get; set; }
        public string MANUFACTURER_NAME { get; set; }
        public string MEDI_STOCK_CODE { get; set; }
        public string MEDI_STOCK_NAME { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<long> MEDI_STOCK_ID { get; set; }
        public Nullable<decimal> SERVICE_TYPE_ID { get; set; }
        public Nullable<decimal> IS_CHEMICAL_SUBSTANCE { get; set; }
        public Nullable<short> IS_AUTO_EXPEND { get; set; }
        public string PARENT_CODE { get; set; }
        public string PARENT_NAME { get; set; }
        public long SERVICE_UNIT_ID { get; set; }
        public Nullable<long> HEIN_SERVICE_TYPE_ID { get; set; }
        public Nullable<short> IS_OUT_PARENT_FEE { get; set; }
        public Nullable<long> GENDER_ID { get; set; }
        public Nullable<long> OTHER_PAY_SOURCE_ID { get; set; }
        public string OTHER_PAY_SOURCE_ICDS { get; set; }
        public string SERVICE_UNIT_CODE { get; set; }
        public string SERVICE_UNIT_NAME { get; set; }
        public Nullable<decimal> CONVERT_RATIO { get; set; }
        public string CONVERT_UNIT_CODE { get; set; }
        public string CONVERT_UNIT_NAME { get; set; }
    }
}
