//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_SKIN_SURGERY_DESC
    {
        public HIS_SKIN_SURGERY_DESC()
        {
            this.HIS_SERE_SERV_PTTT = new HashSet<HIS_SERE_SERV_PTTT>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string DAMAGE { get; set; }
        public string DAMAGE_POSITION { get; set; }
        public Nullable<long> DAMAGE_AMOUNT { get; set; }
        public Nullable<long> DAMAGE_TREAT_CUTTING_TYPE { get; set; }
        public Nullable<long> DAMAGE_TREAT_SHAPING_TYPE { get; set; }
        public Nullable<long> DAMAGE_TREAT_CLOSING_TYPE { get; set; }
        public string DAMAGE_TREAT_OTHER { get; set; }
    
        public virtual ICollection<HIS_SERE_SERV_PTTT> HIS_SERE_SERV_PTTT { get; set; }
    }
}
