//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_BED
    {
        public HIS_BED()
        {
            this.HIS_BED_BSTY = new HashSet<HIS_BED_BSTY>();
            this.HIS_BED_LOG = new HashSet<HIS_BED_LOG>();
            this.HIS_TREATMENT_BED_ROOM = new HashSet<HIS_TREATMENT_BED_ROOM>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string BED_CODE { get; set; }
        public string BED_NAME { get; set; }
        public long BED_ROOM_ID { get; set; }
        public long BED_TYPE_ID { get; set; }
        public Nullable<long> MAX_CAPACITY { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public Nullable<long> TREATMENT_ROOM_ID { get; set; }
    
        public virtual ICollection<HIS_BED_BSTY> HIS_BED_BSTY { get; set; }
        public virtual HIS_BED_ROOM HIS_BED_ROOM { get; set; }
        public virtual HIS_BED_TYPE HIS_BED_TYPE { get; set; }
        public virtual HIS_TREATMENT_ROOM HIS_TREATMENT_ROOM { get; set; }
        public virtual ICollection<HIS_BED_LOG> HIS_BED_LOG { get; set; }
        public virtual ICollection<HIS_TREATMENT_BED_ROOM> HIS_TREATMENT_BED_ROOM { get; set; }
    }
}
