//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_TEST_INDEX_RANGE
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long TEST_INDEX_ID { get; set; }
        public string MIN_VALUE { get; set; }
        public string MAX_VALUE { get; set; }
        public Nullable<short> IS_MALE { get; set; }
        public Nullable<short> IS_FEMALE { get; set; }
        public Nullable<long> AGE_FROM { get; set; }
        public Nullable<long> AGE_TO { get; set; }
        public string NORMAL_VALUE { get; set; }
        public Nullable<short> IS_ACCEPT_EQUAL_MIN { get; set; }
        public Nullable<short> IS_ACCEPT_EQUAL_MAX { get; set; }
        public string WARNING_MIN_VALUE { get; set; }
        public string WARNING_MAX_VALUE { get; set; }
        public Nullable<short> IS_ACCEPT_EQUAL_WARNING_MIN { get; set; }
        public Nullable<short> IS_ACCEPT_EQUAL_WARNING_MAX { get; set; }
        public Nullable<long> AGE_TYPE_ID { get; set; }
    
        public virtual HIS_AGE_TYPE HIS_AGE_TYPE { get; set; }
        public virtual HIS_TEST_INDEX HIS_TEST_INDEX { get; set; }
    }
}
