//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_PROGRAM
    {
        public HIS_PROGRAM()
        {
            this.HIS_MEDI_RECORD = new HashSet<HIS_MEDI_RECORD>();
            this.HIS_PATIENT_PROGRAM = new HashSet<HIS_PATIENT_PROGRAM>();
            this.HIS_TREATMENT = new HashSet<HIS_TREATMENT>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string PROGRAM_CODE { get; set; }
        public string PROGRAM_NAME { get; set; }
        public Nullable<long> DATA_STORE_ID { get; set; }
        public Nullable<long> TREATMENT_TYPE_ID { get; set; }
        public Nullable<short> AUTO_CHANGE_TO_OUT_PATIENT { get; set; }
    
        public virtual HIS_DATA_STORE HIS_DATA_STORE { get; set; }
        public virtual ICollection<HIS_MEDI_RECORD> HIS_MEDI_RECORD { get; set; }
        public virtual ICollection<HIS_PATIENT_PROGRAM> HIS_PATIENT_PROGRAM { get; set; }
        public virtual HIS_TREATMENT_TYPE HIS_TREATMENT_TYPE { get; set; }
        public virtual ICollection<HIS_TREATMENT> HIS_TREATMENT { get; set; }
    }
}
