//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_SERE_SERV_FILE
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string SERE_SERV_FILE_NAME { get; set; }
        public long SERE_SERV_ID { get; set; }
        public string URL { get; set; }
        public string DESCRIPTION { get; set; }
        public string CAPTION { get; set; }
        public Nullable<long> BODY_PART_ID { get; set; }
    
        public virtual HIS_BODY_PART HIS_BODY_PART { get; set; }
        public virtual HIS_SERE_SERV HIS_SERE_SERV { get; set; }
    }
}
