//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_BABY
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long TREATMENT_ID { get; set; }
        public string BABY_NAME { get; set; }
        public Nullable<long> GENDER_ID { get; set; }
        public Nullable<long> BORN_TYPE_ID { get; set; }
        public Nullable<long> BORN_RESULT_ID { get; set; }
        public Nullable<long> BORN_POSITION_ID { get; set; }
        public Nullable<long> BORN_TIME { get; set; }
        public Nullable<long> BABY_ORDER { get; set; }
        public Nullable<long> MONTH_COUNT { get; set; }
        public Nullable<long> WEEK_COUNT { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> HEAD { get; set; }
        public string MIDWIFE { get; set; }
        public string FATHER_NAME { get; set; }
        public string ETHNIC_CODE { get; set; }
        public string ETHNIC_NAME { get; set; }
        public Nullable<long> BIRTH_CERT_NUM { get; set; }
        public Nullable<long> BIRTH_CERT_BOOK_ID { get; set; }
        public string ISSUER_LOGINNAME { get; set; }
        public string ISSUER_USERNAME { get; set; }
        public Nullable<long> CURRENT_ALIVE { get; set; }
        public Nullable<long> NUMBER_OF_PREGNANCIES { get; set; }
        public Nullable<short> IS_DIFFICULT_BIRTH { get; set; }
        public Nullable<short> IS_HAEMORRHAGE { get; set; }
        public Nullable<short> IS_UTERINE_RUPTURE { get; set; }
        public Nullable<short> IS_PUERPERAL { get; set; }
        public Nullable<short> IS_BACTERIAL_CONTAMINATION { get; set; }
        public Nullable<short> IS_TETANUS { get; set; }
        public Nullable<short> IS_MOTHER_DEATH { get; set; }
        public string BIRTHPLACE { get; set; }
        public Nullable<short> IS_FETAL_DEATH_22_WEEKS { get; set; }
        public Nullable<short> IS_INJECT_K1 { get; set; }
        public Nullable<short> IS_INJECT_B { get; set; }
        public Nullable<long> POSTPARTUM_CARE { get; set; }
        public string METHOD_STYLE { get; set; }
        public string NOTE { get; set; }
        public Nullable<long> DEATH_DATE { get; set; }
        public string HEIN_CARD_NUMBER_TMP { get; set; }
        public Nullable<long> DEPARTMENT_ID { get; set; }
        public Nullable<short> IS_SURGERY { get; set; }
        public Nullable<long> NUMBER_CHILDREN_BIRTH { get; set; }
        public string SYNC_FAILD_REASON { get; set; }
        public Nullable<long> SYNC_RESULT_TYPE { get; set; }
        public Nullable<long> SYNC_TIME { get; set; }
        public Nullable<long> ISSUED_DATE { get; set; }
        public Nullable<short> BIRTHPLACE_TYPE { get; set; }
        public string BIRTH_PROVINCE_CODE { get; set; }
        public string BIRTH_PROVINCE_NAME { get; set; }
        public string BIRTH_DISTRICT_CODE { get; set; }
        public string BIRTH_DISTRICT_NAME { get; set; }
        public string BIRTH_COMMUNE_CODE { get; set; }
        public string BIRTH_COMMUNE_NAME { get; set; }
        public string BIRTH_HOSPITAL_CODE { get; set; }
        public string BIRTH_HOSPITAL_NAME { get; set; }
    
        public virtual HIS_TREATMENT HIS_TREATMENT { get; set; }
        public virtual HIS_GENDER HIS_GENDER { get; set; }
        public virtual HIS_BORN_TYPE HIS_BORN_TYPE { get; set; }
        public virtual HIS_BORN_RESULT HIS_BORN_RESULT { get; set; }
        public virtual HIS_BORN_POSITION HIS_BORN_POSITION { get; set; }
        public virtual HIS_BIRTH_CERT_BOOK HIS_BIRTH_CERT_BOOK { get; set; }
    }
}
