//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_INTERACTIVE_GRADE
    {
        public HIS_INTERACTIVE_GRADE()
        {
            this.HIS_ACIN_INTERACTIVE = new HashSet<HIS_ACIN_INTERACTIVE>();
            this.HIS_MEDICINE_INTERACTIVE = new HashSet<HIS_MEDICINE_INTERACTIVE>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long INTERACTIVE_GRADE { get; set; }
        public string INTERACTIVE_GRADE_NAME { get; set; }
    
        public virtual ICollection<HIS_ACIN_INTERACTIVE> HIS_ACIN_INTERACTIVE { get; set; }
        public virtual ICollection<HIS_MEDICINE_INTERACTIVE> HIS_MEDICINE_INTERACTIVE { get; set; }
    }
}
