//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_SERVICE_REQ_METY
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long SERVICE_REQ_ID { get; set; }
        public Nullable<long> MEDICINE_TYPE_ID { get; set; }
        public string MEDICINE_TYPE_NAME { get; set; }
        public string UNIT_NAME { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<long> NUM_ORDER { get; set; }
        public string TUTORIAL { get; set; }
        public Nullable<long> MEDICINE_USE_FORM_ID { get; set; }
        public Nullable<long> USE_TIME_TO { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> SPEED { get; set; }
        public Nullable<long> DAY_COUNT { get; set; }
        public string MORNING { get; set; }
        public string NOON { get; set; }
        public string AFTERNOON { get; set; }
        public string EVENING { get; set; }
        public Nullable<long> HTU_ID { get; set; }
        public Nullable<short> IS_SUB_PRES { get; set; }
        public long TDL_TREATMENT_ID { get; set; }
        public Nullable<decimal> PRES_AMOUNT { get; set; }
        public Nullable<long> PREVIOUS_USING_COUNT { get; set; }
        public string EXCEED_LIMIT_IN_PRES_REASON { get; set; }
        public string EXCEED_LIMIT_IN_DAY_REASON { get; set; }
        public string ODD_PRES_REASON { get; set; }
        public string OVER_RESULT_TEST_REASON { get; set; }
        public string OVER_KIDNEY_REASON { get; set; }
    
        public virtual HIS_MEDICINE_TYPE HIS_MEDICINE_TYPE { get; set; }
        public virtual HIS_MEDICINE_USE_FORM HIS_MEDICINE_USE_FORM { get; set; }
        public virtual HIS_SERVICE_REQ HIS_SERVICE_REQ { get; set; }
    }
}
