//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_MR_CHECK_SUMMARY
    {
        public HIS_MR_CHECK_SUMMARY()
        {
            this.HIS_MR_CHECKLIST = new HashSet<HIS_MR_CHECKLIST>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public Nullable<long> ERROR_NUMBER { get; set; }
        public Nullable<long> DEPARTMENT_RETURN_DATE { get; set; }
        public string DEPARTMENT_USER_NAME { get; set; }
        public string DEPARTMENT_LOGIN_NAME { get; set; }
        public Nullable<long> KHTH_RETURN_DATE { get; set; }
        public string KHTH_USER_NAME { get; set; }
        public string KHTH_LOGIN_NAME { get; set; }
        public long DEPARTMENT_ID { get; set; }
        public long TREATMENT_ID { get; set; }
        public Nullable<long> MEDI_RECORD_SUBMIT_DATE { get; set; }
        public Nullable<long> LATE_DATE_NUMBER { get; set; }
        public Nullable<short> IS_APPROVED { get; set; }
        public Nullable<short> CHECK_PLACE { get; set; }
    
        public virtual HIS_DEPARTMENT HIS_DEPARTMENT { get; set; }
        public virtual HIS_TREATMENT HIS_TREATMENT { get; set; }
        public virtual ICollection<HIS_MR_CHECKLIST> HIS_MR_CHECKLIST { get; set; }
    }
}
