//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_LICENSE_CLASS
    {
        public HIS_LICENSE_CLASS()
        {
            this.HIS_KSK_PERIOD_DRIVER = new HashSet<HIS_KSK_PERIOD_DRIVER>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string LICENSE_CLASS_CODE { get; set; }
        public string LICENSE_CLASS_NAME { get; set; }
    
        public virtual ICollection<HIS_KSK_PERIOD_DRIVER> HIS_KSK_PERIOD_DRIVER { get; set; }
    }
}
