//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_INVOICE_BOOK
    {
        public HIS_INVOICE_BOOK()
        {
            this.HIS_INVOICE = new HashSet<HIS_INVOICE>();
            this.HIS_INVOICE_BOOK1 = new HashSet<HIS_INVOICE_BOOK>();
            this.HIS_USER_INVOICE_BOOK = new HashSet<HIS_USER_INVOICE_BOOK>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long TOTAL { get; set; }
        public long FROM_NUM_ORDER { get; set; }
        public string DESCRIPTION { get; set; }
        public string TEMPLATE_CODE { get; set; }
        public string SYMBOL_CODE { get; set; }
        public string INVOICE_BOOK_NAME { get; set; }
        public Nullable<long> RELEASE_TIME { get; set; }
        public Nullable<long> LINK_ID { get; set; }
    
        public virtual ICollection<HIS_INVOICE> HIS_INVOICE { get; set; }
        public virtual ICollection<HIS_INVOICE_BOOK> HIS_INVOICE_BOOK1 { get; set; }
        public virtual HIS_INVOICE_BOOK HIS_INVOICE_BOOK2 { get; set; }
        public virtual ICollection<HIS_USER_INVOICE_BOOK> HIS_USER_INVOICE_BOOK { get; set; }
    }
}
