//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_FILM_SIZE
    {
        public HIS_FILM_SIZE()
        {
            this.HIS_MATERIAL_TYPE = new HashSet<HIS_MATERIAL_TYPE>();
            this.HIS_SERE_SERV_EXT = new HashSet<HIS_SERE_SERV_EXT>();
            this.HIS_SERVICE = new HashSet<HIS_SERVICE>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string FILM_SIZE_NAME { get; set; }
        public string FILM_SIZE_CODE { get; set; }
    
        public virtual ICollection<HIS_MATERIAL_TYPE> HIS_MATERIAL_TYPE { get; set; }
        public virtual ICollection<HIS_SERE_SERV_EXT> HIS_SERE_SERV_EXT { get; set; }
        public virtual ICollection<HIS_SERVICE> HIS_SERVICE { get; set; }
    }
}
