//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_EXPIRED_DATE_CFG
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public Nullable<long> LIFESPAN_MONTH_FROM { get; set; }
        public Nullable<long> LIFESPAN_MONTH_TO { get; set; }
        public Nullable<long> IS_MATERIAL { get; set; }
        public Nullable<long> EXPIRED_DAY { get; set; }
        public Nullable<decimal> EXPIRED_DAY_RATIO { get; set; }
    }
}
