//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_VACCINE_TYPE
    {
        public HIS_VACCINE_TYPE()
        {
            this.HIS_KSK_UNEI_VATY = new HashSet<HIS_KSK_UNEI_VATY>();
            this.HIS_MEDICINE_TYPE = new HashSet<HIS_MEDICINE_TYPE>();
            this.HIS_VACC_APPOINTMENT = new HashSet<HIS_VACC_APPOINTMENT>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string VACCINE_TYPE_CODE { get; set; }
        public string VACCINE_TYPE_NAME { get; set; }
        public Nullable<short> IS_USE_FOR_KSK { get; set; }
    
        public virtual ICollection<HIS_KSK_UNEI_VATY> HIS_KSK_UNEI_VATY { get; set; }
        public virtual ICollection<HIS_MEDICINE_TYPE> HIS_MEDICINE_TYPE { get; set; }
        public virtual ICollection<HIS_VACC_APPOINTMENT> HIS_VACC_APPOINTMENT { get; set; }
    }
}
