//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_IMP_MEST_PROPOSE
    {
        public HIS_IMP_MEST_PROPOSE()
        {
            this.HIS_IMP_MEST = new HashSet<HIS_IMP_MEST>();
            this.HIS_IMP_MEST_PAY = new HashSet<HIS_IMP_MEST_PAY>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string IMP_MEST_PROPOSE_CODE { get; set; }
        public string PROPOSE_LOGINNAME { get; set; }
        public string PROPOSE_USERNAME { get; set; }
        public long SUPPLIER_ID { get; set; }
        public long PROPOSE_ROOM_ID { get; set; }
        public long PROPOSE_DEPARTMENT_ID { get; set; }
        public Nullable<long> MEDICAL_CONTRACT_ID { get; set; }
    
        public virtual HIS_DEPARTMENT HIS_DEPARTMENT { get; set; }
        public virtual ICollection<HIS_IMP_MEST> HIS_IMP_MEST { get; set; }
        public virtual ICollection<HIS_IMP_MEST_PAY> HIS_IMP_MEST_PAY { get; set; }
        public virtual HIS_SUPPLIER HIS_SUPPLIER { get; set; }
        public virtual HIS_ROOM HIS_ROOM { get; set; }
        public virtual HIS_MEDICAL_CONTRACT HIS_MEDICAL_CONTRACT { get; set; }
    }
}
