//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_APPOINTMENT
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long APPOINTMENT_DATE { get; set; }
        public string APPOINTMENT_CODE { get; set; }
        public Nullable<long> APPOINTMENT_PERIOD_ID { get; set; }
        public Nullable<long> NUM_ORDER_ISSUE_ID { get; set; }
        public long NUM_ORDER { get; set; }
        public Nullable<long> PATIENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string VIR_PATIENT_NAME { get; set; }
        public long GENDER_ID { get; set; }
        public long DOB { get; set; }
        public Nullable<short> IS_HAS_NOT_DAY_DOB { get; set; }
        public string ETHNIC_CODE { get; set; }
        public string ETHNIC_NAME { get; set; }
        public string RELIGION_NAME { get; set; }
        public string PROVINCE_CODE { get; set; }
        public string PROVINCE_NAME { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string COMMUNE_CODE { get; set; }
        public string COMMUNE_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string VIR_ADDRESS { get; set; }
        public string MOBILE { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string CAREER_CODE { get; set; }
        public string CAREER_NAME { get; set; }
        public Nullable<long> CAREER_ID { get; set; }
    
        public virtual HIS_NUM_ORDER_ISSUE HIS_NUM_ORDER_ISSUE { get; set; }
        public virtual HIS_PATIENT HIS_PATIENT { get; set; }
        public virtual HIS_APPOINTMENT_PERIOD HIS_APPOINTMENT_PERIOD { get; set; }
        public virtual HIS_GENDER HIS_GENDER { get; set; }
        public virtual HIS_CAREER HIS_CAREER { get; set; }
    }
}
