//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_TRANSFUSION
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long TRANSFUSION_SUM_ID { get; set; }
        public long MEASURE_TIME { get; set; }
        public long SPEED { get; set; }
        public string SKIN { get; set; }
        public Nullable<decimal> BREATH_RATE { get; set; }
        public Nullable<long> PULSE { get; set; }
        public Nullable<long> BLOOD_PRESSURE_MAX { get; set; }
        public Nullable<long> BLOOD_PRESSURE_MIN { get; set; }
        public Nullable<decimal> TEMPERATURE { get; set; }
        public string NOTE { get; set; }
    
        public virtual HIS_TRANSFUSION_SUM HIS_TRANSFUSION_SUM { get; set; }
    }
}
