//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_ROOM_TIME
    {
        public HIS_ROOM_TIME()
        {
            this.HIS_NUM_ORDER_BLOCK = new HashSet<HIS_NUM_ORDER_BLOCK>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long ROOM_ID { get; set; }
        public short DAY { get; set; }
        public string FROM_TIME { get; set; }
        public string TO_TIME { get; set; }
        public string ROOM_TIME_NAME { get; set; }
    
        public virtual ICollection<HIS_NUM_ORDER_BLOCK> HIS_NUM_ORDER_BLOCK { get; set; }
        public virtual HIS_ROOM HIS_ROOM { get; set; }
    }
}
