//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_ASSESSMENT_MEMBER
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long MEDICAL_ASSESSMENT_ID { get; set; }
        public string LOGINNAME { get; set; }
        public string USERNAME { get; set; }
        public Nullable<short> IS_PRESIDENT { get; set; }
        public Nullable<short> IS_SECRETARY { get; set; }
        public Nullable<short> IS_VICE_PRESIDENT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<short> ON_BEHALF_TO_SIGN { get; set; }
        public Nullable<short> IS_GUEST { get; set; }
        public Nullable<short> IS_DISAGREED { get; set; }
        public string DISAGREE_REASON { get; set; }
        public Nullable<short> IS_ABSENT { get; set; }
    
        public virtual HIS_MEDICAL_ASSESSMENT HIS_MEDICAL_ASSESSMENT { get; set; }
    }
}
