//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_ACCIDENT_HURT
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long TREATMENT_ID { get; set; }
        public string CONTENT { get; set; }
        public long ACCIDENT_HURT_TYPE_ID { get; set; }
        public Nullable<long> ACCIDENT_BODY_PART_ID { get; set; }
        public Nullable<long> ACCIDENT_LOCATION_ID { get; set; }
        public Nullable<long> ACCIDENT_POISON_ID { get; set; }
        public Nullable<long> ACCIDENT_VEHICLE_ID { get; set; }
        public Nullable<long> ACCIDENT_HELMET_ID { get; set; }
        public Nullable<long> ACCIDENT_RESULT_ID { get; set; }
        public Nullable<long> ACCIDENT_CARE_ID { get; set; }
        public Nullable<long> ACCIDENT_TIME { get; set; }
        public Nullable<short> IS_USE_ALCOHOL { get; set; }
        public Nullable<long> EXECUTE_ROOM_ID { get; set; }
        public Nullable<long> EXECUTE_DEPARTMENT_ID { get; set; }
        public string EXECUTE_LOGINNAME { get; set; }
        public string EXECUTE_USERNAME { get; set; }
        public string STATUS_IN { get; set; }
        public string STATUS_OUT { get; set; }
        public string TREATMENT_INFO { get; set; }
        public Nullable<short> ALCOHOL_TEST_RESULT { get; set; }
        public Nullable<short> NARCOTICS_TEST_RESULT { get; set; }
        public string ISSUE_NUMBER { get; set; }
        public string SEEDING_ISSUED_CODE { get; set; }
        public string VIR_ISSUE_NUMBER { get; set; }
        public string ACCIDENT_HURT_ICD_CODE { get; set; }
        public string ACCIDENT_HURT_ICD_NAME { get; set; }
        public string ACCIDENT_HURT_ICD_SUB_CODE { get; set; }
        public string ACCIDENT_HURT_ICD_TEXT { get; set; }
    
        public virtual HIS_ACCIDENT_BODY_PART HIS_ACCIDENT_BODY_PART { get; set; }
        public virtual HIS_ACCIDENT_CARE HIS_ACCIDENT_CARE { get; set; }
        public virtual HIS_ACCIDENT_HELMET HIS_ACCIDENT_HELMET { get; set; }
        public virtual HIS_TREATMENT HIS_TREATMENT { get; set; }
        public virtual HIS_ROOM HIS_ROOM { get; set; }
        public virtual HIS_DEPARTMENT HIS_DEPARTMENT { get; set; }
        public virtual HIS_ACCIDENT_HURT_TYPE HIS_ACCIDENT_HURT_TYPE { get; set; }
        public virtual HIS_ACCIDENT_LOCATION HIS_ACCIDENT_LOCATION { get; set; }
        public virtual HIS_ACCIDENT_POISON HIS_ACCIDENT_POISON { get; set; }
        public virtual HIS_ACCIDENT_VEHICLE HIS_ACCIDENT_VEHICLE { get; set; }
        public virtual HIS_ACCIDENT_RESULT HIS_ACCIDENT_RESULT { get; set; }
    }
}
