//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_HIS_TREATMENT_1
    {
        public long ID { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string TREATMENT_CODE { get; set; }
        public Nullable<short> IS_PAUSE { get; set; }
        public Nullable<long> CLINICAL_IN_TIME { get; set; }
        public string TDL_PATIENT_NAME { get; set; }
        public string TDL_PATIENT_FIRST_NAME { get; set; }
        public string TDL_PATIENT_LAST_NAME { get; set; }
        public string TDL_PATIENT_GENDER_NAME { get; set; }
        public long TDL_PATIENT_DOB { get; set; }
        public string TDL_HEIN_CARD_NUMBER { get; set; }
        public string TDL_HEIN_MEDI_ORG_CODE { get; set; }
        public Nullable<long> TDL_TREATMENT_TYPE_ID { get; set; }
        public long IN_TIME { get; set; }
        public long IN_DATE { get; set; }
        public Nullable<long> LAST_DEPARTMENT_ID { get; set; }
        public Nullable<long> BED_ROOM_ID { get; set; }
        public Nullable<long> BED_ID { get; set; }
        public string BED_ROOM_CODE { get; set; }
        public string BED_ROOM_NAME { get; set; }
        public string BED_CODE { get; set; }
        public string BED_NAME { get; set; }
        public Nullable<decimal> TOTAL_BILL_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_BILL_OTHER_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_BILL_TRANSFER_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_BILL_EXEMPTION { get; set; }
        public Nullable<decimal> TOTAL_BILL_FUND { get; set; }
        public Nullable<decimal> TOTAL_DEPOSIT_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_REPAY_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_PRICE { get; set; }
        public Nullable<decimal> TOTAL_HEIN_PRICE { get; set; }
        public Nullable<decimal> TOTAL_PATIENT_PRICE { get; set; }
        public Nullable<decimal> TOTAL_DISCOUNT { get; set; }
        public Nullable<decimal> REMAIN_AMOUNT { get; set; }
    }
}
