//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_HIS_MATERIAL_BEAN
    {
        public long ID { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<long> MEDI_STOCK_ID { get; set; }
        public long TDL_MATERIAL_TYPE_ID { get; set; }
        public Nullable<short> TDL_MATERIAL_IS_ACTIVE { get; set; }
        public string MATERIAL_TYPE_CODE { get; set; }
        public string MATERIAL_TYPE_NAME { get; set; }
        public Nullable<short> MATERIAL_TYPE_IS_ACTIVE { get; set; }
        public string CONCENTRA { get; set; }
        public Nullable<short> IS_BUSINESS { get; set; }
        public string MEDI_STOCK_CODE { get; set; }
        public string MEDI_STOCK_NAME { get; set; }
        public string SERVICE_UNIT_NAME { get; set; }
    }
}
