//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_ANTIGEN_METY
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long ANTIGEN_ID { get; set; }
        public long MEDICINE_TYPE_ID { get; set; }
        public string ANTIGEN_CODE { get; set; }
        public string ANTIGEN_NAME { get; set; }
        public string MEDICINE_TYPE_CODE { get; set; }
        public string MEDICINE_TYPE_NAME { get; set; }
        public Nullable<short> IS_LEAF { get; set; }
        public string CONCENTRA { get; set; }
        public string ACTIVE_INGR_BHYT_CODE { get; set; }
        public string ACTIVE_INGR_BHYT_NAME { get; set; }
        public string REGISTER_NUMBER { get; set; }
        public long TDL_SERVICE_UNIT_ID { get; set; }
        public string NATIONAL_NAME { get; set; }
        public string TUTORIAL { get; set; }
        public string DESCRIPTION { get; set; }
        public string MEDICINE_TYPE_PROPRIETARY_NAME { get; set; }
        public string PACKING_TYPE_NAME { get; set; }
        public Nullable<short> IS_VITAMIN_A { get; set; }
        public Nullable<short> IS_VACCINE { get; set; }
        public Nullable<short> IS_TCMR { get; set; }
    }
}
