//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_MEDICINE_BEAN_2
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long MEDICINE_ID { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<long> MEDI_STOCK_ID { get; set; }
        public Nullable<long> SOURCE_ID { get; set; }
        public Nullable<decimal> DETACH_AMOUNT { get; set; }
        public string DETACH_KEY { get; set; }
        public Nullable<decimal> BK_DECREASE_AMOUNT { get; set; }
        public Nullable<long> BK_MEDI_STOCK_ID { get; set; }
        public Nullable<short> IS_TH { get; set; }
        public Nullable<short> IS_CK { get; set; }
        public Nullable<short> IS_USE { get; set; }
        public string SESSION_KEY { get; set; }
        public Nullable<long> SESSION_TIME { get; set; }
        public long TDL_MEDICINE_TYPE_ID { get; set; }
        public Nullable<short> TDL_MEDICINE_IS_ACTIVE { get; set; }
        public decimal TDL_MEDICINE_IMP_PRICE { get; set; }
        public decimal TDL_MEDICINE_IMP_VAT_RATIO { get; set; }
        public Nullable<long> TDL_MEDICINE_IMP_TIME { get; set; }
        public Nullable<long> TDL_MEDICINE_EXPIRED_DATE { get; set; }
        public Nullable<short> TDL_IS_SALE_EQUAL_IMP_PRICE { get; set; }
        public long TDL_SERVICE_ID { get; set; }
        public Nullable<long> EXP_MEST_MEDICINE_ID { get; set; }
        public long MEDICINE_TYPE_ID { get; set; }
        public decimal IMP_PRICE { get; set; }
        public decimal IMP_VAT_RATIO { get; set; }
        public Nullable<long> BID_ID { get; set; }
        public Nullable<long> IMP_TIME { get; set; }
        public Nullable<decimal> INTERNAL_PRICE { get; set; }
        public string PACKAGE_NUMBER { get; set; }
        public Nullable<long> SUPPLIER_ID { get; set; }
        public Nullable<short> MEDICINE_IS_ACTIVE { get; set; }
    }
}
