//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_SERVICE_CHANGE_REQ
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long TDL_SERVICE_REQ_ID { get; set; }
        public string REQUEST_LOGINNAME { get; set; }
        public string REQUEST_USERNAME { get; set; }
        public string APPROVAL_LOGINNAME { get; set; }
        public string APPROVAL_USERNAME { get; set; }
        public string APPROVAL_CASHIER_LOGINNAME { get; set; }
        public string APPROVAL_CASHIER_USERNAME { get; set; }
        public long ALTER_SERVICE_ID { get; set; }
        public long SERE_SERV_ID { get; set; }
        public long PATIENT_TYPE_ID { get; set; }
        public Nullable<long> PRIMARY_PATIENT_TYPE_ID { get; set; }
        public Nullable<long> ALTER_SERE_SERV_ID { get; set; }
        public string SERVICE_REQ_CODE { get; set; }
        public string TDL_TREATMENT_CODE { get; set; }
        public string TDL_PATIENT_NAME { get; set; }
        public long EXECUTE_ROOM_ID { get; set; }
        public long REQUEST_ROOM_ID { get; set; }
        public string TDL_SERVICE_CODE { get; set; }
        public string TDL_SERVICE_NAME { get; set; }
        public decimal AMOUNT { get; set; }
        public string EXECUTE_ROOM_CODE { get; set; }
        public string EXECUTE_ROOM_NAME { get; set; }
        public string REQUEST_ROOM_CODE { get; set; }
        public string REQUEST_ROOM_NAME { get; set; }
        public long BRANCH_ID { get; set; }
        public string ALTER_SERVICE_CODE { get; set; }
        public string ALTER_SERVICE_NAME { get; set; }
    }
}
