//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_METY_METY
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long PREPARATION_MEDICINE_TYPE_ID { get; set; }
        public decimal PREPARATION_AMOUNT { get; set; }
        public long METY_PRODUCT_ID { get; set; }
        public Nullable<long> MEDICINE_TYPE_ID_BK { get; set; }
        public long MEDICINE_TYPE_ID { get; set; }
        public decimal PRODUCT_AMOUNT { get; set; }
        public string MEDICINE_TYPE_CODE { get; set; }
        public string MEDICINE_TYPE_NAME { get; set; }
        public string PREPARATION_MEDICINE_TYPE_CODE { get; set; }
        public string PREPARATION_MEDICINE_TYPE_NAME { get; set; }
    }
}
