//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_VACCINATION_EXAM
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string VACCINATION_EXAM_CODE { get; set; }
        public long PATIENT_ID { get; set; }
        public long BRANCH_ID { get; set; }
        public Nullable<long> NUM_ORDER { get; set; }
        public long REQUEST_TIME { get; set; }
        public long REQUEST_DATE { get; set; }
        public long REQUEST_ROOM_ID { get; set; }
        public long REQUEST_DEPARTMENT_ID { get; set; }
        public string REQUEST_LOGINNAME { get; set; }
        public string REQUEST_USERNAME { get; set; }
        public Nullable<long> EXECUTE_TIME { get; set; }
        public Nullable<long> EXECUTE_DATE { get; set; }
        public long EXECUTE_ROOM_ID { get; set; }
        public long EXECUTE_DEPARTMENT_ID { get; set; }
        public string EXECUTE_LOGINNAME { get; set; }
        public string EXECUTE_USERNAME { get; set; }
        public string TDL_PATIENT_CODE { get; set; }
        public string TDL_PATIENT_NAME { get; set; }
        public string TDL_PATIENT_FIRST_NAME { get; set; }
        public string TDL_PATIENT_LAST_NAME { get; set; }
        public long TDL_PATIENT_DOB { get; set; }
        public Nullable<short> TDL_PATIENT_IS_HAS_NOT_DAY_DOB { get; set; }
        public string TDL_PATIENT_ADDRESS { get; set; }
        public Nullable<long> TDL_PATIENT_GENDER_ID { get; set; }
        public string TDL_PATIENT_GENDER_NAME { get; set; }
        public string TDL_PATIENT_CAREER_NAME { get; set; }
        public string TDL_PATIENT_WORK_PLACE { get; set; }
        public string TDL_PATIENT_WORK_PLACE_NAME { get; set; }
        public string NOTE { get; set; }
        public Nullable<long> CONCLUDE { get; set; }
        public long PATIENT_TYPE_ID { get; set; }
        public string PT_PATHOLOGICAL_HISTORY { get; set; }
        public string PT_PATHOLOGICAL_HISTORY_FAMILY { get; set; }
        public string PT_ALLERGIC_HISTORY { get; set; }
        public string ADVISE { get; set; }
        public Nullable<long> APPOINTMENT_TIME { get; set; }
        public Nullable<short> VACCINATION_EXAM_STT_ID { get; set; }
        public Nullable<short> IS_TEST_HBSAG { get; set; }
        public Nullable<short> IS_POSITIVE_RESULT { get; set; }
        public Nullable<short> IS_SPECIALIST_EXAM { get; set; }
        public Nullable<long> SPECIALIST_DEPARTMENT_ID { get; set; }
        public string SPECIALIST_REASON { get; set; }
        public string SPECIALIST_RESULT { get; set; }
        public string SPECIALIST_CONCLUDE { get; set; }
        public Nullable<long> RABIES_NUMBER_OF_DAYS { get; set; }
        public Nullable<short> RABIES_ANIMAL_DOG { get; set; }
        public Nullable<short> RABIES_ANIMAL_CAT { get; set; }
        public Nullable<short> RABIES_ANIMAL_BAT { get; set; }
        public Nullable<short> RABIES_ANIMAL_OTHER { get; set; }
        public Nullable<short> RABIES_WOUND_LOCATION_HEAD { get; set; }
        public Nullable<short> RABIES_WOUND_LOCATION_FACE { get; set; }
        public Nullable<short> RABIES_WOUND_LOCATION_NECK { get; set; }
        public Nullable<short> RABIES_WOUND_LOCATION_HAND { get; set; }
        public Nullable<short> RABIES_WOUND_LOCATION_FOOT { get; set; }
        public Nullable<short> RABIES_WOUND_RANK { get; set; }
        public Nullable<short> RABIES_ANIMAL_STATUS { get; set; }
        public string PATIENT_TYPE_CODE { get; set; }
        public string PATIENT_TYPE_NAME { get; set; }
        public string REQUEST_ROOM_CODE { get; set; }
        public string REQUEST_ROOM_NAME { get; set; }
        public string REQUEST_DEPARTMENT_CODE { get; set; }
        public string REQUEST_DEPARTMENT_NAME { get; set; }
        public string EXECUTE_ROOM_CODE { get; set; }
        public string EXECUTE_ROOM_NAME { get; set; }
        public string EXECUTE_DEPARTMENT_CODE { get; set; }
        public string EXECUTE_DEPARTMENT_NAME { get; set; }
        public string SPECIALIST_DEPARTMENT_CODE { get; set; }
        public string SPECIALIST_DEPARTMENT_NAME { get; set; }
        public string RELATIVE_ADDRESS { get; set; }
        public string RELATIVE_CMND_NUMBER { get; set; }
        public string RELATIVE_MOBILE { get; set; }
        public string RELATIVE_NAME { get; set; }
        public string RELATIVE_PHONE { get; set; }
        public string RELATIVE_TYPE { get; set; }
    }
}
