//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_TRANSFUSION_SUM
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long TREATMENT_ID { get; set; }
        public Nullable<long> DEPARTMENT_ID { get; set; }
        public Nullable<long> ROOM_ID { get; set; }
        public long EXP_MEST_BLOOD_ID { get; set; }
        public Nullable<long> START_TIME { get; set; }
        public Nullable<long> FINISH_TIME { get; set; }
        public Nullable<long> NUM_ORDER { get; set; }
        public string EXECUTE_LOGINNAME { get; set; }
        public string EXECUTE_USERNAME { get; set; }
        public string ICD_CODE { get; set; }
        public string ICD_NAME { get; set; }
        public string ICD_SUB_CODE { get; set; }
        public string ICD_TEXT { get; set; }
        public Nullable<decimal> TRANSFUSION_VOLUME { get; set; }
        public string NOTE { get; set; }
        public string TREATMENT_CODE { get; set; }
        public string TDL_PATIENT_CODE { get; set; }
        public string TDL_PATIENT_NAME { get; set; }
        public long TDL_PATIENT_DOB { get; set; }
        public Nullable<short> TDL_PATIENT_IS_HAS_NOT_DAY_DOB { get; set; }
        public string TDL_PATIENT_GENDER_NAME { get; set; }
        public long BLOOD_ID { get; set; }
        public string PATIENT_BLOOD_ABO_CODE { get; set; }
        public string PATIENT_BLOOD_RH_CODE { get; set; }
        public string PUC { get; set; }
        public string TEST_TUBE { get; set; }
        public string SCANGEL_GELCARD { get; set; }
        public string COOMBS { get; set; }
        public string BLOOD_CODE { get; set; }
        public long BLOOD_TYPE_ID { get; set; }
        public long BLOOD_ABO_ID { get; set; }
        public Nullable<long> BLOOD_RH_ID { get; set; }
        public Nullable<long> EXPIRED_DATE { get; set; }
        public Nullable<short> IS_INFECT { get; set; }
        public string GIVE_NAME { get; set; }
        public string GIVE_CODE { get; set; }
        public string BLOOD_TYPE_CODE { get; set; }
        public string BLOOD_TYPE_NAME { get; set; }
        public long BLOOD_VOLUME_ID { get; set; }
        public decimal VOLUME { get; set; }
    }
}
