//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_EXP_MEST_MEDICINE
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public Nullable<decimal> BK_AMOUNT { get; set; }
        public Nullable<long> EXP_MEST_ID { get; set; }
        public Nullable<long> MEDICINE_ID { get; set; }
        public Nullable<long> TDL_MEDI_STOCK_ID { get; set; }
        public Nullable<long> MEDI_STOCK_PERIOD_ID { get; set; }
        public Nullable<long> TDL_MEDICINE_TYPE_ID { get; set; }
        public Nullable<long> TDL_AGGR_EXP_MEST_ID { get; set; }
        public Nullable<long> EXP_MEST_METY_REQ_ID { get; set; }
        public Nullable<long> CK_IMP_MEST_MEDICINE_ID { get; set; }
        public Nullable<short> IS_EXPORT { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> VAT_RATIO { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<long> NUM_ORDER { get; set; }
        public string DESCRIPTION { get; set; }
        public string APPROVAL_LOGINNAME { get; set; }
        public string APPROVAL_USERNAME { get; set; }
        public Nullable<long> APPROVAL_TIME { get; set; }
        public Nullable<long> APPROVAL_DATE { get; set; }
        public string EXP_LOGINNAME { get; set; }
        public string EXP_USERNAME { get; set; }
        public Nullable<long> EXP_TIME { get; set; }
        public Nullable<long> EXP_DATE { get; set; }
        public Nullable<decimal> TH_AMOUNT { get; set; }
        public Nullable<long> PATIENT_TYPE_ID { get; set; }
        public Nullable<long> SERE_SERV_PARENT_ID { get; set; }
        public Nullable<short> IS_EXPEND { get; set; }
        public Nullable<short> IS_OUT_PARENT_FEE { get; set; }
        public Nullable<long> USE_TIME_TO { get; set; }
        public string TUTORIAL { get; set; }
        public Nullable<long> TDL_SERVICE_REQ_ID { get; set; }
        public Nullable<long> TDL_TREATMENT_ID { get; set; }
        public Nullable<short> IS_USE_CLIENT_PRICE { get; set; }
        public Nullable<decimal> VIR_PRICE { get; set; }
        public Nullable<long> VACCINATION_RESULT_ID { get; set; }
        public Nullable<long> TDL_VACCINATION_ID { get; set; }
        public Nullable<decimal> SPEED { get; set; }
        public Nullable<long> EXPEND_TYPE_ID { get; set; }
        public Nullable<short> IS_NOT_PRES { get; set; }
        public Nullable<short> USE_ORIGINAL_UNIT_FOR_PRES { get; set; }
        public Nullable<decimal> BCS_REQ_AMOUNT { get; set; }
        public Nullable<long> DAY_COUNT { get; set; }
        public string MORNING { get; set; }
        public string NOON { get; set; }
        public string AFTERNOON { get; set; }
        public string EVENING { get; set; }
        public Nullable<long> HTU_ID { get; set; }
        public string BREATH_SPEED { get; set; }
        public string BREATH_TIME { get; set; }
        public Nullable<long> PREVIOUS_USING_COUNT { get; set; }
        public Nullable<short> IS_USED { get; set; }
        public Nullable<long> SERVICE_CONDITION_ID { get; set; }
        public Nullable<short> IS_CREATED_BY_APPROVAL { get; set; }
        public Nullable<long> OTHER_PAY_SOURCE_ID { get; set; }
        public Nullable<long> MIXED_INFUSION { get; set; }
        public string TUTORIAL_INFUSION { get; set; }
        public Nullable<short> IS_MIXED_MAIN { get; set; }
        public Nullable<long> VACCINE_TURN { get; set; }
        public Nullable<decimal> PRES_AMOUNT { get; set; }
        public string EXCEED_LIMIT_IN_PRES_REASON { get; set; }
        public string EXCEED_LIMIT_IN_DAY_REASON { get; set; }
        public string ODD_PRES_REASON { get; set; }
        public string OVER_RESULT_TEST_REASON { get; set; }
        public string OVER_KIDNEY_REASON { get; set; }
        public string EXP_MEST_CODE { get; set; }
        public long EXP_MEST_TYPE_ID { get; set; }
        public Nullable<long> AGGR_EXP_MEST_ID { get; set; }
        public long MEDI_STOCK_ID { get; set; }
        public long EXP_MEST_STT_ID { get; set; }
        public long REQ_ROOM_ID { get; set; }
        public long REQ_DEPARTMENT_ID { get; set; }
        public Nullable<long> TDL_INTRUCTION_TIME { get; set; }
        public string REQ_USER_TITLE { get; set; }
        public string TDL_PRES_REQ_USER_TITLE { get; set; }
        public string REQ_LOGINNAME { get; set; }
        public string REQ_USERNAME { get; set; }
        public Nullable<long> TDL_PATIENT_ID { get; set; }
        public decimal IMP_PRICE { get; set; }
        public decimal IMP_VAT_RATIO { get; set; }
        public Nullable<long> BID_ID { get; set; }
        public string PACKAGE_NUMBER { get; set; }
        public Nullable<long> EXPIRED_DATE { get; set; }
        public long MEDICINE_TYPE_ID { get; set; }
        public Nullable<decimal> INTERNAL_PRICE { get; set; }
        public Nullable<long> IMP_TIME { get; set; }
        public Nullable<long> SUPPLIER_ID { get; set; }
        public string MEDICINE_TCY_NUM_ORDER { get; set; }
        public string MEDICINE_BYT_NUM_ORDER { get; set; }
        public string MEDICINE_REGISTER_NUMBER { get; set; }
        public string ACTIVE_INGR_BHYT_CODE { get; set; }
        public string ACTIVE_INGR_BHYT_NAME { get; set; }
        public string CONCENTRA { get; set; }
        public Nullable<decimal> TAX_RATIO { get; set; }
        public string MEDICINE_TYPE_CODE { get; set; }
        public string MEDICINE_TYPE_NAME { get; set; }
        public long SERVICE_ID { get; set; }
        public string NATIONAL_NAME { get; set; }
        public Nullable<long> MANUFACTURER_ID { get; set; }
        public Nullable<long> MEDICINE_TYPE_NUM_ORDER { get; set; }
        public string TCY_NUM_ORDER { get; set; }
        public string BYT_NUM_ORDER { get; set; }
        public string REGISTER_NUMBER { get; set; }
        public Nullable<short> IS_FUNCTIONAL_FOOD { get; set; }
        public Nullable<long> MEMA_GROUP_ID { get; set; }
        public Nullable<short> IS_ALLOW_ODD { get; set; }
        public Nullable<long> MEDICINE_GROUP_ID { get; set; }
        public long SERVICE_UNIT_ID { get; set; }
        public string RECORDING_TRANSACTION { get; set; }
        public Nullable<long> MEDICINE_USE_FORM_ID { get; set; }
        public Nullable<short> IS_OUT_HOSPITAL { get; set; }
        public string SERVICE_UNIT_CODE { get; set; }
        public string SERVICE_UNIT_NAME { get; set; }
        public Nullable<long> MEDICINE_NUM_ORDER { get; set; }
        public Nullable<long> MATERIAL_NUM_ORDER { get; set; }
        public Nullable<decimal> CONVERT_RATIO { get; set; }
        public string MANUFACTURER_CODE { get; set; }
        public string MANUFACTURER_NAME { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string BID_NUMBER { get; set; }
        public string BID_NAME { get; set; }
        public string PATIENT_TYPE_CODE { get; set; }
        public string PATIENT_TYPE_NAME { get; set; }
        public Nullable<short> IS_RATION { get; set; }
        public string CONVERT_UNIT_CODE { get; set; }
        public string CONVERT_UNIT_NAME { get; set; }
        public string HTU_NAME { get; set; }
        public string MEDICINE_GROUP_CODE { get; set; }
        public string MEDICINE_GROUP_NAME { get; set; }
        public Nullable<long> MEDICINE_GROUP_NUM_ORDER { get; set; }
        public string MEDICINE_USE_FORM_CODE { get; set; }
        public string MEDICINE_USE_FORM_NAME { get; set; }
        public Nullable<long> MEDICINE_USE_FORM_NUM_ORDER { get; set; }
        public string MEDI_STOCK_CODE { get; set; }
        public string MEDI_STOCK_NAME { get; set; }
        public string OTHER_PAY_SOURCE_CODE { get; set; }
        public string OTHER_PAY_SOURCE_NAME { get; set; }
    }
}
