//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_SERE_SERV_14
    {
        public long ID { get; set; }
        public string TDL_SERVICE_NAME { get; set; }
        public decimal PRICE { get; set; }
        public Nullable<short> IS_EXPEND { get; set; }
        public Nullable<short> IS_NO_EXECUTE { get; set; }
        public Nullable<decimal> VIR_TOTAL_PRICE { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<decimal> VIR_TOTAL_HEIN_PRICE { get; set; }
        public Nullable<decimal> VIR_TOTAL_PATIENT_PRICE { get; set; }
        public Nullable<long> TDL_TREATMENT_ID { get; set; }
        public Nullable<decimal> TOTAL_DEBT_PRICE { get; set; }
    }
}
