//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_AREA
    {
        public HIS_AREA()
        {
            this.HIS_DESK = new HashSet<HIS_DESK>();
            this.HIS_ROOM = new HashSet<HIS_ROOM>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string AREA_CODE { get; set; }
        public string AREA_NAME { get; set; }
        public Nullable<long> DEPARTMENT_ID { get; set; }
        public Nullable<long> PATIENT_TYPE_ID { get; set; }
    
        public virtual HIS_DEPARTMENT HIS_DEPARTMENT { get; set; }
        public virtual HIS_PATIENT_TYPE HIS_PATIENT_TYPE { get; set; }
        public virtual ICollection<HIS_DESK> HIS_DESK { get; set; }
        public virtual ICollection<HIS_ROOM> HIS_ROOM { get; set; }
    }
}
