//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_TRAN_PATI_TEMP
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string TRAN_PATI_TEMP_CODE { get; set; }
        public string TRAN_PATI_TEMP_NAME { get; set; }
        public string MEDI_ORG_CODE { get; set; }
        public string MEDI_ORG_NAME { get; set; }
        public long TRAN_PATI_REASON_ID { get; set; }
        public long TRAN_PATI_FORM_ID { get; set; }
        public Nullable<long> TRAN_PATI_TECH_ID { get; set; }
        public Nullable<short> IS_PUBLIC { get; set; }
        public string TREATMENT_DIRECTION { get; set; }
        public string TREATMENT_METHOD { get; set; }
        public string PATIENT_CONDITION { get; set; }
        public string USED_MEDICINE { get; set; }
        public string TRANSPORT_VEHICLE { get; set; }
        public string TRANSPORTER { get; set; }
    
        public virtual HIS_TRAN_PATI_FORM HIS_TRAN_PATI_FORM { get; set; }
        public virtual HIS_TRAN_PATI_REASON HIS_TRAN_PATI_REASON { get; set; }
        public virtual HIS_TRAN_PATI_TECH HIS_TRAN_PATI_TECH { get; set; }
    }
}
