//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_MEDICINE
    {
        public HIS_MEDICINE()
        {
            this.HIS_EXP_MEST_MEDICINE = new HashSet<HIS_EXP_MEST_MEDICINE>();
            this.HIS_IMP_MEST_MATE_REQ = new HashSet<HIS_IMP_MEST_MATE_REQ>();
            this.HIS_IMP_MEST_MEDI_REQ = new HashSet<HIS_IMP_MEST_MEDI_REQ>();
            this.HIS_IMP_MEST_MEDICINE = new HashSet<HIS_IMP_MEST_MEDICINE>();
            this.HIS_INFUSION = new HashSet<HIS_INFUSION>();
            this.HIS_MEDI_REACT = new HashSet<HIS_MEDI_REACT>();
            this.HIS_MEDICINE_BEAN = new HashSet<HIS_MEDICINE_BEAN>();
            this.HIS_MEDICINE_MATERIAL = new HashSet<HIS_MEDICINE_MATERIAL>();
            this.HIS_MEDICINE_MEDICINE = new HashSet<HIS_MEDICINE_MEDICINE>();
            this.HIS_MEDICINE_MEDICINE1 = new HashSet<HIS_MEDICINE_MEDICINE>();
            this.HIS_MEDICINE_PATY = new HashSet<HIS_MEDICINE_PATY>();
            this.HIS_MEST_PERIOD_MEDI = new HashSet<HIS_MEST_PERIOD_MEDI>();
            this.HIS_MIXED_MEDICINE = new HashSet<HIS_MIXED_MEDICINE>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long MEDICINE_TYPE_ID { get; set; }
        public Nullable<long> SUPPLIER_ID { get; set; }
        public string PACKAGE_NUMBER { get; set; }
        public Nullable<long> EXPIRED_DATE { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<long> IMP_SOURCE_ID { get; set; }
        public Nullable<long> IMP_TIME { get; set; }
        public decimal IMP_PRICE { get; set; }
        public decimal IMP_VAT_RATIO { get; set; }
        public Nullable<decimal> INTERNAL_PRICE { get; set; }
        public Nullable<long> BID_ID { get; set; }
        public string TDL_BID_NUMBER { get; set; }
        public string TDL_BID_NUM_ORDER { get; set; }
        public string TDL_BID_GROUP_CODE { get; set; }
        public string TDL_BID_PACKAGE_CODE { get; set; }
        public string TDL_BID_YEAR { get; set; }
        public string MEDICINE_REGISTER_NUMBER { get; set; }
        public string MEDICINE_BYT_NUM_ORDER { get; set; }
        public string MEDICINE_TCY_NUM_ORDER { get; set; }
        public Nullable<short> MEDICINE_IS_STAR_MARK { get; set; }
        public Nullable<short> IS_PREGNANT { get; set; }
        public Nullable<short> IS_SALE_EQUAL_IMP_PRICE { get; set; }
        public long TDL_SERVICE_ID { get; set; }
        public Nullable<decimal> VIR_IMP_PRICE { get; set; }
        public string ACTIVE_INGR_BHYT_CODE { get; set; }
        public string ACTIVE_INGR_BHYT_NAME { get; set; }
        public Nullable<long> DOCUMENT_PRICE { get; set; }
        public string NATIONAL_NAME { get; set; }
        public Nullable<long> MANUFACTURER_ID { get; set; }
        public string CONCENTRA { get; set; }
        public string TDL_IMP_MEST_CODE { get; set; }
        public string TDL_IMP_MEST_SUB_CODE { get; set; }
        public Nullable<decimal> IMP_UNIT_AMOUNT { get; set; }
        public Nullable<decimal> IMP_UNIT_PRICE { get; set; }
        public Nullable<long> TDL_IMP_UNIT_ID { get; set; }
        public Nullable<decimal> TDL_IMP_UNIT_CONVERT_RATIO { get; set; }
        public Nullable<long> MEDICAL_CONTRACT_ID { get; set; }
        public Nullable<decimal> CONTRACT_PRICE { get; set; }
        public Nullable<decimal> PROFIT_RATIO { get; set; }
        public string PACKING_TYPE_NAME { get; set; }
        public string HEIN_SERVICE_BHYT_NAME { get; set; }
        public string ACTIVE_INGR_BHYT_NAME1 { get; set; }
        public Nullable<long> MEDICINE_USE_FORM_ID { get; set; }
        public string DOSAGE_FORM { get; set; }
        public Nullable<decimal> TAX_RATIO { get; set; }
        public string TDL_BID_EXTRA_CODE { get; set; }
        public string LOCKING_REASON { get; set; }
    
        public virtual HIS_BID HIS_BID { get; set; }
        public virtual ICollection<HIS_EXP_MEST_MEDICINE> HIS_EXP_MEST_MEDICINE { get; set; }
        public virtual ICollection<HIS_IMP_MEST_MATE_REQ> HIS_IMP_MEST_MATE_REQ { get; set; }
        public virtual ICollection<HIS_IMP_MEST_MEDI_REQ> HIS_IMP_MEST_MEDI_REQ { get; set; }
        public virtual ICollection<HIS_IMP_MEST_MEDICINE> HIS_IMP_MEST_MEDICINE { get; set; }
        public virtual HIS_IMP_SOURCE HIS_IMP_SOURCE { get; set; }
        public virtual ICollection<HIS_INFUSION> HIS_INFUSION { get; set; }
        public virtual ICollection<HIS_MEDI_REACT> HIS_MEDI_REACT { get; set; }
        public virtual HIS_MEDICAL_CONTRACT HIS_MEDICAL_CONTRACT { get; set; }
        public virtual ICollection<HIS_MEDICINE_BEAN> HIS_MEDICINE_BEAN { get; set; }
        public virtual HIS_MEDICINE_TYPE HIS_MEDICINE_TYPE { get; set; }
        public virtual HIS_SUPPLIER HIS_SUPPLIER { get; set; }
        public virtual HIS_MEDICINE_USE_FORM HIS_MEDICINE_USE_FORM { get; set; }
        public virtual ICollection<HIS_MEDICINE_MATERIAL> HIS_MEDICINE_MATERIAL { get; set; }
        public virtual ICollection<HIS_MEDICINE_MEDICINE> HIS_MEDICINE_MEDICINE { get; set; }
        public virtual ICollection<HIS_MEDICINE_MEDICINE> HIS_MEDICINE_MEDICINE1 { get; set; }
        public virtual ICollection<HIS_MEDICINE_PATY> HIS_MEDICINE_PATY { get; set; }
        public virtual ICollection<HIS_MEST_PERIOD_MEDI> HIS_MEST_PERIOD_MEDI { get; set; }
        public virtual ICollection<HIS_MIXED_MEDICINE> HIS_MIXED_MEDICINE { get; set; }
    }
}
