//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_ACTIVE_INGREDIENT
    {
        public HIS_ACTIVE_INGREDIENT()
        {
            this.HIS_ACIN_INTERACTIVE = new HashSet<HIS_ACIN_INTERACTIVE>();
            this.HIS_ACIN_INTERACTIVE1 = new HashSet<HIS_ACIN_INTERACTIVE>();
            this.HIS_ANTIBIOTIC_NEW_REG = new HashSet<HIS_ANTIBIOTIC_NEW_REG>();
            this.HIS_ICD_SERVICE = new HashSet<HIS_ICD_SERVICE>();
            this.HIS_MEDICINE_TYPE_ACIN = new HashSet<HIS_MEDICINE_TYPE_ACIN>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string ACTIVE_INGREDIENT_CODE { get; set; }
        public string ACTIVE_INGREDIENT_NAME { get; set; }
        public Nullable<short> IS_CONSULTATION_REQUIRED { get; set; }
        public string NOTE { get; set; }
        public Nullable<short> IS_APPROVAL_REQUIRED { get; set; }
    
        public virtual ICollection<HIS_ACIN_INTERACTIVE> HIS_ACIN_INTERACTIVE { get; set; }
        public virtual ICollection<HIS_ACIN_INTERACTIVE> HIS_ACIN_INTERACTIVE1 { get; set; }
        public virtual ICollection<HIS_ANTIBIOTIC_NEW_REG> HIS_ANTIBIOTIC_NEW_REG { get; set; }
        public virtual ICollection<HIS_ICD_SERVICE> HIS_ICD_SERVICE { get; set; }
        public virtual ICollection<HIS_MEDICINE_TYPE_ACIN> HIS_MEDICINE_TYPE_ACIN { get; set; }
    }
}
