//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_KSK_OVER_EIGHTEEN
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long SERVICE_REQ_ID { get; set; }
        public long TDL_TREATMENT_ID { get; set; }
        public long TDL_PATIENT_ID { get; set; }
        public Nullable<long> DHST_ID { get; set; }
        public Nullable<long> DHST_RANK { get; set; }
        public string PATHOLOGICAL_HISTORY_FAMILY { get; set; }
        public string MEDICINE_USING { get; set; }
        public string MATERNITY_HISTORY { get; set; }
        public string EXAM_CIRCULATION { get; set; }
        public Nullable<long> EXAM_CIRCULATION_RANK { get; set; }
        public string EXAM_RESPIRATORY { get; set; }
        public Nullable<long> EXAM_RESPIRATORY_RANK { get; set; }
        public string EXAM_DIGESTION { get; set; }
        public Nullable<long> EXAM_DIGESTION_RANK { get; set; }
        public string EXAM_KIDNEY_UROLOGY { get; set; }
        public Nullable<long> EXAM_KIDNEY_UROLOGY_RANK { get; set; }
        public string EXAM_NEUROLOGICAL { get; set; }
        public Nullable<long> EXAM_NEUROLOGICAL_RANK { get; set; }
        public string EXAM_MUSCLE_BONE { get; set; }
        public Nullable<long> EXAM_MUSCLE_BONE_RANK { get; set; }
        public string EXAM_ENT { get; set; }
        public Nullable<long> EXAM_ENT_RANK { get; set; }
        public string EXAM_STOMATOLOGY { get; set; }
        public Nullable<long> EXAM_STOMATOLOGY_RANK { get; set; }
        public string EXAM_EYE { get; set; }
        public Nullable<long> EXAM_EYE_RANK { get; set; }
        public string EXAM_MENTAL { get; set; }
        public Nullable<long> EXAM_MENTAL_RANK { get; set; }
        public string EXAM_DERMATOLOGY { get; set; }
        public Nullable<long> EXAM_DERMATOLOGY_RANK { get; set; }
        public string EXAM_SURGERY { get; set; }
        public Nullable<long> EXAM_SURGERY_RANK { get; set; }
        public Nullable<long> HEALTH_EXAM_RANK_ID { get; set; }
        public string EXAM_OBSTETRIC { get; set; }
        public Nullable<long> EXAM_OBSTETRIC_RANK { get; set; }
        public string DISEASES { get; set; }
        public string PATHOLOGICAL_HISTORY { get; set; }
        public string EXAM_EYE_DISEASE { get; set; }
        public string EXAM_EYESIGHT_GLASS_LEFT { get; set; }
        public string EXAM_EYESIGHT_GLASS_RIGHT { get; set; }
        public string EXAM_EYESIGHT_LEFT { get; set; }
        public string EXAM_EYESIGHT_RIGHT { get; set; }
        public string EXAM_ENT_DISEASE { get; set; }
        public string EXAM_ENT_LEFT_NORMAL { get; set; }
        public string EXAM_ENT_LEFT_WHISPER { get; set; }
        public string EXAM_ENT_RIGHT_NORMAL { get; set; }
        public string EXAM_ENT_RIGHT_WHISPER { get; set; }
        public string EXAM_STOMATOLOGY_DISEASE { get; set; }
        public string EXAM_STOMATOLOGY_LOWER { get; set; }
        public string EXAM_STOMATOLOGY_UPPER { get; set; }
        public string TEST_BLOOD_HC { get; set; }
        public string TEST_BLOOD_BC { get; set; }
        public string TEST_BLOOD_TC { get; set; }
        public string TEST_BLOOD_GLUCO { get; set; }
        public string TEST_BLOOD_URE { get; set; }
        public string TEST_BLOOD_CREATININ { get; set; }
        public string TEST_BLOOD_ASAT { get; set; }
        public string TEST_BLOOD_ALAT { get; set; }
        public string TEST_BLOOD_OTHER { get; set; }
        public string TEST_URINE_GLUCO { get; set; }
        public string TEST_URINE_PROTEIN { get; set; }
        public string TEST_URINE_OTHER { get; set; }
        public string RESULT_DIIM { get; set; }
    
        public virtual HIS_SERVICE_REQ HIS_SERVICE_REQ { get; set; }
    }
}
