//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_EKIP
    {
        public HIS_EKIP()
        {
            this.HIS_EKIP_USER = new HashSet<HIS_EKIP_USER>();
            this.HIS_SERE_SERV = new HashSet<HIS_SERE_SERV>();
            this.HIS_SESE_PTTT_METHOD = new HashSet<HIS_SESE_PTTT_METHOD>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
    
        public virtual ICollection<HIS_EKIP_USER> HIS_EKIP_USER { get; set; }
        public virtual ICollection<HIS_SERE_SERV> HIS_SERE_SERV { get; set; }
        public virtual ICollection<HIS_SESE_PTTT_METHOD> HIS_SESE_PTTT_METHOD { get; set; }
    }
}
