//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_CARE
    {
        public HIS_CARE()
        {
            this.HIS_CARE_DETAIL = new HashSet<HIS_CARE_DETAIL>();
            this.HIS_DHST1 = new HashSet<HIS_DHST>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long TREATMENT_ID { get; set; }
        public Nullable<long> CARE_SUM_ID { get; set; }
        public Nullable<long> TRACKING_ID { get; set; }
        public Nullable<long> DHST_ID { get; set; }
        public Nullable<long> AWARENESS_ID { get; set; }
        public Nullable<long> EXECUTE_ROOM_ID { get; set; }
        public Nullable<long> EXECUTE_DEPARTMENT_ID { get; set; }
        public Nullable<long> EXECUTE_TIME { get; set; }
        public string EXECUTE_LOGINNAME { get; set; }
        public string EXECUTE_USERNAME { get; set; }
        public string MUCOCUTANEOUS { get; set; }
        public string URINE { get; set; }
        public string DEJECTA { get; set; }
        public string NUTRITION { get; set; }
        public string SANITARY { get; set; }
        public string TUTORIAL { get; set; }
        public string EDUCATION { get; set; }
        public string AWARENESS { get; set; }
        public Nullable<short> HAS_TEST { get; set; }
        public Nullable<short> HAS_MEDICINE { get; set; }
        public Nullable<short> HAS_ADD_MEDICINE { get; set; }
        public string INSTRUCTION_DESCRIPTION { get; set; }
        public string CARE_DESCRIPTION { get; set; }
        public Nullable<short> HAS_REHABILITATION { get; set; }
        public Nullable<long> EXECUTE_DATE { get; set; }
        public Nullable<short> ALLERGY_HISTORY { get; set; }
        public Nullable<short> AWARENESS_CONDITION { get; set; }
        public Nullable<short> BODY_CONDITION { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<short> MUCOCUTANEOUS_CONDITION { get; set; }
        public Nullable<short> FUNCTION_CONDITION { get; set; }
        public Nullable<short> SKIN_DAMAGE_CONDITION { get; set; }
        public Nullable<long> PAIN_SCORE { get; set; }
        public Nullable<short> CAN_ULCERS { get; set; }
        public Nullable<short> RESPIRATORY_CONDITION { get; set; }
        public Nullable<short> NEUROLOGICAL_CONDITION { get; set; }
        public Nullable<short> DEFECATE_CONDITION { get; set; }
        public Nullable<short> URINE_CONDITION { get; set; }
        public Nullable<short> DIGEST_CONDITION { get; set; }
        public Nullable<short> TUTORIAL_CONDITION { get; set; }
        public Nullable<short> SANITARY_CONDITION { get; set; }
        public Nullable<short> EDUCATION_CONDITION { get; set; }
        public Nullable<short> HAS_TOPICAL_MEDICINE { get; set; }
        public Nullable<short> HAS_DRINK_MEDICINE { get; set; }
        public Nullable<short> HAS_INFUTION_MEDICINE { get; set; }
        public Nullable<short> HAS_DIIM { get; set; }
        public Nullable<short> HAS_FUEX { get; set; }
        public Nullable<short> HAS_CHANGE_BANDAGE { get; set; }
        public Nullable<short> HAS_CUT_SUTURE { get; set; }
        public string OTHER_CARE { get; set; }
        public string EVALUTE_CARE { get; set; }
    
        public virtual HIS_AWARENESS HIS_AWARENESS { get; set; }
        public virtual ICollection<HIS_CARE_DETAIL> HIS_CARE_DETAIL { get; set; }
        public virtual HIS_TREATMENT HIS_TREATMENT { get; set; }
        public virtual HIS_DHST HIS_DHST { get; set; }
        public virtual HIS_ROOM HIS_ROOM { get; set; }
        public virtual HIS_DEPARTMENT HIS_DEPARTMENT { get; set; }
        public virtual HIS_TRACKING HIS_TRACKING { get; set; }
        public virtual HIS_CARE_SUM HIS_CARE_SUM { get; set; }
        public virtual ICollection<HIS_DHST> HIS_DHST1 { get; set; }
    }
}
