//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_ANTICIPATE
    {
        public HIS_ANTICIPATE()
        {
            this.HIS_ANTICIPATE_BLTY = new HashSet<HIS_ANTICIPATE_BLTY>();
            this.HIS_ANTICIPATE_MATY = new HashSet<HIS_ANTICIPATE_MATY>();
            this.HIS_ANTICIPATE_METY = new HashSet<HIS_ANTICIPATE_METY>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string ANTICIPATE_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string REQUEST_LOGINNAME { get; set; }
        public string REQUEST_USERNAME { get; set; }
        public Nullable<long> REQUEST_ROOM_ID { get; set; }
        public Nullable<long> REQUEST_DEPARTMENT_ID { get; set; }
        public string USE_TIME { get; set; }
    
        public virtual ICollection<HIS_ANTICIPATE_BLTY> HIS_ANTICIPATE_BLTY { get; set; }
        public virtual HIS_ROOM HIS_ROOM { get; set; }
        public virtual HIS_DEPARTMENT HIS_DEPARTMENT { get; set; }
        public virtual ICollection<HIS_ANTICIPATE_MATY> HIS_ANTICIPATE_MATY { get; set; }
        public virtual ICollection<HIS_ANTICIPATE_METY> HIS_ANTICIPATE_METY { get; set; }
    }
}
