//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_EMOTIONLESS_METHOD
    {
        public HIS_EMOTIONLESS_METHOD()
        {
            this.HIS_DEBATE = new HashSet<HIS_DEBATE>();
            this.HIS_SERE_SERV_PTTT = new HashSet<HIS_SERE_SERV_PTTT>();
            this.HIS_SERE_SERV_PTTT1 = new HashSet<HIS_SERE_SERV_PTTT>();
            this.HIS_SERE_SERV_PTTT_TEMP = new HashSet<HIS_SERE_SERV_PTTT_TEMP>();
            this.HIS_SERE_SERV_PTTT_TEMP1 = new HashSet<HIS_SERE_SERV_PTTT_TEMP>();
            this.HIS_SURG_REMUNERATION = new HashSet<HIS_SURG_REMUNERATION>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string EMOTIONLESS_METHOD_CODE { get; set; }
        public string EMOTIONLESS_METHOD_NAME { get; set; }
        public Nullable<short> IS_FIRST { get; set; }
        public Nullable<short> IS_SECOND { get; set; }
        public Nullable<short> IS_ANAESTHESIA { get; set; }
        public string HEIN_CODE { get; set; }
    
        public virtual ICollection<HIS_DEBATE> HIS_DEBATE { get; set; }
        public virtual ICollection<HIS_SERE_SERV_PTTT> HIS_SERE_SERV_PTTT { get; set; }
        public virtual ICollection<HIS_SERE_SERV_PTTT> HIS_SERE_SERV_PTTT1 { get; set; }
        public virtual ICollection<HIS_SERE_SERV_PTTT_TEMP> HIS_SERE_SERV_PTTT_TEMP { get; set; }
        public virtual ICollection<HIS_SERE_SERV_PTTT_TEMP> HIS_SERE_SERV_PTTT_TEMP1 { get; set; }
        public virtual ICollection<HIS_SURG_REMUNERATION> HIS_SURG_REMUNERATION { get; set; }
    }
}
