//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_DESK
    {
        public HIS_DESK()
        {
            this.HIS_SERVICE_REQ = new HashSet<HIS_SERVICE_REQ>();
            this.HIS_SUBCLINICAL_RS_ADD = new HashSet<HIS_SUBCLINICAL_RS_ADD>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string DESK_CODE { get; set; }
        public string DESK_NAME { get; set; }
        public Nullable<long> ROOM_ID { get; set; }
        public Nullable<long> MAX_REQ_PER_DAY { get; set; }
        public Nullable<long> AREA_ID { get; set; }
    
        public virtual HIS_AREA HIS_AREA { get; set; }
        public virtual HIS_ROOM HIS_ROOM { get; set; }
        public virtual ICollection<HIS_SERVICE_REQ> HIS_SERVICE_REQ { get; set; }
        public virtual ICollection<HIS_SUBCLINICAL_RS_ADD> HIS_SUBCLINICAL_RS_ADD { get; set; }
    }
}
