//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_SEVERE_ILLNESS_INFO
    {
        public HIS_SEVERE_ILLNESS_INFO()
        {
            this.HIS_EVENTS_CAUSES_DEATH = new HashSet<HIS_EVENTS_CAUSES_DEATH>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public Nullable<short> IS_DEATH { get; set; }
        public Nullable<short> DEATH_TYPE { get; set; }
        public Nullable<short> IS_SEVERE_ILLNESS_HOME { get; set; }
        public Nullable<decimal> IS_WITHIN_4_WEEK_SURGERY { get; set; }
        public Nullable<long> SURGERY_DATE { get; set; }
        public string SURGERY_REASON { get; set; }
        public Nullable<short> IS_USING_FORENSIC_EXAMINATION { get; set; }
        public Nullable<short> DEATH_CAUSES_TYPE { get; set; }
        public Nullable<short> EXTERNAL_CAUSES { get; set; }
        public string OTHER_EXTERNAL_CAUSES { get; set; }
        public Nullable<short> IS_FETAL_OR_INFANT_DEATH { get; set; }
        public Nullable<short> MULTIPLE_PREGNANCY { get; set; }
        public Nullable<short> PREMATURE_BIRTH { get; set; }
        public Nullable<long> INFANT_AGE { get; set; }
        public Nullable<long> INFANT_WEIGHT { get; set; }
        public Nullable<long> FETAL_AGE { get; set; }
        public Nullable<long> MOTHER_AGE { get; set; }
        public string FETAL_INFANT_AFFECTED_ICD { get; set; }
        public Nullable<short> IS_DIED_WHEN_PREGNANCY { get; set; }
        public Nullable<short> TIME_OF_PREGNANCY { get; set; }
        public Nullable<short> IS_PREGNANCY_CAUSING_DEATH { get; set; }
        public string DEATH_MAIN_CAUSE { get; set; }
        public Nullable<long> TREATMENT_ID { get; set; }
        public Nullable<long> DEPARTMENT_ID { get; set; }
        public Nullable<long> ABSENT_DAY { get; set; }
        public Nullable<long> ICU_BED_DAYS_COUNT { get; set; }
    
        public virtual HIS_DEPARTMENT HIS_DEPARTMENT { get; set; }
        public virtual ICollection<HIS_EVENTS_CAUSES_DEATH> HIS_EVENTS_CAUSES_DEATH { get; set; }
        public virtual HIS_TREATMENT HIS_TREATMENT { get; set; }
    }
}
