//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_PTTT_GROUP
    {
        public HIS_PTTT_GROUP()
        {
            this.HIS_PTTT_GROUP_BEST = new HashSet<HIS_PTTT_GROUP_BEST>();
            this.HIS_PTTT_METHOD = new HashSet<HIS_PTTT_METHOD>();
            this.HIS_SERE_SERV_PTTT = new HashSet<HIS_SERE_SERV_PTTT>();
            this.HIS_SERE_SERV_PTTT_TEMP = new HashSet<HIS_SERE_SERV_PTTT_TEMP>();
            this.HIS_SERVICE = new HashSet<HIS_SERVICE>();
            this.HIS_SESE_PTTT_METHOD = new HashSet<HIS_SESE_PTTT_METHOD>();
            this.HIS_SURG_REMUNERATION = new HashSet<HIS_SURG_REMUNERATION>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string PTTT_GROUP_CODE { get; set; }
        public string PTTT_GROUP_NAME { get; set; }
        public Nullable<decimal> REMUNERATION { get; set; }
        public Nullable<long> NUM_ORDER { get; set; }
    
        public virtual ICollection<HIS_PTTT_GROUP_BEST> HIS_PTTT_GROUP_BEST { get; set; }
        public virtual ICollection<HIS_PTTT_METHOD> HIS_PTTT_METHOD { get; set; }
        public virtual ICollection<HIS_SERE_SERV_PTTT> HIS_SERE_SERV_PTTT { get; set; }
        public virtual ICollection<HIS_SERE_SERV_PTTT_TEMP> HIS_SERE_SERV_PTTT_TEMP { get; set; }
        public virtual ICollection<HIS_SERVICE> HIS_SERVICE { get; set; }
        public virtual ICollection<HIS_SESE_PTTT_METHOD> HIS_SESE_PTTT_METHOD { get; set; }
        public virtual ICollection<HIS_SURG_REMUNERATION> HIS_SURG_REMUNERATION { get; set; }
    }
}
