//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_IMP_MEST
    {
        public HIS_IMP_MEST()
        {
            this.HIS_BLOOD_GIVER = new HashSet<HIS_BLOOD_GIVER>();
            this.HIS_EXP_MEST = new HashSet<HIS_EXP_MEST>();
            this.HIS_IMP_MEST_BLOOD = new HashSet<HIS_IMP_MEST_BLOOD>();
            this.HIS_IMP_MEST1 = new HashSet<HIS_IMP_MEST>();
            this.HIS_IMP_MEST11 = new HashSet<HIS_IMP_MEST>();
            this.HIS_IMP_MEST_MATE_REQ = new HashSet<HIS_IMP_MEST_MATE_REQ>();
            this.HIS_IMP_MEST_MATERIAL = new HashSet<HIS_IMP_MEST_MATERIAL>();
            this.HIS_IMP_MEST_MEDI_REQ = new HashSet<HIS_IMP_MEST_MEDI_REQ>();
            this.HIS_IMP_MEST_MEDICINE = new HashSet<HIS_IMP_MEST_MEDICINE>();
            this.HIS_IMP_MEST_USER = new HashSet<HIS_IMP_MEST_USER>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string IMP_MEST_CODE { get; set; }
        public long IMP_MEST_TYPE_ID { get; set; }
        public long IMP_MEST_STT_ID { get; set; }
        public long MEDI_STOCK_ID { get; set; }
        public Nullable<long> MEDI_STOCK_PERIOD_ID { get; set; }
        public string IMP_LOGINNAME { get; set; }
        public string IMP_USERNAME { get; set; }
        public Nullable<long> IMP_TIME { get; set; }
        public Nullable<long> IMP_DATE { get; set; }
        public string APPROVAL_LOGINNAME { get; set; }
        public string APPROVAL_USERNAME { get; set; }
        public Nullable<long> APPROVAL_TIME { get; set; }
        public string REQ_LOGINNAME { get; set; }
        public string REQ_USERNAME { get; set; }
        public Nullable<long> REQ_ROOM_ID { get; set; }
        public Nullable<long> REQ_DEPARTMENT_ID { get; set; }
        public long CREATE_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> CHMS_EXP_MEST_ID { get; set; }
        public string TDL_CHMS_EXP_MEST_CODE { get; set; }
        public Nullable<long> AGGR_IMP_MEST_ID { get; set; }
        public string TDL_AGGR_IMP_MEST_CODE { get; set; }
        public Nullable<long> MOBA_EXP_MEST_ID { get; set; }
        public string TDL_MOBA_EXP_MEST_CODE { get; set; }
        public Nullable<long> TDL_TREATMENT_ID { get; set; }
        public Nullable<long> DISPENSE_ID { get; set; }
        public string TDL_DISPENSE_CODE { get; set; }
        public Nullable<long> SUPPLIER_ID { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public Nullable<long> DOCUMENT_DATE { get; set; }
        public Nullable<decimal> DOCUMENT_PRICE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> DISCOUNT_RATIO { get; set; }
        public string DELIVERER { get; set; }
        public string TDL_TREATMENT_CODE { get; set; }
        public Nullable<long> TDL_PATIENT_ID { get; set; }
        public string TDL_PATIENT_CODE { get; set; }
        public string TDL_PATIENT_NAME { get; set; }
        public Nullable<long> TDL_PATIENT_DOB { get; set; }
        public string TDL_PATIENT_ADDRESS { get; set; }
        public Nullable<long> TDL_PATIENT_GENDER_ID { get; set; }
        public string TDL_PATIENT_GENDER_NAME { get; set; }
        public string TDL_PATIENT_FIRST_NAME { get; set; }
        public string TDL_PATIENT_LAST_NAME { get; set; }
        public Nullable<short> TDL_PATIENT_IS_HAS_NOT_DAY_DOB { get; set; }
        public string NATIONAL_IMP_MEST_CODE { get; set; }
        public Nullable<long> IMP_MEST_PROPOSE_ID { get; set; }
        public string CREDIT_ACCOUNT { get; set; }
        public string DEBIT_ACCOUNT { get; set; }
        public string INVOICE_SYMBOL { get; set; }
        public Nullable<long> CHMS_TYPE_ID { get; set; }
        public Nullable<long> CHMS_MEDI_STOCK_ID { get; set; }
        public Nullable<long> SOURCE_MEST_PERIOD_ID { get; set; }
        public string IMP_MEST_SUB_CODE { get; set; }
        public string TDL_BID_NAMES { get; set; }
        public string TDL_BID_GROUP_CODES { get; set; }
        public string TDL_BID_NUMBERS { get; set; }
        public string RECEIVER_LOGINNAME { get; set; }
        public string RECEIVER_USERNAME { get; set; }
        public string IMP_MEST_SUB_CODE_2 { get; set; }
        public Nullable<long> SPECIAL_MEDICINE_NUM_ORDER { get; set; }
        public Nullable<long> SPECIAL_MEDICINE_TYPE { get; set; }
        public string VIR_SPECIAL_MEDICINE_NUM_ORDER { get; set; }
        public Nullable<decimal> VIR_CREATE_YEAR { get; set; }
        public Nullable<long> MEDICAL_CONTRACT_ID { get; set; }
        public Nullable<long> APPROVAL_IMP_MEST_ID { get; set; }
        public Nullable<long> TRACKING_ID { get; set; }
    
        public virtual ICollection<HIS_BLOOD_GIVER> HIS_BLOOD_GIVER { get; set; }
        public virtual HIS_DEPARTMENT HIS_DEPARTMENT { get; set; }
        public virtual HIS_DISPENSE HIS_DISPENSE { get; set; }
        public virtual ICollection<HIS_EXP_MEST> HIS_EXP_MEST { get; set; }
        public virtual HIS_EXP_MEST HIS_EXP_MEST1 { get; set; }
        public virtual HIS_EXP_MEST HIS_EXP_MEST2 { get; set; }
        public virtual ICollection<HIS_IMP_MEST_BLOOD> HIS_IMP_MEST_BLOOD { get; set; }
        public virtual HIS_IMP_MEST_TYPE HIS_IMP_MEST_TYPE { get; set; }
        public virtual HIS_IMP_MEST_PROPOSE HIS_IMP_MEST_PROPOSE { get; set; }
        public virtual HIS_MEDI_STOCK HIS_MEDI_STOCK { get; set; }
        public virtual HIS_MEDI_STOCK_PERIOD HIS_MEDI_STOCK_PERIOD { get; set; }
        public virtual HIS_MEDICAL_CONTRACT HIS_MEDICAL_CONTRACT { get; set; }
        public virtual ICollection<HIS_IMP_MEST> HIS_IMP_MEST1 { get; set; }
        public virtual HIS_IMP_MEST HIS_IMP_MEST2 { get; set; }
        public virtual HIS_MEDI_STOCK HIS_MEDI_STOCK1 { get; set; }
        public virtual ICollection<HIS_IMP_MEST> HIS_IMP_MEST11 { get; set; }
        public virtual HIS_IMP_MEST HIS_IMP_MEST3 { get; set; }
        public virtual HIS_MEDI_STOCK_PERIOD HIS_MEDI_STOCK_PERIOD1 { get; set; }
        public virtual HIS_ROOM HIS_ROOM { get; set; }
        public virtual HIS_SUPPLIER HIS_SUPPLIER { get; set; }
        public virtual ICollection<HIS_IMP_MEST_MATE_REQ> HIS_IMP_MEST_MATE_REQ { get; set; }
        public virtual ICollection<HIS_IMP_MEST_MATERIAL> HIS_IMP_MEST_MATERIAL { get; set; }
        public virtual ICollection<HIS_IMP_MEST_MEDI_REQ> HIS_IMP_MEST_MEDI_REQ { get; set; }
        public virtual ICollection<HIS_IMP_MEST_MEDICINE> HIS_IMP_MEST_MEDICINE { get; set; }
        public virtual ICollection<HIS_IMP_MEST_USER> HIS_IMP_MEST_USER { get; set; }
    }
}
