//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_HORE_HANDOVER
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string HORE_HANDOVER_CODE { get; set; }
        public long HORE_HANDOVER_STT_ID { get; set; }
        public string SEND_LOGINNAME { get; set; }
        public string SEND_USERNAME { get; set; }
        public long SEND_ROOM_ID { get; set; }
        public string RECEIVE_LOGINNAME { get; set; }
        public string RECEIVE_USERNAME { get; set; }
        public long RECEIVE_ROOM_ID { get; set; }
    
        public virtual HIS_ROOM HIS_ROOM { get; set; }
        public virtual HIS_ROOM HIS_ROOM1 { get; set; }
        public virtual HIS_HORE_HANDOVER_STT HIS_HORE_HANDOVER_STT { get; set; }
    }
}
