//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_HEIN_APPROVAL
    {
        public HIS_HEIN_APPROVAL()
        {
            this.HIS_SERE_SERV = new HashSet<HIS_SERE_SERV>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string HEIN_APPROVAL_CODE { get; set; }
        public long TREATMENT_ID { get; set; }
        public long TREATMENT_TYPE_ID { get; set; }
        public long CASHIER_ROOM_ID { get; set; }
        public string EXECUTE_LOGINNAME { get; set; }
        public string EXECUTE_USERNAME { get; set; }
        public Nullable<long> EXECUTE_TIME { get; set; }
        public string XML_URL { get; set; }
        public string LEVEL_CODE { get; set; }
        public string RIGHT_ROUTE_CODE { get; set; }
        public string RIGHT_ROUTE_TYPE_CODE { get; set; }
        public string LIVE_AREA_CODE { get; set; }
        public string HEIN_MEDI_ORG_CODE { get; set; }
        public string HEIN_MEDI_ORG_NAME { get; set; }
        public string HAS_BIRTH_CERTIFICATE { get; set; }
        public string HEIN_CARD_NUMBER { get; set; }
        public long HEIN_CARD_FROM_TIME { get; set; }
        public long HEIN_CARD_TO_TIME { get; set; }
        public string ADDRESS { get; set; }
        public string JOIN_5_YEAR { get; set; }
        public string PAID_6_MONTH { get; set; }
        public Nullable<long> FREE_CO_PAID_TIME { get; set; }
        public Nullable<long> JOIN_5_YEAR_TIME { get; set; }
    
        public virtual HIS_CASHIER_ROOM HIS_CASHIER_ROOM { get; set; }
        public virtual HIS_TREATMENT HIS_TREATMENT { get; set; }
        public virtual HIS_TREATMENT_TYPE HIS_TREATMENT_TYPE { get; set; }
        public virtual ICollection<HIS_SERE_SERV> HIS_SERE_SERV { get; set; }
    }
}
