//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_SERE_SERV_PTTT_TEMP
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public Nullable<long> PTTT_GROUP_ID { get; set; }
        public Nullable<long> PTTT_METHOD_ID { get; set; }
        public Nullable<long> PTTT_CONDITION_ID { get; set; }
        public Nullable<long> PTTT_CATASTROPHE_ID { get; set; }
        public Nullable<long> PTTT_HIGH_TECH_ID { get; set; }
        public Nullable<long> PTTT_PRIORITY_ID { get; set; }
        public Nullable<long> PTTT_TABLE_ID { get; set; }
        public Nullable<long> EMOTIONLESS_METHOD_ID { get; set; }
        public Nullable<long> EMOTIONLESS_METHOD_SECOND_ID { get; set; }
        public Nullable<long> EMOTIONLESS_RESULT_ID { get; set; }
        public Nullable<long> BLOOD_ABO_ID { get; set; }
        public Nullable<long> BLOOD_RH_ID { get; set; }
        public Nullable<long> DEATH_WITHIN_ID { get; set; }
        public string MANNER { get; set; }
        public Nullable<long> REAL_PTTT_METHOD_ID { get; set; }
        public Nullable<short> IS_PUBLIC { get; set; }
        public Nullable<short> IS_PUBLIC_IN_DEPARTMENT { get; set; }
        public Nullable<long> DEPARTMENT_ID { get; set; }
        public string CONCLUDE { get; set; }
        public string DESCRIPTION { get; set; }
        public string NOTE { get; set; }
        public string SERE_SERV_PTTT_TEMP_CODE { get; set; }
        public string SERE_SERV_PTTT_TEMP_NAME { get; set; }
    
        public virtual HIS_BLOOD_ABO HIS_BLOOD_ABO { get; set; }
        public virtual HIS_BLOOD_RH HIS_BLOOD_RH { get; set; }
        public virtual HIS_DEATH_WITHIN HIS_DEATH_WITHIN { get; set; }
        public virtual HIS_DEPARTMENT HIS_DEPARTMENT { get; set; }
        public virtual HIS_EMOTIONLESS_METHOD HIS_EMOTIONLESS_METHOD { get; set; }
        public virtual HIS_EMOTIONLESS_METHOD HIS_EMOTIONLESS_METHOD1 { get; set; }
        public virtual HIS_EMOTIONLESS_RESULT HIS_EMOTIONLESS_RESULT { get; set; }
        public virtual HIS_PTTT_CATASTROPHE HIS_PTTT_CATASTROPHE { get; set; }
        public virtual HIS_PTTT_CONDITION HIS_PTTT_CONDITION { get; set; }
        public virtual HIS_PTTT_GROUP HIS_PTTT_GROUP { get; set; }
        public virtual HIS_PTTT_HIGH_TECH HIS_PTTT_HIGH_TECH { get; set; }
        public virtual HIS_PTTT_METHOD HIS_PTTT_METHOD { get; set; }
        public virtual HIS_PTTT_METHOD HIS_PTTT_METHOD1 { get; set; }
        public virtual HIS_PTTT_PRIORITY HIS_PTTT_PRIORITY { get; set; }
        public virtual HIS_PTTT_TABLE HIS_PTTT_TABLE { get; set; }
    }
}
