//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_HIS_ROOM_COUNTER
    {
        public long ID { get; set; }
        public long ROOM_ID { get; set; }
        public string EXECUTE_ROOM_CODE { get; set; }
        public string EXECUTE_ROOM_NAME { get; set; }
        public Nullable<long> MAX_REQ_BHYT_BY_DAY { get; set; }
        public Nullable<long> MAX_REQUEST_BY_DAY { get; set; }
        public Nullable<long> NUM_ORDER { get; set; }
        public Nullable<short> IS_EXAM { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_PAUSE_ENCLITIC { get; set; }
        public Nullable<short> ALLOW_NOT_CHOOSE_SERVICE { get; set; }
        public long BRANCH_ID { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public long DEPARTMENT_ID { get; set; }
        public long ROOM_TYPE_ID { get; set; }
        public Nullable<long> AREA_ID { get; set; }
        public string RESPONSIBLE_USERNAME { get; set; }
        public string RESPONSIBLE_LOGINNAME { get; set; }
        public Nullable<long> RESPONSIBLE_TIME { get; set; }
        public string WORKING_USERNAME { get; set; }
        public string WORKING_LOGINNAME { get; set; }
        public Nullable<short> IS_BLOCK_NUM_ORDER { get; set; }
        public Nullable<long> DEFAULT_SERVICE_ID { get; set; }
        public Nullable<decimal> TOTAL_NEW_SERVICE_REQ { get; set; }
        public Nullable<decimal> TOTAL_TODAY_SERVICE_REQ { get; set; }
        public Nullable<decimal> TOTAL_WAIT_TODAY_SERVICE_REQ { get; set; }
        public Nullable<decimal> TOTAL_END_SERVICE_REQ { get; set; }
    }
}
