//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_CARER_CARD_BORROW
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long BORROW_TIME { get; set; }
        public Nullable<long> GIVE_BACK_TIME { get; set; }
        public long CARER_CARD_ID { get; set; }
        public long TREATMENT_ID { get; set; }
        public string GIVING_LOGINNAME { get; set; }
        public string GIVING_USERNAME { get; set; }
        public Nullable<short> IS_LOST { get; set; }
        public string RECEIVING_LOGINNAME { get; set; }
        public string RECEIVING_USERNAME { get; set; }
        public string TDL_SERVICE_NAME { get; set; }
        public string TDL_SERVICE_CODE { get; set; }
        public string TREATMENT_CODE { get; set; }
        public string TDL_PATIENT_CODE { get; set; }
        public string TDL_PATIENT_NAME { get; set; }
        public string TDL_PATIENT_GENDER_NAME { get; set; }
        public string IN_CODE { get; set; }
        public long TDL_PATIENT_DOB { get; set; }
        public Nullable<short> TDL_PATIENT_IS_HAS_NOT_DAY_DOB { get; set; }
        public string TDL_PATIENT_MOBILE { get; set; }
        public string TDL_PATIENT_PHONE { get; set; }
        public string TDL_PATIENT_CMND_NUMBER { get; set; }
        public string TDL_PATIENT_CCCD_NUMBER { get; set; }
        public string TDL_PATIENT_CAREER_NAME { get; set; }
        public string TDL_PATIENT_ETHNIC_NAME { get; set; }
        public string TDL_PATIENT_ADDRESS { get; set; }
        public string TDL_PATIENT_MILITARY_RANK_NAME { get; set; }
        public string TDL_PATIENT_WORK_PLACE { get; set; }
        public string TDL_PATIENT_WORK_PLACE_NAME { get; set; }
        public Nullable<long> TDL_PATIENT_POSITION_ID { get; set; }
        public long IN_TIME { get; set; }
        public string TDL_HEIN_CARD_NUMBER { get; set; }
        public Nullable<long> TDL_PATIENT_TYPE_ID { get; set; }
        public Nullable<long> TDL_PATIENT_CLASSIFY_ID { get; set; }
        public Nullable<short> TREATMENT_IS_ACTIVE { get; set; }
        public string PATIENT_CLASSIFY_NAME { get; set; }
        public string POSITION_NAME { get; set; }
        public string CARER_CARD_NUMBER { get; set; }
    }
}
