//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_MEDI_STOCK_PERIOD
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string MEDI_STOCK_PERIOD_NAME { get; set; }
        public long MEDI_STOCK_ID { get; set; }
        public Nullable<long> PREVIOUS_ID { get; set; }
        public Nullable<long> COUNT_MEDICINE_TYPE { get; set; }
        public Nullable<long> COUNT_MATERIAL_TYPE { get; set; }
        public Nullable<long> COUNT_IMP_MEST { get; set; }
        public Nullable<long> COUNT_EXP_MEST { get; set; }
        public Nullable<long> TO_TIME { get; set; }
        public Nullable<short> IS_APPROVE { get; set; }
        public Nullable<short> IS_AUTO_PERIOD { get; set; }
        public string MEDI_STOCK_CODE { get; set; }
        public string MEDI_STOCK_NAME { get; set; }
    }
}
