//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_SURG_REMUNERATION
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string SURG_REMUNERATION_CODE { get; set; }
        public string SURG_REMUNERATION_NAME { get; set; }
        public long PTTT_GROUP_ID { get; set; }
        public Nullable<long> EMOTIONLESS_METHOD_ID { get; set; }
        public Nullable<long> NUMBER_OF_PEOPLE { get; set; }
        public long SERVICE_TYPE_ID { get; set; }
        public Nullable<long> SURG_FROM_TIME { get; set; }
        public Nullable<long> SURG_TO_TIME { get; set; }
        public string PTTT_GROUP_CODE { get; set; }
        public string PTTT_GROUP_NAME { get; set; }
        public string EMOTIONLESS_METHOD_CODE { get; set; }
        public string EMOTIONLESS_METHOD_NAME { get; set; }
        public string SERVICE_TYPE_CODE { get; set; }
        public string SERVICE_TYPE_NAME { get; set; }
    }
}
