//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_CONTACT_POINT
    {
        public long ID { get; set; }
        public string CREATOR { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public string MODIFIER { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public Nullable<long> CONTACT_LEVEL { get; set; }
        public Nullable<long> PATIENT_ID { get; set; }
        public Nullable<long> EMPLOYEE_ID { get; set; }
        public long CONTACT_TYPE { get; set; }
        public string NOTE { get; set; }
        public Nullable<short> TEST_RESULT_1 { get; set; }
        public Nullable<short> TEST_RESULT_2 { get; set; }
        public Nullable<short> TEST_RESULT_3 { get; set; }
        public string CONTACT_POINT_OTHER_TYPE_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FULL_NAME { get; set; }
        public Nullable<long> GENDER_ID { get; set; }
        public Nullable<decimal> DOB { get; set; }
        public string VIR_ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public Nullable<decimal> DEPARTMENT_ID { get; set; }
        public string PATIENT_CODE { get; set; }
        public string LOGINNAME { get; set; }
    }
}
