//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_HOLD_RETURN
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long PATIENT_ID { get; set; }
        public string HEIN_CARD_NUMBER { get; set; }
        public long HOLD_TIME { get; set; }
        public string HOLD_LOGINNAME { get; set; }
        public string HOLD_USERNAME { get; set; }
        public long HOLD_ROOM_ID { get; set; }
        public long RESPONSIBLE_ROOM_ID { get; set; }
        public Nullable<short> IS_HANDOVERING { get; set; }
        public Nullable<long> RETURN_TIME { get; set; }
        public string RETURN_LOGINNAME { get; set; }
        public string RETURN_USERNAME { get; set; }
        public Nullable<long> RETURN_ROOM_ID { get; set; }
        public string VIR_UNIQUE { get; set; }
        public Nullable<long> TREATMENT_ID { get; set; }
        public string TREATMENT_CODE { get; set; }
        public string TDL_PATIENT_CODE { get; set; }
        public string TDL_PATIENT_NAME { get; set; }
        public string TDL_PATIENT_GENDER_NAME { get; set; }
        public long TDL_PATIENT_DOB { get; set; }
        public Nullable<short> TDL_PATIENT_IS_HAS_NOT_DAY_DOB { get; set; }
        public string TDL_PATIENT_ADDRESS { get; set; }
        public string TDL_PATIENT_FIRST_NAME { get; set; }
        public string TDL_PATIENT_LAST_NAME { get; set; }
        public Nullable<short> TREATMENT_IS_ACTIVE { get; set; }
        public Nullable<short> TREATMENT_IS_PAUSE { get; set; }
        public string RESPONSIBLE_ROOM_CODE { get; set; }
        public string RESPONSIBLE_ROOM_NAME { get; set; }
        public string DOC_HOLD_TYPE_NAMES { get; set; }
        public string DOC_HOLD_TYPE_IDS { get; set; }
    }
}
