//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_ACCOUNT_BOOK
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string ACCOUNT_BOOK_CODE { get; set; }
        public string ACCOUNT_BOOK_NAME { get; set; }
        public long TOTAL { get; set; }
        public long FROM_NUM_ORDER { get; set; }
        public Nullable<short> IS_FOR_DEPOSIT { get; set; }
        public Nullable<short> IS_FOR_REPAY { get; set; }
        public Nullable<short> IS_FOR_BILL { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> NUM_ORDER { get; set; }
        public string TEMPLATE_CODE { get; set; }
        public string SYMBOL_CODE { get; set; }
        public Nullable<long> RELEASE_TIME { get; set; }
        public Nullable<long> LINK_ID { get; set; }
        public Nullable<long> BILL_TYPE_ID { get; set; }
        public Nullable<short> IS_NOT_GEN_TRANSACTION_ORDER { get; set; }
        public Nullable<long> MAX_ITEM_NUM_PER_TRANS { get; set; }
        public Nullable<short> IS_FOR_DEBT { get; set; }
        public Nullable<short> IS_FOR_OTHER_SALE { get; set; }
        public Nullable<long> WORKING_SHIFT_ID { get; set; }
        public Nullable<long> EINVOICE_TYPE_ID { get; set; }
        public Nullable<short> NUM_ORDER_SPLIT_BY_BOOK { get; set; }
        public Nullable<decimal> CURRENT_NUM_ORDER { get; set; }
    }
}
