//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_MEST_PERIOD_BLOOD
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long MEDI_STOCK_PERIOD_ID { get; set; }
        public long BLOOD_ID { get; set; }
        public string BLOOD_CODE { get; set; }
        public long BLOOD_TYPE_ID { get; set; }
        public long BLOOD_ABO_ID { get; set; }
        public Nullable<long> BLOOD_RH_ID { get; set; }
        public Nullable<long> MEDI_STOCK_ID { get; set; }
        public Nullable<long> SUPPLIER_ID { get; set; }
        public Nullable<long> IMP_SOURCE_ID { get; set; }
        public Nullable<long> BID_ID { get; set; }
        public string BID_NUM_ORDER { get; set; }
        public decimal IMP_PRICE { get; set; }
        public decimal IMP_VAT_RATIO { get; set; }
        public Nullable<decimal> INTERNAL_PRICE { get; set; }
        public Nullable<long> IMP_TIME { get; set; }
        public Nullable<long> PACKING_TIME { get; set; }
        public string PACKAGE_NUMBER { get; set; }
        public Nullable<long> EXPIRED_DATE { get; set; }
        public Nullable<short> IS_INFECT { get; set; }
        public string GIVE_NAME { get; set; }
        public string GIVE_CODE { get; set; }
        public Nullable<short> IS_PREGNANT { get; set; }
        public Nullable<decimal> VIR_IMP_PRICE { get; set; }
        public Nullable<long> BLOOD_GIVE_ID { get; set; }
    }
}
