//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_EXP_MEST_BLTY_REQ
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public long EXP_MEST_ID { get; set; }
        public long BLOOD_TYPE_ID { get; set; }
        public Nullable<long> BLOOD_ABO_ID { get; set; }
        public Nullable<long> BLOOD_RH_ID { get; set; }
        public Nullable<long> PATIENT_TYPE_ID { get; set; }
        public long AMOUNT { get; set; }
        public Nullable<long> NUM_ORDER { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<short> IS_EXPEND { get; set; }
        public Nullable<long> SERE_SERV_PARENT_ID { get; set; }
        public Nullable<short> IS_OUT_PARENT_FEE { get; set; }
        public Nullable<decimal> DD_AMOUNT { get; set; }
        public long TDL_MEDI_STOCK_ID { get; set; }
        public Nullable<long> REQ_BLOOD_TYPE_ID { get; set; }
        public Nullable<long> REQ_BLOOD_ABO_ID { get; set; }
        public Nullable<long> REQ_BLOOD_RH_ID { get; set; }
        public Nullable<long> REQ_AMOUNT { get; set; }
        public Nullable<long> SERVICE_REQ_ID { get; set; }
        public string EXP_MEST_SUB_CODE { get; set; }
        public string EXP_MEST_SUB_CODE_2 { get; set; }
        public Nullable<long> TDL_TREATMENT_ID { get; set; }
        public long EXP_MEST_STT_ID { get; set; }
        public string BLOOD_TYPE_CODE { get; set; }
        public string BLOOD_TYPE_NAME { get; set; }
        public string BLOOD_ABO_CODE { get; set; }
        public string BLOOD_RH_CODE { get; set; }
    }
}
