//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_RATION_SCHEDULE
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public Nullable<long> TREATMENT_ID { get; set; }
        public Nullable<long> RATION_TIME_ID { get; set; }
        public Nullable<long> PATIENT_TYPE_ID { get; set; }
        public Nullable<long> SERVICE_ID { get; set; }
        public Nullable<long> REFECTORY_ROOM_ID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<long> FROM_TIME { get; set; }
        public Nullable<long> TO_TIME { get; set; }
        public Nullable<short> IS_FOR_HOMIE { get; set; }
        public Nullable<short> IS_HALF_IN_FIRST_DAY { get; set; }
        public string NOTE { get; set; }
        public Nullable<long> LAST_ASSIGN_DATE { get; set; }
        public Nullable<long> DEPARTMENT_ID { get; set; }
        public Nullable<long> VIR_FROM_DATE { get; set; }
        public Nullable<long> VIR_TO_DATE { get; set; }
        public string RATION_TIME_CODE { get; set; }
        public string RATION_TIME_NAME { get; set; }
        public string PATIENT_TYPE_CODE { get; set; }
        public string PATIENT_TYPE_NAME { get; set; }
        public string SERVICE_CODE { get; set; }
        public string SERVICE_NAME { get; set; }
        public string REFECTORY_ROOM_CODE { get; set; }
        public string REFECTORY_ROOM_NAME { get; set; }
        public string ICD_CODE { get; set; }
        public string ICD_NAME { get; set; }
        public string ICD_SUB_CODE { get; set; }
        public string ICD_TEXT { get; set; }
        public Nullable<long> LAST_DEPARTMENT_ID { get; set; }
        public Nullable<long> PATIENT_ID { get; set; }
        public Nullable<long> TDL_TREATMENT_TYPE_ID { get; set; }
        public Nullable<long> TDL_HEIN_CARD_FROM_TIME { get; set; }
        public string TDL_PATIENT_ACCOUNT_NUMBER { get; set; }
        public string TDL_PATIENT_ADDRESS { get; set; }
        public string TDL_PATIENT_AVATAR_URL { get; set; }
        public string TDL_PATIENT_CAREER_NAME { get; set; }
        public Nullable<long> TDL_PATIENT_CCCD_DATE { get; set; }
        public string TDL_PATIENT_CCCD_NUMBER { get; set; }
        public string TDL_PATIENT_CCCD_PLACE { get; set; }
        public Nullable<long> TDL_PATIENT_CLASSIFY_ID { get; set; }
        public Nullable<long> TDL_PATIENT_CMND_DATE { get; set; }
        public string TDL_PATIENT_CMND_NUMBER { get; set; }
        public string TDL_PATIENT_CMND_PLACE { get; set; }
        public string TDL_PATIENT_CODE { get; set; }
        public string TDL_PATIENT_COMMUNE_CODE { get; set; }
        public string TDL_PATIENT_COMMUNE_NAME { get; set; }
        public string TDL_PATIENT_DISTRICT_CODE { get; set; }
        public string TDL_PATIENT_DISTRICT_NAME { get; set; }
        public Nullable<long> TDL_PATIENT_DOB { get; set; }
        public string TDL_PATIENT_ETHNIC_NAME { get; set; }
        public string TDL_PATIENT_FATHER_NAME { get; set; }
        public string TDL_PATIENT_FIRST_NAME { get; set; }
        public Nullable<long> TDL_PATIENT_GENDER_ID { get; set; }
        public string TDL_PATIENT_GENDER_NAME { get; set; }
        public Nullable<short> TDL_PATIENT_IS_HAS_NOT_DAY_DOB { get; set; }
        public string TDL_PATIENT_LAST_NAME { get; set; }
        public string TDL_PATIENT_MILITARY_RANK_NAME { get; set; }
        public string TDL_PATIENT_MOBILE { get; set; }
        public string TDL_PATIENT_MOTHER_NAME { get; set; }
        public string TDL_PATIENT_MPS_NATIONAL_CODE { get; set; }
        public string TDL_PATIENT_NAME { get; set; }
        public string TDL_PATIENT_NATIONAL_CODE { get; set; }
        public string TDL_PATIENT_NATIONAL_NAME { get; set; }
        public Nullable<long> TDL_PATIENT_PASSPORT_DATE { get; set; }
        public string TDL_PATIENT_PASSPORT_NUMBER { get; set; }
        public string TDL_PATIENT_PASSPORT_PLACE { get; set; }
        public string TDL_PATIENT_PHONE { get; set; }
        public Nullable<long> TDL_PATIENT_POSITION_ID { get; set; }
        public string TDL_PATIENT_PROVINCE_CODE { get; set; }
        public string TDL_PATIENT_PROVINCE_NAME { get; set; }
        public string TDL_PATIENT_RELATIVE_ADDRESS { get; set; }
        public string TDL_PATIENT_RELATIVE_MOBILE { get; set; }
        public string TDL_PATIENT_RELATIVE_NAME { get; set; }
        public string TDL_PATIENT_RELATIVE_PHONE { get; set; }
        public string TDL_PATIENT_RELATIVE_TYPE { get; set; }
        public string TDL_PATIENT_TAX_CODE { get; set; }
        public Nullable<long> TDL_PATIENT_TYPE_ID { get; set; }
        public string TDL_PATIENT_UNSIGNED_NAME { get; set; }
        public string TDL_PATIENT_WORK_PLACE { get; set; }
        public Nullable<long> TDL_PATIENT_WORK_PLACE_ID { get; set; }
        public string TDL_PATIENT_WORK_PLACE_NAME { get; set; }
        public string TDL_HEIN_CARD_NUMBER { get; set; }
        public Nullable<long> TDL_HEIN_CARD_TO_TIME { get; set; }
        public string TDL_HEIN_MEDI_ORG_CODE { get; set; }
        public string TDL_HEIN_MEDI_ORG_NAME { get; set; }
        public Nullable<long> OUT_TIME { get; set; }
        public Nullable<short> IS_PAUSE { get; set; }
        public string LAST_DEPARTMENT_CODE { get; set; }
        public string LAST_DEPARTMENT_NAME { get; set; }
    }
}
