//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_MATERIAL_TYPE
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string MATERIAL_TYPE_CODE { get; set; }
        public string MATERIAL_TYPE_NAME { get; set; }
        public long SERVICE_ID { get; set; }
        public Nullable<long> PARENT_ID { get; set; }
        public Nullable<short> IS_LEAF { get; set; }
        public Nullable<long> NUM_ORDER { get; set; }
        public string CONCENTRA { get; set; }
        public Nullable<long> PACKING_TYPE_ID__DELETE { get; set; }
        public Nullable<long> MANUFACTURER_ID { get; set; }
        public long TDL_SERVICE_UNIT_ID { get; set; }
        public Nullable<long> TDL_GENDER_ID { get; set; }
        public string NATIONAL_NAME { get; set; }
        public Nullable<decimal> IMP_PRICE { get; set; }
        public Nullable<decimal> IMP_VAT_RATIO { get; set; }
        public Nullable<decimal> INTERNAL_PRICE { get; set; }
        public Nullable<long> ALERT_EXPIRED_DATE { get; set; }
        public Nullable<decimal> ALERT_MIN_IN_STOCK { get; set; }
        public Nullable<decimal> ALERT_MAX_IN_PRESCRIPTION { get; set; }
        public Nullable<short> IS_CHEMICAL_SUBSTANCE { get; set; }
        public Nullable<short> IS_AUTO_EXPEND { get; set; }
        public Nullable<short> IS_STENT { get; set; }
        public Nullable<short> IS_IN_KTC_FEE { get; set; }
        public Nullable<short> IS_ALLOW_ODD { get; set; }
        public Nullable<short> IS_ALLOW_EXPORT_ODD { get; set; }
        public Nullable<short> IS_STOP_IMP { get; set; }
        public Nullable<short> IS_REQUIRE_HSD { get; set; }
        public Nullable<short> IS_SALE_EQUAL_IMP_PRICE { get; set; }
        public Nullable<short> IS_BUSINESS { get; set; }
        public Nullable<short> IS_RAW_MATERIAL { get; set; }
        public Nullable<short> IS_MUST_PREPARE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> MEMA_GROUP_ID { get; set; }
        public string PACKING_TYPE_NAME { get; set; }
        public Nullable<short> IS_REUSABLE { get; set; }
        public Nullable<long> MAX_REUSE_COUNT { get; set; }
        public string MATERIAL_GROUP_BHYT { get; set; }
        public Nullable<long> MATERIAL_TYPE_MAP_ID { get; set; }
        public Nullable<decimal> LAST_EXP_PRICE { get; set; }
        public Nullable<decimal> LAST_EXP_VAT_RATIO { get; set; }
        public Nullable<decimal> LAST_IMP_PRICE { get; set; }
        public Nullable<decimal> LAST_IMP_VAT_RATIO { get; set; }
        public Nullable<long> FILM_SIZE_ID { get; set; }
        public Nullable<short> IS_FILM { get; set; }
        public Nullable<long> LAST_EXPIRED_DATE { get; set; }
        public string RECORDING_TRANSACTION { get; set; }
        public string REGISTER_NUMBER { get; set; }
        public Nullable<short> IS_CONSUMABLE { get; set; }
        public Nullable<short> IS_OUT_HOSPITAL { get; set; }
        public Nullable<long> IMP_UNIT_ID { get; set; }
        public Nullable<decimal> IMP_UNIT_CONVERT_RATIO { get; set; }
        public Nullable<short> IS_DRUG_STORE { get; set; }
        public Nullable<short> IS_NOT_SHOW_TRACKING { get; set; }
        public string LOCKING_REASON { get; set; }
        public Nullable<decimal> ALERT_MAX_IN_DAY { get; set; }
        public string MODEL_CODE { get; set; }
        public long SERVICE_UNIT_ID { get; set; }
        public long SERVICE_TYPE_ID { get; set; }
        public Nullable<long> HEIN_SERVICE_TYPE_ID { get; set; }
        public Nullable<short> BILL_OPTION { get; set; }
        public Nullable<short> IS_OUT_PARENT_FEE { get; set; }
        public string HEIN_SERVICE_BHYT_CODE { get; set; }
        public string HEIN_SERVICE_BHYT_NAME { get; set; }
        public string HEIN_ORDER { get; set; }
        public Nullable<decimal> HEIN_LIMIT_PRICE_OLD { get; set; }
        public Nullable<decimal> HEIN_LIMIT_PRICE { get; set; }
        public Nullable<decimal> HEIN_LIMIT_RATIO_OLD { get; set; }
        public Nullable<decimal> HEIN_LIMIT_RATIO { get; set; }
        public Nullable<long> HEIN_LIMIT_PRICE_IN_TIME { get; set; }
        public Nullable<long> HEIN_LIMIT_PRICE_INTR_TIME { get; set; }
        public string SERVICE_UNIT_CODE { get; set; }
        public string SERVICE_UNIT_NAME { get; set; }
        public Nullable<decimal> CONVERT_RATIO { get; set; }
        public string MANUFACTURER_CODE { get; set; }
        public string MANUFACTURER_NAME { get; set; }
        public string HEIN_SERVICE_TYPE_CODE { get; set; }
        public string HEIN_SERVICE_TYPE_NAME { get; set; }
        public string CONVERT_UNIT_CODE { get; set; }
        public string CONVERT_UNIT_NAME { get; set; }
        public string MATERIAL_TYPE_MAP_CODE { get; set; }
        public string MATERIAL_TYPE_MAP_NAME { get; set; }
        public string IMP_UNIT_CODE { get; set; }
        public string IMP_UNIT_NAME { get; set; }
        public string PARENT_CODE { get; set; }
        public string PARENT_NAME { get; set; }
    }
}
