//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOS.EFMODEL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_VITAMIN_A
    {
        public long ID { get; set; }
        public Nullable<long> CREATE_TIME { get; set; }
        public Nullable<long> MODIFY_TIME { get; set; }
        public string CREATOR { get; set; }
        public string MODIFIER { get; set; }
        public string APP_CREATOR { get; set; }
        public string APP_MODIFIER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public string GROUP_CODE { get; set; }
        public string VITAMIN_A_CODE { get; set; }
        public long PATIENT_ID { get; set; }
        public long BRANCH_ID { get; set; }
        public Nullable<long> NUM_ORDER { get; set; }
        public long REQUEST_TIME { get; set; }
        public long REQUEST_DATE { get; set; }
        public long REQUEST_ROOM_ID { get; set; }
        public long REQUEST_DEPARTMENT_ID { get; set; }
        public string REQUEST_LOGINNAME { get; set; }
        public string REQUEST_USERNAME { get; set; }
        public Nullable<long> EXECUTE_TIME { get; set; }
        public Nullable<long> EXECUTE_DATE { get; set; }
        public long EXECUTE_ROOM_ID { get; set; }
        public long EXECUTE_DEPARTMENT_ID { get; set; }
        public string EXECUTE_LOGINNAME { get; set; }
        public string EXECUTE_USERNAME { get; set; }
        public Nullable<long> EXP_MEST_ID { get; set; }
        public Nullable<long> MEDICINE_TYPE_ID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public long CASE_TYPE { get; set; }
        public Nullable<short> IS_SICK { get; set; }
        public Nullable<short> IS_ONE_MONTH_BORN { get; set; }
        public string TDL_PATIENT_CODE { get; set; }
        public string TDL_PATIENT_NAME { get; set; }
        public string TDL_PATIENT_FIRST_NAME { get; set; }
        public string TDL_PATIENT_LAST_NAME { get; set; }
        public long TDL_PATIENT_DOB { get; set; }
        public Nullable<short> TDL_PATIENT_IS_HAS_NOT_DAY_DOB { get; set; }
        public string TDL_PATIENT_ADDRESS { get; set; }
        public Nullable<long> TDL_PATIENT_GENDER_ID { get; set; }
        public string TDL_PATIENT_GENDER_NAME { get; set; }
        public string TDL_PATIENT_CAREER_NAME { get; set; }
        public string TDL_PATIENT_WORK_PLACE { get; set; }
        public string TDL_PATIENT_WORK_PLACE_NAME { get; set; }
        public Nullable<short> IS_MALNUTRITION { get; set; }
        public Nullable<short> IS_YDT_UPLOAD { get; set; }
        public string MEDICINE_TYPE_CODE { get; set; }
        public string MEDICINE_TYPE_NAME { get; set; }
        public string EXP_MEST_CODE { get; set; }
        public Nullable<long> EXP_MEST_TYPE_ID { get; set; }
        public Nullable<long> EXP_MEST_STT_ID { get; set; }
        public Nullable<long> MEDI_STOCK_ID { get; set; }
        public string REQUEST_DEPARTMENT_CODE { get; set; }
        public string REQUEST_DEPARTMENT_NAME { get; set; }
        public string EXECUTE_DEPARTMENT_CODE { get; set; }
        public string EXECUTE_DEPARTMENT_NAME { get; set; }
        public string REQUEST_ROOM_CODE { get; set; }
        public string REQUEST_ROOM_NAME { get; set; }
        public string EXECUTE_ROOM_CODE { get; set; }
        public string EXECUTE_ROOM_NAME { get; set; }
    }
}
