//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRS.LibraryMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageViResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageViResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRS.LibraryMessage.MessageViResource", typeof(MessageViResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có thông tin biểu mẫu, vui lòng tải biểu mẫu lên.
        /// </summary>
        internal static string BieuMauKhongCoThongTinFile {
            get {
                return ResourceManager.GetString("BieuMauKhongCoThongTinFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đang bị khóa.
        /// </summary>
        internal static string Common__DuLieuDangBiKhoa {
            get {
                return ResourceManager.GetString("Common__DuLieuDangBiKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận vận hành thiết lập thiếu cấu hình hệ thống.
        /// </summary>
        internal static string Common__LoiCauHinhHeThong {
            get {
                return ResourceManager.GetString("Common__LoiCauHinhHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu có mã đã tồn tại trên hệ thống.
        /// </summary>
        internal static string Common__MaDaTonTaiTrenHeThong {
            get {
                return ResourceManager.GetString("Common__MaDaTonTaiTrenHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu thiếu trường thông tin bắt buộc.
        /// </summary>
        internal static string Common__ThieuThongTinBatBuoc {
            get {
                return ResourceManager.GetString("Common__ThieuThongTinBatBuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo bị giới hạn thời gian. Vui lòng tạo báo cáo sau {0}.
        /// </summary>
        internal static string Core_MrsReport_Create__GoiHanThoiGianDen {
            get {
                return ResourceManager.GetString("Core_MrsReport_Create__GoiHanThoiGianDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo bị giới hạn thời gian. Vui lòng tạo báo cáo trước {0}.
        /// </summary>
        internal static string Core_MrsReport_Create__GoiHanThoiGianTu {
            get {
                return ResourceManager.GetString("Core_MrsReport_Create__GoiHanThoiGianTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo bị giới hạn thời gian. Vui lòng tạo báo cáo ngoài khoảng thời gian từ {0} đến {1}.
        /// </summary>
        internal static string Core_MrsReport_Create__GoiHanThoiGianTuDen {
            get {
                return ResourceManager.GetString("Core_MrsReport_Create__GoiHanThoiGianTuDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy bộ xử lý của báo cáo {0}, vui lòng nâng cấp hệ thống..
        /// </summary>
        internal static string Core_MrsReport_Create__KhongTimDuocDLL {
            get {
                return ResourceManager.GetString("Core_MrsReport_Create__KhongTimDuocDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy biểu mẫu trên máy chủ, vui lòng tải lên biểu mẫu mới.
        /// </summary>
        internal static string Core_MrsReport_Create__KhongTimDuocFileBieuMauTrenMayChu {
            get {
                return ResourceManager.GetString("Core_MrsReport_Create__KhongTimDuocFileBieuMauTrenMayChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi Upload file..
        /// </summary>
        internal static string Core_MrsReport_Create__LoiFss {
            get {
                return ResourceManager.GetString("Core_MrsReport_Create__LoiFss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi trong quá trình lấy dữ liệu báo cáo.
        /// </summary>
        internal static string Core_MrsReport_Create__LoiGetData {
            get {
                return ResourceManager.GetString("Core_MrsReport_Create__LoiGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi biểu mẫu.
        /// </summary>
        internal static string Core_MrsReport_Create__LoiTemplate {
            get {
                return ResourceManager.GetString("Core_MrsReport_Create__LoiTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi câu truy vấn.
        /// </summary>
        internal static string Core_MrsReport_Create__LoiTruyVan {
            get {
                return ResourceManager.GetString("Core_MrsReport_Create__LoiTruyVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi trong quá trình xử lý dữ liệu báo cáo.
        /// </summary>
        internal static string Core_MrsReport_Create__LoiXuLyDuLieu {
            get {
                return ResourceManager.GetString("Core_MrsReport_Create__LoiXuLyDuLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đã hoàn thành xử lý yêu cầu báo cáo của bạn. Mã yêu cầu báo cáo: {0}; tên loại báo cáo: {1}; mã loại báo cáo: {2}; mã biểu mẫu: {3}. Bạn vui lòng truy cập chức năng danh sách báo cáo để tải file dữ liệu..
        /// </summary>
        internal static string SarReport_MessageContentComplete {
            get {
                return ResourceManager.GetString("SarReport_MessageContentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đã không thể hoàn thành xử lý yêu cầu báo cáo của bạn. Mã yêu cầu báo cáo: {0}; tên loại báo cáo: {1}; mã loại báo cáo: {2}; mã biểu mẫu: {3}. Bạn vui lòng liên hệ với quản trị hệ thống để được hỗ trợ. Chúng tôi rất lấy làm tiếc về trường hợp này và sẽ khắc phục trong thời gian sớm nhất..
        /// </summary>
        internal static string SarReport_MessageContentError {
            get {
                return ResourceManager.GetString("SarReport_MessageContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành xử lý yêu cầu báo cáo..
        /// </summary>
        internal static string SarReport_MessageTitleError {
            get {
                return ResourceManager.GetString("SarReport_MessageTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        internal static string SarReport_SystemName {
            get {
                return ResourceManager.GetString("SarReport_SystemName", resourceCulture);
            }
        }
    }
}
